### ISSUE TITLE
Simple database migration doesn't succeed

### ISSUE THREAD

**Issue by jmelich** [FusionAuth/fusionauth-issues#1161]
Migrating database with a dump doesn't succeed

Under a Ubuntu 18 we have a Fusionauth 1.7.2  which data is stored in a local MariaDB database. We are trying to migrate to a MySQL Amazon RDS instance given MariaDB is not compatible with Fusionauth 1.7.2 greater versions.

It seems it should be easy as: 
1) Dump local MariaDB
2) Restore to dump to remote MySQL 
3) Change database pointer in Fusionauth config files(/usr/local/fusionauth/config/fusionauth.properties) to the new database.
4) Reboot server.

After this steps, fusionauth-app is not booting throwing the following errors:

```
===================================================================================================

  Unable to start the server. Here's why: 


[Error injecting constructor, java.lang.NullPointerException] 
	-> [class java.lang.NullPointerException] null

===================================================================================================


Apr 09, 2021 10:51:21.950 AM ERROR org.primeframework.mvc.guice.GuiceBootstrap - Unable to start the server. Exception: 

com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.NullPointerException
  at com.inversoft.cache.DefaultCacheRegistry.<init>(DefaultCacheRegistry.java:28)
  while locating com.inversoft.cache.DefaultCacheRegistry
  at com.inversoft.cache.guice.CacheModule.configure(CacheModule.java:22) (via modules: io.fusionauth.app.guice.FusionAuthModule -> com.google.inject.util.Modules$OverrideModule -> io.fusionauth.api.guice.APIModule -> io.fusionauth.api.service.guice.ServiceModule -> io.fusionauth.api.service.guice.FusionAuthCacheModule)
  while locating com.inversoft.cache.CacheRegistry
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at io.fusionauth.api.security.JWTVerifierProvider.getVerifier(JWTVerifierProvider.java:90)
	at io.fusionauth.api.security.JWTVerifierProvider.onCacheLoad(JWTVerifierProvider.java:76)
	at com.inversoft.cache.atomic.ManualAtomicCache.lambda$loadClearPutAllAndNotify$0(ManualAtomicCache.java:85)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.inversoft.cache.atomic.ManualAtomicCache.loadClearPutAllAndNotify(ManualAtomicCache.java:85)
	at com.inversoft.cache.atomic.ManualAtomicCache.<init>(ManualAtomicCache.java:35)
	at com.inversoft.cache.atomic.AtomicCache.<init>(AtomicCache.java:25)
	at com.inversoft.cache.atomic.AtomicCache$Builder.build(AtomicCache.java:60)
	at io.fusionauth.api.service.cache.FusionAuthCacheFactory.build(FusionAuthCacheFactory.java:98)
	at com.inversoft.cache.DefaultCacheRegistry.<init>(DefaultCacheRegistry.java:30)
	at com.inversoft.cache.DefaultCacheRegistry$$FastClassByGuice$$dd8d0c9d.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at org.primeframework.mvc.guice.GuiceBootstrap.initialize(GuiceBootstrap.java:58)
	at com.inversoft.maintenance.MaintenanceModeService.done(MaintenanceModeService.java:47)
	at com.inversoft.maintenance.action.MaintenanceModeDoneAction.lambda$get$0(MaintenanceModeDoneAction.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2) Error injecting constructor, java.lang.NullPointerException
  at io.fusionauth.api.domain.guice.FusionAuthTenantIdProvider.<init>(FusionAuthTenantIdProvider.java:20)
  while locating io.fusionauth.api.domain.guice.FusionAuthTenantIdProvider
  at io.fusionauth.api.domain.guice.FusionAuthClientModule.configure(FusionAuthClientModule.java:18) (via modules: io.fusionauth.app.guice.FusionAuthModule -> com.google.inject.util.Modules$OverrideModule -> io.fusionauth.api.guice.APIModule -> io.fusionauth.api.domain.guice.FusionAuthClientModule)
  while locating java.util.UUID annotated with interface io.fusionauth.api.domain.guice.FusionAuthTenantId
Caused by: java.lang.NullPointerException
	at io.fusionauth.api.domain.guice.FusionAuthTenantIdProvider.<init>(FusionAuthTenantIdProvider.java:21)
	at io.fusionauth.api.domain.guice.FusionAuthTenantIdProvider$$FastClassByGuice$$2dc4e0cf.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:60)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at org.primeframework.mvc.guice.GuiceBootstrap.initialize(GuiceBootstrap.java:58)
	at com.inversoft.maintenance.MaintenanceModeService.done(MaintenanceModeService.java:47)
	at com.inversoft.maintenance.action.MaintenanceModeDoneAction.lambda$get$0(MaintenanceModeDoneAction.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at org.primeframework.mvc.guice.GuiceBootstrap.initialize(GuiceBootstrap.java:58)
	at com.inversoft.maintenance.MaintenanceModeService.done(MaintenanceModeService.java:47)
	at com.inversoft.maintenance.action.MaintenanceModeDoneAction.lambda$get$0(MaintenanceModeDoneAction.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Apr 09, 2021 10:51:31.982 AM INFO  io.fusionauth.app.guice.FusionAuthModule - 

---------------------------------------------------------------------------------------------------------
---------------------------------- Starting FusionAuth version [1.7.2] ----------------------------------
---------------------------------------------------------------------------------------------------------

Apr 09, 2021 10:51:32.011 AM INFO  io.fusionauth.api.plugin.guice.PluginModule - No plugins found
Apr 09, 2021 10:51:32.076 AM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Loading FusionAuth configuration file [/usr/local/fusionauth/fusionauth-app/apache-tomcat/../../config/fusionauth.properties]
Apr 09, 2021 10:51:32.076 AM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Dynamically set property [fusionauth-app.public-url] set to [http://172.17.0.1:9011]
Apr 09, 2021 10:51:32.076 AM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - FusionAuth Runtime Mode [Production]
Apr 09, 2021 10:51:32.077 AM INFO  com.inversoft.jdbc.hikari.DataSourceProvider - Connecting to MySQL database at [jdbc:mysql://blablabla.blablabla.eu-west-3.rds.amazonaws.com:3306/authdatabase?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true]
Apr 09, 2021 10:51:32.077 AM INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-4 - Starting...
Apr 09, 2021 10:51:32.181 AM INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-4 - Start completed.
Apr 09, 2021 10:51:32.611 AM INFO  com.inversoft.scheduler.DefaultScheduler - Starting up scheduler
Apr 09, 2021 10:51:32.612 AM INFO  com.inversoft.scheduler.DefaultScheduler - Scheduler is running
Apr 09, 2021 10:51:32.637 AM INFO  io.fusionauth.api.service.system.NodeService - Add node with address [http://172.17.0.1:9011]
Apr 09, 2021 10:51:32.811 AM ERROR com.inversoft.scheduler.LogAndRetainFailureHandler - The scheduled service [class io.fusionauth.api.service.metrics.MetricsLogger] failed but will be re-run.
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NullPointerException
  at com.inversoft.cache.DefaultCacheRegistry.<init>(DefaultCacheRegistry.java:28)
  while locating com.inversoft.cache.DefaultCacheRegistry
  at com.inversoft.cache.guice.CacheModule.configure(CacheModule.java:22) (via modules: io.fusionauth.app.guice.FusionAuthModule -> com.google.inject.util.Modules$OverrideModule -> io.fusionauth.api.guice.APIModule -> io.fusionauth.api.service.guice.ServiceModule -> io.fusionauth.api.service.guice.FusionAuthCacheModule)
  while locating com.inversoft.cache.CacheRegistry
    for the 1st parameter of io.fusionauth.api.service.messaging.KafkaService.<init>(KafkaService.java:47)
  while locating io.fusionauth.api.service.messaging.KafkaService
    for the 2nd parameter of io.fusionauth.api.service.event.DefaultEventService.<init>(DefaultEventService.java:48)
  while locating io.fusionauth.api.service.event.DefaultEventService
  while locating io.fusionauth.api.service.event.EventService
    for the 3rd parameter of io.fusionauth.api.service.application.DefaultApplicationService.<init>(DefaultApplicationService.java:96)
  while locating io.fusionauth.api.service.application.DefaultApplicationService
  while locating io.fusionauth.api.service.application.ApplicationService
    for the 1st parameter of io.fusionauth.api.service.system.DefaultSetupService.<init>(DefaultSetupService.java:66)
  while locating io.fusionauth.api.service.system.DefaultSetupService
  while locating io.fusionauth.api.service.system.SetupService
    for the 6th parameter of io.fusionauth.api.service.metrics.MetricsLogger.<init>(MetricsLogger.java:53)
  while locating io.fusionauth.api.service.metrics.MetricsLogger

1 error
	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
	at com.inversoft.scheduler.InjectableRunnable.run(InjectableRunnable.java:31)
	at com.inversoft.scheduler.DefaultScheduler.<init>(DefaultScheduler.java:74)
	at com.inversoft.scheduler.DefaultScheduler$$FastClassByGuice$$b3f770e0.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at org.primeframework.mvc.guice.GuiceBootstrap.initialize(GuiceBootstrap.java:58)
	at com.inversoft.maintenance.MaintenanceModeService.done(MaintenanceModeService.java:47)
	at com.inversoft.maintenance.action.MaintenanceModeDoneAction.lambda$get$0(MaintenanceModeDoneAction.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203)
	at io.fusionauth.api.security.JWTVerifierProvider.getVerifier(JWTVerifierProvider.java:90)
	at io.fusionauth.api.security.JWTVerifierProvider.onCacheLoad(JWTVerifierProvider.java:76)
	at com.inversoft.cache.atomic.ManualAtomicCache.lambda$loadClearPutAllAndNotify$0(ManualAtomicCache.java:85)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.inversoft.cache.atomic.ManualAtomicCache.loadClearPutAllAndNotify(ManualAtomicCache.java:85)
	at com.inversoft.cache.atomic.ManualAtomicCache.<init>(ManualAtomicCache.java:35)
	at com.inversoft.cache.atomic.AtomicCache.<init>(AtomicCache.java:25)
	at com.inversoft.cache.atomic.AtomicCache$Builder.build(AtomicCache.java:60)
	at io.fusionauth.api.service.cache.FusionAuthCacheFactory.build(FusionAuthCacheFactory.java:98)
	at com.inversoft.cache.DefaultCacheRegistry.<init>(DefaultCacheRegistry.java:30)
	at com.inversoft.cache.DefaultCacheRegistry$$FastClassByGuice$$dd8d0c9d.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
	... 25 common frames omitted
Apr 09, 2021 10:51:32.871 AM INFO  com.inversoft.migration.Migrator - Run Cleanup [io.fusionauth.api.migration.guice.Migration_1_2_0]
Apr 09, 2021 10:51:32.880 AM INFO  com.inversoft.migration.Migrator - Run Cleanup [io.fusionauth.api.migration.guice.Migration_1_3_0]
Apr 09, 2021 10:51:32.888 AM INFO  com.inversoft.migration.Migrator - Run Cleanup [io.fusionauth.api.migration.guice.Migration_1_3_1]
Apr 09, 2021 10:51:32.897 AM INFO  com.inversoft.migration.Migrator - Run Cleanup [io.fusionauth.api.migration.guice.Migration_1_5_0]
Apr 09, 2021 10:51:32.905 AM INFO  com.inversoft.migration.Migrator - Run Cleanup [io.fusionauth.api.migration.guice.Migration_1_6_0]
Apr 09, 2021 10:51:32.913 AM INFO  com.inversoft.migration.Migrator - Run Cleanup [io.fusionauth.api.migration.guice.Migration_1_7_0]
Apr 09, 2021 10:51:32.921 AM ERROR org.primeframework.mvc.guice.GuiceBootstrap - 

===================================================================================================

  Unable to start the server. Here's why: 


[Error injecting constructor, java.lang.NullPointerException] 
	-> [class java.lang.NullPointerException] null

===================================================================================================


Apr 09, 2021 10:51:32.922 AM ERROR org.primeframework.mvc.guice.GuiceBootstrap - Unable to start the server. Exception: 

com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.NullPointerException
  at com.inversoft.cache.DefaultCacheRegistry.<init>(DefaultCacheRegistry.java:28)
  while locating com.inversoft.cache.DefaultCacheRegistry
  at com.inversoft.cache.guice.CacheModule.configure(CacheModule.java:22) (via modules: io.fusionauth.app.guice.FusionAuthModule -> com.google.inject.util.Modules$OverrideModule -> io.fusionauth.api.guice.APIModule -> io.fusionauth.api.service.guice.ServiceModule -> io.fusionauth.api.service.guice.FusionAuthCacheModule)
  while locating com.inversoft.cache.CacheRegistry
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at io.fusionauth.api.security.JWTVerifierProvider.getVerifier(JWTVerifierProvider.java:90)
	at io.fusionauth.api.security.JWTVerifierProvider.onCacheLoad(JWTVerifierProvider.java:76)
	at com.inversoft.cache.atomic.ManualAtomicCache.lambda$loadClearPutAllAndNotify$0(ManualAtomicCache.java:85)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.inversoft.cache.atomic.ManualAtomicCache.loadClearPutAllAndNotify(ManualAtomicCache.java:85)
	at com.inversoft.cache.atomic.ManualAtomicCache.<init>(ManualAtomicCache.java:35)
	at com.inversoft.cache.atomic.AtomicCache.<init>(AtomicCache.java:25)
	at com.inversoft.cache.atomic.AtomicCache$Builder.build(AtomicCache.java:60)
	at io.fusionauth.api.service.cache.FusionAuthCacheFactory.build(FusionAuthCacheFactory.java:98)
	at com.inversoft.cache.DefaultCacheRegistry.<init>(DefaultCacheRegistry.java:30)
	at com.inversoft.cache.DefaultCacheRegistry$$FastClassByGuice$$dd8d0c9d.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at org.primeframework.mvc.guice.GuiceBootstrap.initialize(GuiceBootstrap.java:58)
	at com.inversoft.maintenance.MaintenanceModeService.done(MaintenanceModeService.java:47)
	at com.inversoft.maintenance.action.MaintenanceModeDoneAction.lambda$get$0(MaintenanceModeDoneAction.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2) Error injecting constructor, java.lang.NullPointerException
  at io.fusionauth.api.domain.guice.FusionAuthTenantIdProvider.<init>(FusionAuthTenantIdProvider.java:20)
  while locating io.fusionauth.api.domain.guice.FusionAuthTenantIdProvider
  at io.fusionauth.api.domain.guice.FusionAuthClientModule.configure(FusionAuthClientModule.java:18) (via modules: io.fusionauth.app.guice.FusionAuthModule -> com.google.inject.util.Modules$OverrideModule -> io.fusionauth.api.guice.APIModule -> io.fusionauth.api.domain.guice.FusionAuthClientModule)
  while locating java.util.UUID annotated with interface io.fusionauth.api.domain.guice.FusionAuthTenantId
Caused by: java.lang.NullPointerException
	at io.fusionauth.api.domain.guice.FusionAuthTenantIdProvider.<init>(FusionAuthTenantIdProvider.java:21)
	at io.fusionauth.api.domain.guice.FusionAuthTenantIdProvider$$FastClassByGuice$$2dc4e0cf.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:60)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at org.primeframework.mvc.guice.GuiceBootstrap.initialize(GuiceBootstrap.java:58)
	at com.inversoft.maintenance.MaintenanceModeService.done(MaintenanceModeService.java:47)
	at com.inversoft.maintenance.action.MaintenanceModeDoneAction.lambda$get$0(MaintenanceModeDoneAction.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at org.primeframework.mvc.guice.GuiceBootstrap.initialize(GuiceBootstrap.java:58)
	at com.inversoft.maintenance.MaintenanceModeService.done(MaintenanceModeService.java:47)
	at com.inversoft.maintenance.action.MaintenanceModeDoneAction.lambda$get$0(MaintenanceModeDoneAction.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

I also tried a fresh installation of Fusionauth 1.7.2 with a local database with the production dump loaded, and it throws the same error.

As I can see there is an error related with cache but I'm not sure where to flush it. 

Can someone help me to fix it?

NOTE: I know is an older version, but until it works on a MySQL database I cannot upgrade Fusionauth

Thanks in advance!

**Comment by mooreds** [comment]
So this is an unsupported use case with an old version of FusionAuth, but I'll try to help. You are trying to migrate from FusionAuth 1.7.2 on MariaDB to FusionAuth 1.7.2 on mysql, correct? What version of mysql?

Also, can you install a new copy of FusionAuth 1.7.2 onto MariaDB and see if you can port it over to mysql and see if you see the same issue?

An alternative if you can't get the database dump to work would be to export everything via the API and import it. You can't export the password hashes and other password related info (salt) but you could pull that from the database and use the bulk import API.

**Comment by jmelich** [comment]
@mooreds thanks  for your reply ;)

I'm still testing if I can find any workaround either with a fresh installation or other versions.

For now I can say there is the same issue with a fresh installation on 1.7.2 when I export database, but it works if I install directly on it.

About exporting via API is there a builtin service or function or I have to develop it?

Thanks .

**Comment by jmelich** [comment]
I've tried with both MySQL 5.7.34 and 8.0.21 getting the same result.

I've also tried a fresh  installation of the most recent FusionAuth(1.26.0)  pointing to this databases but crashes when performing the updates at 1.8.0-RC.1

```
-- Update the version
UPDATE version
SET version = '1.8.0-RC.1';
.  Cause: java.sql.SQLSyntaxErrorException: Table 'themes' already exists
	at org.apache.ibatis.jdbc.ScriptRunner.executeFullScript(ScriptRunner.java:142)
	at org.apache.ibatis.jdbc.ScriptRunner.runScript(ScriptRunner.java:117)
	at com.inversoft.maintenance.db.SQLExecutor.executeSQLScriptWithError(SQLExecutor.java:43)
	at com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService.upgrade(JDBCMaintenanceModeDatabaseService.java:357)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	... 1 common frames omitted

```

Seems that 1.26.0 can establish a connection with the database and wants to perform an upgrade. If I can upgrade the database and use a fresh instance poiting to it is another valid solution for me.

Could someone help me with it?


Thanks in advance

**Comment by jmelich** [comment]
@mooreds We've tried with different database and fusionauth versions, obtaining the same behaviour. I think the main fault could be mysqldump parameters which could be exporting a corrupted or incomplete database. Did you successfully a migration yet? If so, could you remember if you paid special attention in any mysqdump parameter?

**Comment by jmelich** [comment]
As I told I've been unlucky and I were trying extra parameters on mysqldump from the start,  making the result wrong or uncompatible, so for me the following was the right one being simpler than I expected:

**1. Database creation in MySQL 8.0.21:**
`create schema fusionauth collate utf8mb4_0900_ai_ci;`

**2. Generate dump:**
`mysqldump --host=hostname --port=3306 --databases fusionauth --user=user --password="**********" --default-character-set=utf8mb4  --result-file=/destination_path/filename.sql`

**3. Restaurar backup:**
`mysql --host=hostname --port=6603 -u root -p fusionauth < /source_path/filename.sql`


Having said that I think the crux of this is: `-default-character-set=utf8mb4` on step 2 on dump` generation.

Thanks once again @mooreds for your time ;)

**Comment by mooreds** [comment]
Glad you sorted this out, @jmelich !
