### ISSUE TITLE
Implicit grant - after login, the given redirect_uri isnt honored.

### ISSUE THREAD

**Issue by botnyx** [FusionAuth/fusionauth-issues#119]
### Description 
When using implicit grant,  the authorization endpoints returns error about 'invalid_origin'

### Steps to reproduce
1. enable implicit mode only.
2. set redir urls.
3. configure client, and login.
4. after login, a error states : invalid origin uri

### Expected behavior

a redirect should occur.
The loginscreen url clearly states the correct redirect url, yet after submission it gives the invalid origin error.

the FusionAuth thinks the redirect is incorrect, as its always assumes its 'https://my.fusioninstance.ext'  (the actual fusionauth server) 

## Login screen url 

`https://my.fusioninstance.ext/oauth2/authorize?client_id=e6049d14-88e4-4cb7-ac72-111c512a8ceb&response_type=token&redirect_uri=https://my.app.ext/oauthJS/redirect.html&state={"client_id":"e6049d14-88e4-4cb7-ac72-111c512a8ceb","network":"mynetwork","display":"page","callback":"_hellojs_1398hlvz","state":"","redirect_uri":"https://my.app.ext/oauthJS/redirect.html","scope":"basic,email","page_uri":"https://my.app.ext/oauthJS/index.html"}&scope=email`

## The Error after login

`error=invalid_request&error_reason=invalid_origin&error_description=Invalid+origin+uri+https%3A%2F%2Fmy.fusioninstance.ext&
`

Somehow, fusionauth doesnt honor the redirect_uri as given on the login-uri..

**Comment by robotdan** [comment]
Hi @botnyx 

I wonder if this is related to your other issue https://github.com/FusionAuth/fusionauth-issues/issues/118. 

Your state parameter is not properly encoded, so it may mess up what we are able to capture from the request. 

```
&state={"client_id":"e6049d14-88e4-4cb7-ac72-111c512a8ceb","network":"mynetwork","display":"page","callback":"_hellojs_1398hlvz","state":"","redirect_uri":"https://my.app.ext/oauthJS/redirect.html","scope":"basic,email","page_uri":"https://my.app.ext/oauthJS/index.html"}
```

You'll need to make sure you URL encode this parameter before appending it to the URL as the `state` value. The same will go for the `redirect_uri` value `https://my.app.ext/oauthJS/redirect.html`. 

All values need to be encoded, but the value for `client_id`, `response_type` and `scope` do not contain any characters that require escaping, so they aren't causing any problems.

**Comment by botnyx** [comment]
i url-decoded the url for readability's sake, so that is not it.

Besides that, im not in control of the link that gets created, like i said:  i press login, and the redirects end up in a invalid-origin error.

**Comment by robotdan** [comment]
Can you add the un-decoded URL so I can see what it looks like? When you press login, do you mean login in your application that then redirects to FusionAuth, or do you mean when you submit the login form in FusionAuth?

**Comment by robotdan** [comment]
Regarding the initial error you mentioned : 

```
error=invalid_request&error_reason=invalid_origin&error_description=Invalid+origin+uri+https%3A%2F%2Fmy.fusioninstance.ext&
```

What do you have configured for authorized redirect URLs, and authorized request origins? 

The origin is an optional configuration that if omitted will allow all origins. Have you tried removing the origin validation?

**Comment by botnyx** [comment]
Here are my settings : 

![image](https://user-images.githubusercontent.com/27279013/56084215-2133e100-5e30-11e9-9933-83540de2db2f.png)

You can check the exact flow via :  https://bootstd.botnyx.com/oauthJS/index.html

user: test@test.test
pass: test12345678

When you try to login into the admin, you see it works ( dont worry: the account has zero rights)

**Comment by robotdan** [comment]
Thanks @botnyx that is very helpful. I was able to observe the issue using the link you sent me. I have an idea of what may be going on. 

Can you try removing your `Authorized request origin URLs` configuration, and try again? If that works, then I think I understand what is happening.

**Comment by botnyx** [comment]
When the Authorized request origin urls are removed, it indeed works.

**Comment by robotdan** [comment]
Great, thanks for the update. 

It think this is a bug in the way we are validating request origin. The symptom seems to occur only when you submit the form during authentication and FusionAuth is behind a proxy of some sort. 

For now, the work-around will be to remove request origin validation. This will be fixed in the next release. 

Thanks for reporting the issue, much appreciated. My assumption is that this will correct the other issue you have open as well. https://github.com/FusionAuth/fusionauth-issues/issues/118 Update that issue if it is not resolved with this workaround.

**Comment by asif-ICM** [comment]
**i am using   FusionAuth™ version 1.29.2**
1- I create OpenID Connect Idp for Microsoft.
2- when I try to log in, it some time successful and sometimes gives an error.
I- error in browser url `(#error=invalid_request&error_reason=invalid_origin&error_description=Invalid+origin+uri+https:%2F%2Flogin.live.com%2F)`
II- error in Event Log Failed to complete a login for Identity Provider [DDA 1].
```

The following errors occurred:

{
  "fieldErrors" : { },
  "generalErrors" : [ {
    "code" : "[Exception]",
    "message" : "FusionAuth encountered an unexpected error. Please review the troubleshooting guide found in the documentation for assistance and the available support channels."
  } ]
}
```
III- error in logs
```
2021-09-29 5:54:18.587 AM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'encryption_scheme' cannot be null
### The error may exist in io/fusionauth/api/domain/UserMapper.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: INSERT INTO identities (users_id, breached_password_last_checked_instant, breached_password_status, connectors_id, email, encryption_scheme, factor, insert_instant, last_login_instant, last_update_instant, password, password_change_reason, password_change_required, password_last_update_instant, salt, tenants_id, username, username_index, username_status, verified, status)       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, UPPER(?), ?, ?, ?)
### Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'encryption_scheme' cannot be null
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:196)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181)
	at jdk.internal.reflect.GeneratedMethodAccessor238.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.ibatis.session.SqlSessionManager$SqlSessionInterceptor.invoke(SqlSessionManager.java:350)
	at com.sun.proxy.$Proxy52.insert(Unknown Source)
	at org.apache.ibatis.session.SqlSessionManager.insert(SqlSessionManager.java:236)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	at com.sun.proxy.$Proxy92.createIdentity(Unknown Source)
	at io.fusionauth.api.service.user.DefaultUserService.updateAllowConnectorIdChange(DefaultUserService.java:1205)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
	at io.fusionauth.api.service.user.DefaultUserService.update(DefaultUserService.java:1142)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
	at io.fusionauth.api.service.authentication.BaseIdentityProviderAuthenticationService.updateUser(BaseIdentityProviderAuthenticationService.java:492)
	at io.fusionauth.api.service.authentication.BaseIdentityProviderAuthenticationService.completeLogin(BaseIdentityProviderAuthenticationService.java:196)
	at io.fusionauth.api.service.authentication.BaseIdentityProviderAuthenticationService.completeLogin(BaseIdentityProviderAuthenticationService.java:138)
	at io.fusionauth.api.service.authentication.OpenIdConnectIdentityProviderAuthenticationService._login(OpenIdConnectIdentityProviderAuthenticationService.java:162)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
	at io.fusionauth.api.service.authentication.BaseIdentityProviderAuthenticationService.login(BaseIdentityProviderAuthenticationService.java:111)
	at io.fusionauth.app.action.api.identityProvider.LoginAction.lambda$post$0(LoginAction.java:63)
	at io.fusionauth.app.action.api.BaseLoginAction.callLogin(BaseLoginAction.java:167)
	at io.fusionauth.app.action.api.identityProvider.LoginAction.post(LoginAction.java:63)
	at jdk.internal.reflect.GeneratedMethodAccessor1194.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.primeframework.mvc.util.ReflectionUtils.invoke(ReflectionUtils.java:414)
	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.execute(DefaultActionInvocationWorkflow.java:79)
	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.perform(DefaultActionInvocationWorkflow.java:62)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:47)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.security.DefaultSecurityWorkflow.perform(DefaultSecurityWorkflow.java:60)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.parameter.DefaultPostParameterWorkflow.perform(DefaultPostParameterWorkflow.java:50)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.content.DefaultContentWorkflow.perform(DefaultContentWorkflow.java:52)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:57)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:102)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:58)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:44)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:126)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.workflow.StaticResourceWorkflow.perform(StaticResourceWorkflow.java:97)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.parameter.RequestBodyWorkflow.perform(RequestBodyWorkflow.java:91)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:64)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at io.fusionauth.app.primeframework.CORSFilter.doFilter(CORSFilter.java:262)
	at io.fusionauth.app.primeframework.CORSRequestWorkflow.perform(CORSRequestWorkflow.java:49)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at io.fusionauth.app.primeframework.FusionAuthMVCWorkflow.perform(FusionAuthMVCWorkflow.java:86)
	at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44)
	at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50)
	at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:78)
	at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:353)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1629)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'encryption_scheme' cannot be null
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)
	... 93 common frames omitted
```

**Comment by asif-ICM** [comment]
> **i am using FusionAuth™ version 1.29.2** 1- I create OpenID Connect Idp for Microsoft. 2- when I try to log in, it some time successful and sometimes gives an error. I- error in browser url `(#error=invalid_request&error_reason=invalid_origin&error_description=Invalid+origin+uri+https:%2F%2Flogin.live.com%2F)` II- error in Event Log Failed to complete a login for Identity Provider [DDA 1].
> 
> ```
> 
> The following errors occurred:
> 
> {
>   "fieldErrors" : { },
>   "generalErrors" : [ {
>     "code" : "[Exception]",
>     "message" : "FusionAuth encountered an unexpected error. Please review the troubleshooting guide found in the documentation for assistance and the available support channels."
>   } ]
> }
> ```
> 
> III- error in logs
> 
> ```
> 2021-09-29 5:54:18.587 AM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
> org.apache.ibatis.exceptions.PersistenceException: 
> ### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'encryption_scheme' cannot be null
> ### The error may exist in io/fusionauth/api/domain/UserMapper.xml
> ### The error may involve defaultParameterMap
> ### The error occurred while setting parameters
> ### SQL: INSERT INTO identities (users_id, breached_password_last_checked_instant, breached_password_status, connectors_id, email, encryption_scheme, factor, insert_instant, last_login_instant, last_update_instant, password, password_change_reason, password_change_required, password_last_update_instant, salt, tenants_id, username, username_index, username_status, verified, status)       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, UPPER(?), ?, ?, ?)
> ### Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'encryption_scheme' cannot be null
> 	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
> 	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:196)
> 	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181)
> 	at jdk.internal.reflect.GeneratedMethodAccessor238.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> 	at org.apache.ibatis.session.SqlSessionManager$SqlSessionInterceptor.invoke(SqlSessionManager.java:350)
> 	at com.sun.proxy.$Proxy52.insert(Unknown Source)
> 	at org.apache.ibatis.session.SqlSessionManager.insert(SqlSessionManager.java:236)
> 	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
> 	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145)
> 	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
> 	at com.sun.proxy.$Proxy92.createIdentity(Unknown Source)
> 	at io.fusionauth.api.service.user.DefaultUserService.updateAllowConnectorIdChange(DefaultUserService.java:1205)
> 	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
> 	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
> 	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
> 	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
> 	at io.fusionauth.api.service.user.DefaultUserService.update(DefaultUserService.java:1142)
> 	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
> 	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
> 	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
> 	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
> 	at io.fusionauth.api.service.authentication.BaseIdentityProviderAuthenticationService.updateUser(BaseIdentityProviderAuthenticationService.java:492)
> 	at io.fusionauth.api.service.authentication.BaseIdentityProviderAuthenticationService.completeLogin(BaseIdentityProviderAuthenticationService.java:196)
> 	at io.fusionauth.api.service.authentication.BaseIdentityProviderAuthenticationService.completeLogin(BaseIdentityProviderAuthenticationService.java:138)
> 	at io.fusionauth.api.service.authentication.OpenIdConnectIdentityProviderAuthenticationService._login(OpenIdConnectIdentityProviderAuthenticationService.java:162)
> 	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
> 	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
> 	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
> 	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
> 	at io.fusionauth.api.service.authentication.BaseIdentityProviderAuthenticationService.login(BaseIdentityProviderAuthenticationService.java:111)
> 	at io.fusionauth.app.action.api.identityProvider.LoginAction.lambda$post$0(LoginAction.java:63)
> 	at io.fusionauth.app.action.api.BaseLoginAction.callLogin(BaseLoginAction.java:167)
> 	at io.fusionauth.app.action.api.identityProvider.LoginAction.post(LoginAction.java:63)
> 	at jdk.internal.reflect.GeneratedMethodAccessor1194.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> 	at org.primeframework.mvc.util.ReflectionUtils.invoke(ReflectionUtils.java:414)
> 	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.execute(DefaultActionInvocationWorkflow.java:79)
> 	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.perform(DefaultActionInvocationWorkflow.java:62)
> 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
> 	at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:47)
> 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
> 	at org.primeframework.mvc.security.DefaultSecurityWorkflow.perform(DefaultSecurityWorkflow.java:60)
> 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
> 	at org.primeframework.mvc.parameter.DefaultPostParameterWorkflow.perform(DefaultPostParameterWorkflow.java:50)
> 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
> 	at org.primeframework.mvc.content.DefaultContentWorkflow.perform(DefaultContentWorkflow.java:52)
> 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
> 	at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:57)
> 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
> 	at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:102)
> 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
> 	at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:58)
> 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
> 	at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:44)
> 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
> 	at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:126)
> 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
> 	at org.primeframework.mvc.workflow.StaticResourceWorkflow.perform(StaticResourceWorkflow.java:97)
> 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
> 	at org.primeframework.mvc.parameter.RequestBodyWorkflow.perform(RequestBodyWorkflow.java:91)
> 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
> 	at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:64)
> 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
> 	at io.fusionauth.app.primeframework.CORSFilter.doFilter(CORSFilter.java:262)
> 	at io.fusionauth.app.primeframework.CORSRequestWorkflow.perform(CORSRequestWorkflow.java:49)
> 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
> 	at io.fusionauth.app.primeframework.FusionAuthMVCWorkflow.perform(FusionAuthMVCWorkflow.java:86)
> 	at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44)
> 	at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50)
> 	at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:78)
> 	at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:63)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:353)
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1629)
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.base/java.lang.Thread.run(Thread.java:832)
> Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'encryption_scheme' cannot be null
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
> 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
> 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
> 	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
> 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
> 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
> 	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
> 	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
> 	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
> 	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
> 	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
> 	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)
> 	... 93 common frames omitted
> ```

@robotdan please can you help.

**Comment by mooreds** [comment]
@asif-ICM Please open a separate issue with full replication steps if you think this is a bug.

If you are looking for support, please open a support ticket if you have a support contract: account.fusionauth.io/account/support If you don't have a support contract, please use the community forum: https://fusionauth.io/community/forum/
