### ISSUE TITLE
Support multiple signing certificates per SAML IdP

### ISSUE THREAD

**Issue by epbensimpson** [FusionAuth/fusionauth-issues#1213]
### Problem
Some IdPs advertise multiple signing certificates in their federation metadata. This is generally to allow for graceful rollover of certificates. It is expected that the party verifying the tokens supports all the certificates in the metadata.

Unfortunately, because FusionAuth only supports a single certificate / verification key per IdP at present, this results in signature verification errors when the certificate used for signing differs from the one loaded.

Per the [Azure AD documentation](https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/azure-ad-federation-metadata#token-signing-certificates) (ignore the fact this page is deprecated, it's still relevant):
> A federation metadata document published by Azure AD can have multiple signing keys, such as when Azure AD is preparing to update the signing certificate. When a federation metadata document includes more than one certificate, a service that is validating the tokens should support all certificates in the document.

Relevant question on SO: https://stackoverflow.com/a/35949089/3435144

Additionally, the error logging contains no contextual information about which `IdP` was impacted or what the expected vs actual thumbprint is etc., making it impossible to ascribe the error to a specific `IdP`.

### Solution
* The ability to load multiple signing certificates for each `IdP`
* Better contextual information provided in SAML2 errors

### Alternatives/workarounds
* The only real workaround is to try loading the advertised certificates one-by-one until one works, and hope they don't start signing with one of the others in the meantime.

### Additional context
Example error message:
```
Unable to parse or validate SAML response.


Exception:
io.fusionauth.samlv2.domain.SAMLException: Invalid SAML v2.0 authentication response. The signature is invalid.
	at io.fusionauth.samlv2.service.DefaultSAMLv2Service.verifySignature(DefaultSAMLv2Service.java:848)
	at io.fusionauth.samlv2.service.DefaultSAMLv2Service.parseResponse(DefaultSAMLv2Service.java:511)
	at io.fusionauth.api.service.authentication.SAMLv2IdentityProviderAuthenticationService._login(SAMLv2IdentityProviderAuthenticationService.java:92)
	at io.fusionauth.api.service.authentication.SAMLv2IdentityProviderAuthenticationService$$EnhancerByGuice$$8bbdc4f1.CGLIB$_login$0(<generated>)
	at io.fusionauth.api.service.authentication.SAMLv2IdentityProviderAuthenticationService$$EnhancerByGuice$$8bbdc4f1$$FastClassByGuice$$740b1bd4.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:54)
	at io.fusionauth.api.service.authentication.SAMLv2IdentityProviderAuthenticationService$$EnhancerByGuice$$8bbdc4f1._login(<generated>)
	at io.fusionauth.api.service.authentication.BaseIdentityProviderAuthenticationService.login(BaseIdentityProviderAuthenticationService.java:88)
	at io.fusionauth.app.action.api.identityProvider.LoginAction.lambda$post$0(LoginAction.java:62)
	at io.fusionauth.app.action.api.BaseLoginAction.callLogin(BaseLoginAction.java:165)
	at io.fusionauth.app.action.api.identityProvider.LoginAction.post(LoginAction.java:62)
	at jdk.internal.reflect.GeneratedMethodAccessor123.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.primeframework.mvc.util.ReflectionUtils.invoke(ReflectionUtils.java:414)
	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.execute(DefaultActionInvocationWorkflow.java:79)
	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.perform(DefaultActionInvocationWorkflow.java:62)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:47)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.security.DefaultSecurityWorkflow.perform(DefaultSecurityWorkflow.java:60)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.parameter.DefaultPostParameterWorkflow.perform(DefaultPostParameterWorkflow.java:50)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.content.DefaultContentWorkflow.perform(DefaultContentWorkflow.java:52)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:57)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:102)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:58)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:44)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at io.fusionauth.app.primeframework.FrontEndTenantWorkflow.perform(FrontEndTenantWorkflow.java:71)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:126)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.workflow.StaticResourceWorkflow.perform(StaticResourceWorkflow.java:97)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.parameter.RequestBodyWorkflow.perform(RequestBodyWorkflow.java:89)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:64)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at io.fusionauth.app.primeframework.CORSFilter.handleNonCORS(CORSFilter.java:291)
	at io.fusionauth.app.primeframework.CORSFilter.doFilter(CORSFilter.java:252)
	at io.fusionauth.app.primeframework.CORSRequestWorkflow.perform(CORSRequestWorkflow.java:48)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at io.fusionauth.app.primeframework.FusionAuthMVCWorkflow.perform(FusionAuthMVCWorkflow.java:88)
	at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44)
	at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50)
	at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:78)
	at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
From the context, it sounds like you are using a Azure SAML IdP and FusionAuth is the SAML SP which needs to verify the AuthN Response signature.

If this is the case, FusionAuth will be able to verify the signature as long as the public certificate exists in KeyMaster.

In this case, do you have all possible public keys available in KeyMaster?

**Comment by epbensimpson** [comment]
Yes, FusionAuth is our SP and we have a number of ADFS/Azure AD IdPs we are integrating with.

I will note down adding all the signing certificates to the KeyMaster as a possible workaround but if that _does_ work I'm not sure FusionAuth is handling this correctly?

* FusionAuth provides a single `Verification Key` parameter when adding a Saml2 IdP
* The FusionAuth docs [specify ](https://fusionauth.io/docs/v1/tech/identity-providers/samlv2/adfs/) that the certificate used for this should be that from the `ds:Signature`, however that is just the _certificate used to sign the metadata_
* The actual certificate(s) that may be used by the IdP to sign are found in the `IDPSSODescriptor`
* Given your assertion that as long as the certificates exist in KeyMaster they can be used to verify the request, what is the point of the `Verification Key` parameter if it apparently does nothing?

Is there something I'm missing here?

**Comment by robotdan** [comment]
> Given your assertion that as long as the certificates exist in KeyMaster they can be used to verify the request, what is the point of the Verification Key parameter if it apparently does nothing?

Part of the reason for the configuration is historical. In practice, the configured verification key is the default verification key if one cannot be resolved by reviewing the `KeyInfo` elements in the SAML response. 

In the past we only allowed a response to be verified by a single key, that is the reason for the verification key configuration.  

We choose to leave this configuration because it helps us enforce that at least one verification key has been added to Key Master, and it allows FusionAuth to verify a SAML response even if the IdP does not add a `KeyInfo` element, or does not properly build a certificate thumbprint for us to identify the signing key. 

> (edit) Additionally, why check keys that exist in the KeyMaster but aren't explicitly linked to the IdP?


This would be a possibility, it would just mean that after you import key, you would have to explicitly indicate you would like this key to be used by a particular IdP to verify the SAML response. In practice we haven't found a use case where you want a valid public key imported into Key Master, that is currently in use by an IdP, but do not want to use it to verify a SAML response.

**Comment by robotdan** [comment]
Suggestion taken! :-) 

@mooreds Can we use this issue to add some additional details to the SAML v2 IdP config and API (for the `keyId` field and the corresponding field in the UI walk through to better describe how FusionAuth will resolve keys during the SAML response verification process?

**Comment by davidmw** [comment]
@robotdan I'm adding on to this related issue, apologies if it should be a new one.

We had a key expire last month and sadly had no notification until a chance encounter with failed customer logins captured in our log. Seems that ADFS defaults to generate public certificates that expire in a year.

System generated key expiration notices could prevent some headaches.

I'm coming at this from a noob vantage point - but could the IdP configuration support a URL for the federation metadata? And with that extract the certificate and maintain the keys as they rollover?  It is a bit of a hassle to manually extract the certificate or download and convert the .cer to PEM, to create a new key to preserve or restore client access and the issue will expand as we configure multiple ADFS IdPs.
