### ISSUE TITLE
I cannot install version 1.26.1

### ISSUE THREAD

**Issue by Thangamh** [FusionAuth/fusionauth-issues#1252]
## Issue with version 1.26.1

Hi, I was trying to install fusionauth 1.26.1 with postgres and elasticsearch cluster. I turned on silent configuration and when the installation is on docker. When the fusionauth appliucation starts Im getting this error,

2021-06-07 3:07:07.832 AM INFO  com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService - [zGop6w] Attempting to lock database to prevent multi-node issues
2021-06-07 3:07:07.888 AM INFO  com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService - [zGop6w] Obtained a database lock
2021-06-07 3:07:08.043 AM INFO  com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService - [zGop6w] Database Version [1.26.0]
2021-06-07 3:07:08.044 AM INFO  com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService - [zGop6w] Latest Migration Version [1.26.0]
2021-06-07 3:07:08.047 AM INFO  com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService - [zGop6w] Attempting to unlock database to prevent multi-node issues
2021-06-07 3:07:08.048 AM INFO  com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService - [zGop6w] Unlock completed
2021-06-07 3:07:08.068 AM INFO  com.inversoft.search.ElasticRestClientHelper - Connecting to Elasticsearch at [http://10.197.56.173:9200]
2021-06-07 3:07:08.069 AM INFO  com.inversoft.search.ElasticRestClientHelper - Connecting to Elasticsearch at [http://10.197.56.168:9200]
2021-06-07 3:07:08.070 AM INFO  com.inversoft.search.ElasticRestClientHelper - Connecting to Elasticsearch at [http://10.197.56.170:9200]
2021-06-07 3:07:08.934 AM INFO  com.inversoft.maintenance.search.ElasticsearchMaintenanceModeSearchService - Missing search index [fusionauth_entity]
2021-06-07 3:07:08.975 AM INFO  com.inversoft.search.ElasticRestClientHelper - Connecting to Elasticsearch at [http://10.197.56.173:9200]
2021-06-07 3:07:08.976 AM INFO  com.inversoft.search.ElasticRestClientHelper - Connecting to Elasticsearch at [http://10.197.56.168:9200]
2021-06-07 3:07:08.976 AM INFO  com.inversoft.search.ElasticRestClientHelper - Connecting to Elasticsearch at [http://10.197.56.170:9200]
Jun 07, 2021 3:07:09 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class [io.fusionauth.app.primeframework.FusionAuthAppPrimeServletContextListener]
java.lang.IllegalArgumentException: Unable to load the [/elasticsearch/initialize/entity-null.json] Elasticsearch configuration file.
        at com.inversoft.search.ElasticSearchClient.load(ElasticSearchClient.java:119)
        at com.inversoft.search.ElasticSearchClient.initializeIndex(ElasticSearchClient.java:235)
        at com.inversoft.maintenance.search.ElasticsearchMaintenanceModeSearchService.initializeIndex(ElasticsearchMaintenanceModeSearchService.java:103)
        at com.inversoft.maintenance.search.ElasticsearchSilentModeWorkflowTask.perform(ElasticsearchSilentModeWorkflowTask.java:42)
        at com.inversoft.maintenance.DefaultMaintenanceModeWorkflow.performSilentConfiguration(DefaultMaintenanceModeWorkflow.java:47)
        at com.inversoft.maintenance.servlet.MaintenanceModePrimeServletContextListener.contextInitialized(MaintenanceModePrimeServletContextListener.java:52)
        at io.fusionauth.app.primeframework.FusionAuthAppPrimeServletContextListener.contextInitialized(FusionAuthAppPrimeServletContextListener.java:26)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4705)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5171)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
        
Any idea what this might be?

postgres version: 10
elasticsearch version: 7.10.1
fusionauth versioin: 1.26.1

**Note: I can install version 1.25.0 and its starting perfectly fine.**

**Comment by robotdan** [comment]
I was thinking this was fixed in 1.26.1. @voidmain this is the ES version issue you fixed, did that go out in 1.26.1 or 1.27.0? 

@Thangamh have you tried 1.27.0 to see if that works?

**Comment by Thangamh** [comment]
Yes 1.27.2 works fine. I was wondering why 1.26.1 doesnt work when we turn silent config on, because I use 1.26.1 for production with same setting without having silent config on and I make the schemas run manually for our dbs.
