### ISSUE TITLE
Was able to get past the logout uri for OAuth on applications screen and cause a failure.

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1291]
### Description 
When adding a logout URI under `Applications > OAuth > Logout Text Box`

### Affects versions
List the version you are running, and any other versions you have attempted a recreated. 
1.28.1

### Steps to reproduce
1. Add logout URI a certain way
1. Hit save
1. FusionAuth Admin UI turns white and displays "unexpected error message"

### Screenshots
![image](https://user-images.githubusercontent.com/16090626/124034062-ff46ba80-d9b7-11eb-8bab-7001bfdabeb4.png)

### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]
 - Database [MySQL | PostgresSQL] & and version

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

From `sb debug`

```
30-Jun-2021 14:00:56.751 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 5453 ms
30-Jun-2021 15:26:51.498 SEVERE [ajp-nio-127.0.0.1-9019-exec-6] org.apache.coyote.ajp.AjpMessage.checkOverflow Overflow error for buffer adding [7980] bytes at position [259]
	java.lang.ArrayIndexOutOfBoundsException
		at org.apache.coyote.ajp.AjpMessage.checkOverflow(AjpMessage.java:258)
		at org.apache.coyote.ajp.AjpMessage.appendBytes(AjpMessage.java:225)
		at org.apache.coyote.ajp.AjpMessage.appendByteChunk(AjpMessage.java:209)
		at org.apache.coyote.ajp.AjpMessage.appendBytes(AjpMessage.java:191)
		at org.apache.coyote.ajp.AjpProcessor.prepareResponse(AjpProcessor.java:1121)
		at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:384)
		at org.apache.coyote.Response.action(Response.java:208)
		at org.apache.coyote.Response.sendHeaders(Response.java:418)
		at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:312)
		at org.apache.catalina.connector.OutputBuffer.close(OutputBuffer.java:272)
		at org.apache.catalina.connector.Response.finishResponse(Response.java:446)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:384)
		at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:526)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1629)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by jobannon** [comment]
Wanted to document, but closing as it was not reproducible.  I am not sure what caused it.
