### ISSUE TITLE
A FreeMarker exception occurred. See the FusionAuth Event Log for additional details. 

### ISSUE THREAD

**Issue by jn-githubber** [FusionAuth/fusionauth-issues#1334]
### Description

After upgrading from 1.19.8 to 1.28.1 we receive the error "A FreeMarker exception occurred. See the FusionAuth Event Log for additional details. " when opening the webpage. 

We looking at the logs we see that the upgrade completed successful but with an error? see screenshot
![Screenshot 2021-08-03 at 12 58 05](https://user-images.githubusercontent.com/72577341/128004975-d555408c-9db4-4394-990e-d7a17b1ab078.png)

Any recommendations?

**Comment by mooreds** [comment]
Thanks for filing this. Can you please share the event log? (It looks like you shared the system log.) You can find the event log by logging into the FusionAuth administrative user interface, then navigating to "System" and then "Event Log". 

Please share what is logged there (redacting anything sensitive, of course). Thanks!

**Comment by jn-githubber** [comment]
> Thanks for filing this. Can you please share the event log? (It looks like you shared the system log.) You can find the event log by logging into the FusionAuth administrative user interface, then navigating to "System" and then "Event Log".
> 
> Please share what is logged there (redacting anything sensitive, of course). Thanks!


Thank you for your reply.
Hereby the logs
------------------

A FreeMarker exception occurred.

Exception:
FreeMarker template error:
Macro "main" has no parameter with name "rowClass". Valid parameter names are: title, col

----
FTL stack trace ("~" means nesting-related):
	- Failed at: @helpers.main title="" rowClass="row ...  [in template "##d801c442-fb30-4571-ba8b-71314a7aa704##/WEB-INF/templates/index.ftl" at line 20, column 7]
	~ Reached through: #nested  [in template "##d801c442-fb30-4571-ba8b-71314a7aa704##/WEB-INF/templates/_helpers.ftl" in macro "body" at line 88, column 3]
	~ Reached through: @helpers.body  [in template "##d801c442-fb30-4571-ba8b-71314a7aa704##/WEB-INF/templates/index.ftl" at line 8, column 3]
	~ Reached through: #nested  [in template "##d801c442-fb30-4571-ba8b-71314a7aa704##/WEB-INF/templates/_helpers.ftl" in macro "html" at line 26, column 3]
	~ Reached through: @helpers.html  [in template "##d801c442-fb30-4571-ba8b-71314a7aa704##/WEB-INF/templates/index.ftl" at line 6, column 1]
----

Java stack trace (for programmers):
----
freemarker.core._MiscTemplateException: [... Exception message was already printed; see it above ...]
	at freemarker.core.Environment.newUndeclaredParamNameException(Environment.java:1142)
	at freemarker.core.Environment.setMacroContextLocalsFromArguments(Environment.java:1022)
	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:858)
	at freemarker.core.Environment.invokeMacro(Environment.java:812)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeNestedContent(Environment.java:620)
	at freemarker.core.BodyInstruction.accept(BodyInstruction.java:60)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:876)
	at freemarker.core.Environment.invokeMacro(Environment.java:812)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeNestedContent(Environment.java:620)
	at freemarker.core.BodyInstruction.accept(BodyInstruction.java:60)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:876)
	at freemarker.core.Environment.invokeMacro(Environment.java:812)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:334)
	at freemarker.core.Environment.visit(Environment.java:340)
	at freemarker.core.Environment.process(Environment.java:313)
	at freemarker.template.Template.process(Template.java:383)
	at org.primeframework.mvc.freemarker.DefaultFreeMarkerService.render(DefaultFreeMarkerService.java:76)
	at org.primeframework.mvc.action.result.AbstractForwardResult.execute(AbstractForwardResult.java:93)
	at org.primeframework.mvc.action.result.DefaultResultInvocationWorkflow.perform(DefaultResultInvocationWorkflow.java:97)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.scope.DefaultScopeStorageWorkflow.perform(DefaultScopeStorageWorkflow.java:62)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.perform(DefaultActionInvocationWorkflow.java:66)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:47)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.security.DefaultSecurityWorkflow.perform(DefaultSecurityWorkflow.java:60)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.parameter.DefaultPostParameterWorkflow.perform(DefaultPostParameterWorkflow.java:50)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.content.DefaultContentWorkflow.perform(DefaultContentWorkflow.java:52)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:57)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:102)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:58)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:44)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:126)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.workflow.StaticResourceWorkflow.perform(StaticResourceWorkflow.java:97)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.parameter.RequestBodyWorkflow.perform(RequestBodyWorkflow.java:91)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:64)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at io.fusionauth.app.primeframework.CORSFilter.doFilter(CORSFilter.java:262)
	at io.fusionauth.app.primeframework.CORSRequestWorkflow.perform(CORSRequestWorkflow.java:49)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at io.fusionauth.app.primeframework.FusionAuthMVCWorkflow.perform(FusionAuthMVCWorkflow.java:86)
	at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44)
	at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50)
	at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:78)
	at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:353)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1629)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by mooreds** [comment]
Have you updated your theme (either via API or the admin UI)? We added several new pages and the issue may be because you haven't added them into your theme. More details here: https://fusionauth.io/docs/v1/tech/themes/#upgrading

**Comment by jn-githubber** [comment]
Yes we have, after upgrading the version we performed an update of all necessary themes via the Admin UI. We imported the defaults where needed.

Also when looking at the Customization >  Themes  there are no upgrades required anymore.

**Comment by mooreds** [comment]
Thanks. It looks like you might have modified the `main` helper macro to customize the look and feel of your hosted login pages. If you did not, please let us know.

> Macro "main" has no parameter with name "rowClass". Valid parameter names are: title, col

FusionAuth doesn't overwrite theme files, just notifies the admin users of new ones. One of the new ones is the index page. The new template file may expect to call macros with a certain signature, but the old macro may not have all the parameters.

The easiest fix is to add the required parameters. If you need to know what the parameters are doing, it might make sense to install a fresh FusionAuth instance at version 1.28.1 and review the macros there.

**Comment by jn-githubber** [comment]
We will look into this and get back to you!

**Comment by media-square** [comment]
@mooreds we fixed the custom template by deleting the rowClass from the main helper.
You can close this issue, thnx for the support

**Comment by mooreds** [comment]
Excellent!
