### ISSUE TITLE
Support multiple hosts in PostgreSQL URIs

### ISSUE THREAD

**Issue by jcpreston26** [FusionAuth/fusionauth-issues#1436]
### Issue
This allows users to configure connection failover.

### Solution

Allow multiple hosts in the url. Or allow any valid JDBC url. See also https://github.com/FusionAuth/fusionauth-issues/issues/1339 which touches on this.

### Description 
The PostgreSQL JDBC driver permits a format where multiple hosts are included in the URI in order to initiate a connection fail-over.  This allows for multiple hosts being used with streaming replication.  By configuring targetServerType=primary in the URI connection string as well, the driver will only select the single host in the replication cluster designated as the primary and therefore able to perform writes.
(reference: the last section of [https://jdbc.postgresql.org/documentation/head/connect.html]())

Currently FusionAuth will either fail to start or end up with the maintenance mode warning message if this sort of connection string is specified.

### Affects versions
Testing has occurred on version 1.30.1.

### Steps to reproduce
1. Install Fusionauth-app
2. Configure the database.url property to fit this format, e.g. jdbc:postgresql://node1:5432,node2:5432,node3:5432/fusionauth?targetServerType=primary
3. System will not start properly.  The following errors will appear in the log entry:

> 2021-10-12 11:31:12.735 PM ERROR com.inversoft.maintenance.db.JDBCURL - Could not parse jdbcString [jdbc:postgresql://lab-postgres2.domain.local:5432,lab-postgres3.domain.local:5432/fusionauth?targetServerType=primary].
> java.lang.NumberFormatException: For input string: "5432,lab-postgres3.domain.local"
>        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
>        at java.base/java.lang.Integer.parseInt(Integer.java:652)
>   ... snip ...

### Expected behavior
The application should permit any valid URI configuration that is permitted by the underlying JDBC driver.  It should accept multiple hosts and the driver should handle the connection fail-over.

### Platform
(Please complete the following information)
 - OS: CentOS 7

### Additional context
If you remove the port numbers from the URI, the behavior changes, as the app gets stuck at startup with something like the following log entries:
> 2021-10-12 11:31:53.712 PM INFO  com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService - [yWZPng] Attempting to lock database to prevent multi-node issues
> 2021-10-12 11:31:53.724 PM INFO  com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService - [yWZPng] Obtained a database lock
> 2021-10-12 11:31:53.731 PM INFO  com.inversoft.maintenance.db.DatabaseSilentModeWorkflowTask - Attempt 1 of 100. Patiently waiting for database to become available [DOWN].
> 2021-10-12 11:32:03.736 PM INFO  com.inversoft.maintenance.db.DatabaseSilentModeWorkflowTask - Attempt 2 of 100. Patiently waiting for database to become available [DOWN].
> 2021-10-12 11:32:13.740 PM INFO  com.inversoft.maintenance.db.DatabaseSilentModeWorkflowTask - Attempt 3 of 100. Patiently waiting for database to become available [DOWN].

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/681
- https://github.com/FusionAuth/fusionauth-issues/issues/1036
- https://github.com/FusionAuth/fusionauth-issues/issues/1339
- https://github.com/FusionAuth/fusionauth-issues/issues/1762
- https://github.com/FusionAuth/fusionauth-issues/issues/1923
- https://github.com/FusionAuth/fusionauth-issues/issues/2121
- https://github.com/FusionAuth/fusionauth-issues/issues/2350

**Comment by bigg01** [comment]
This would be really great to see. :-)

**Comment by mooreds** [comment]
@bigg01 thanks for your feed back. We also check issues by number of upvotes, so please give the thumbs up to the issue (lower left corner). More on our roadmap process: https://fusionauth.io/docs/v1/tech/core-concepts/roadmap
