### ISSUE TITLE
API: Deleting tenants doesn't work

### ISSUE THREAD

**Issue by vkorn** [FusionAuth/fusionauth-issues#1487]
### Description 
After upgrading to 1.30.2, we're having issues with tenant deletion through the API (golang client, `DeleteTenantAsync`) : request goes through, but tenants are stuck in "Deleting" state. The only way to cleanup is to manually remove records from the DB. 

### Affects versions
1.30.2

### Steps to reproduce
1. Create a new tenant
2. Invoke delete tenant async operation
3. Open tenants list
4. See tenants stuck in "Deleting" state

### Expected behavior
Deleting tenant should go through

### Platform
(Please complete the following information)
 - Device: -
 - OS: Official docker
 - Browser + version: API
 - Database PostgresSQL

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
I don't see much errors in the logs, the only remotely related exception is this one (we do use custom theme, but we've added all new messages after the upgrade, plus I'm not sure if missing message can block the API call): 

```
2021-11-02 10:04:31.462 PM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
org.primeframework.mvc.message.l10n.MissingMessageException: Message could not be found for the URI [/admin/tenant/delete] and key [[pendingDelete]tenantId]
	at org.primeframework.mvc.message.l10n.ResourceBundleMessageProvider.getMessage(ResourceBundleMessageProvider.java:79)
	at io.fusionauth.app.service.FrontEndSupport.addFieldError(FrontEndSupport.java:182)
	at io.fusionauth.app.service.FrontEndSupport.lambda$transfer$1(FrontEndSupport.java:447)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at io.fusionauth.app.service.FrontEndSupport.lambda$transfer$2(FrontEndSupport.java:447)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
	at io.fusionauth.app.service.FrontEndSupport.transfer(FrontEndSupport.java:447)
	at io.fusionauth.app.service.FrontEndSupport.frontEndErrorHandling(FrontEndSupport.java:257)
	at io.fusionauth.client.LambdaDelegate.execute(LambdaDelegate.java:62)
	at io.fusionauth.app.action.admin.tenant.DeleteAction.post(DeleteAction.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.primeframework.mvc.util.ReflectionUtils.invoke(ReflectionUtils.java:414)
	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.execute(DefaultActionInvocationWorkflow.java:79)
	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.perform(DefaultActionInvocationWorkflow.java:62)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:47)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.security.DefaultSecurityWorkflow.perform(DefaultSecurityWorkflow.java:81)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.parameter.DefaultPostParameterWorkflow.perform(DefaultPostParameterWorkflow.java:50)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.content.DefaultContentWorkflow.perform(DefaultContentWorkflow.java:52)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:57)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:102)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:58)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:44)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:126)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.workflow.StaticResourceWorkflow.perform(StaticResourceWorkflow.java:97)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.parameter.RequestBodyWorkflow.perform(RequestBodyWorkflow.java:91)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:64)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at io.fusionauth.app.primeframework.CORSFilter.doFilter(CORSFilter.java:237)
	at io.fusionauth.app.primeframework.CORSRequestWorkflow.perform(CORSRequestWorkflow.java:49)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at io.fusionauth.app.primeframework.FusionAuthMVCWorkflow.perform(FusionAuthMVCWorkflow.java:86)
	at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44)
	at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50)
	at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:78)
	at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:196)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:364)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:624)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1650)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by vkorn** [comment]
Small update: tried deleting from the UI itself -- having the same problem, tenants aren't deleting, stuck with "Deleting..." label. Nothing in the logs.

**Comment by mooreds** [comment]
Can't replicate this, @vkorn but maybe I'm not doing something you are doing.

* stand up a new instance in docker. Don't use kickstart
* proceed through the setup, accepting the license
* create a new tenant
* delete tenant (succeeds)
* create a new tenant
* create a new application in that tenant
* delete the tenant (succeeds, but takes a while )

Can you provide more details about what triggers the tenant deletion to hang? Do you:

* have users in your tenant?
* have users log in to applications in a tenant?

Thanks!

**Comment by vkorn** [comment]
Hey @mooreds  thx for the reply. 

I have two instances of fusion running in cluster in k8s. Initially instances were provisioned long time ago, but were updated to 1.30.2 with all required db upgrade scripts executed. 

We're creating new tenants through the API with multiple apps in each tenant. 

Some of our test tenants didn't have any users some of them had, I've tried removing all users first -- didn't have any effect on tenants deletion. I've also tried removing applications from tenants -- didn't have any effect on tenants deletion. 

So basically my steps are: 

1. Create a tenant through the API
2. Create an app or two through the API
3. Try to remove tenant through the API or through the fusion UI

I've had to manually cleanup `connectors_tenants` and `tenants` just now as I've had 25 or so tenants stuck in PendingDelete state for days. 

There are a few differences from your setup: 

1. Instance was upgraded from older versions
2. Tenants are customized: theme, some JWT configuration, password requirements, etc. Please let me know if you need full list of settings we're using for tenant creation

**Comment by mooreds** [comment]
Thanks for the additional details @vkorn .

Do you remember what version the old version of FusionAuth was?

**Comment by vkorn** [comment]
Checked history. Just in case here's the full versions' list we've used: 

1. Initial setup was with `fusionauth/fusionauth-app:1.23.2`
2. Then it was updated to `fusionauth/fusionauth-app:1.28.0`, deletion was working on that version
3. A few weeks ago we've updated to the `fusionauth/fusionauth-app:1.30.2` -- that's where the problem had started. 

I can try rebooting instances and running tests again, if you think something might went wrong with the update. (After update I had to fix theme to account for a new changes and instances are running without the restart since then).

**Comment by mooreds** [comment]
Hi @vkorn .

Hmm. I did the following:

* stood up a docker container running 1.28.0 (https://fusionauth.io/docs/v1/tech/installation-guide/docker/ )
* added a tenant and two applications via the UI
* deleted the tenant (success)
* paused the fusionauth docker container (`docker-compose pause fusionauth`)
* ran the SQL update statements to upgrade from 1.28.0 to 1.30.2 via the psql command line
* updated the fusionauth docker container to run 1.30.2
* added a tenant and two applications via the UI
* deleted the tenant (success)

Can you please either try to replicate the issue using these steps or provide any additional customizations you are doing?

**Comment by robotdan** [comment]
We have had this issue in the past, but I thought we fixed it. There is a work around documented here: https://github.com/FusionAuth/fusionauth-issues/issues/1075#issuecomment-836873452 if it helps.

**Comment by vkorn** [comment]
Ok, I think I've figured out what was the problem @mooreds 

I've decided to restart nodes and it seem that scheduler wasn't running, after the restart I see bunch of messages 

```
2021-11-12 8:41:05.131 PM INFO  com.inversoft.scheduler.DefaultScheduler - Starting up scheduler
2021-11-12 8:41:05.136 PM INFO  com.inversoft.scheduler.DefaultScheduler - Scheduler is running
2021-11-12 8:41:05.776 PM INFO  io.fusionauth.api.service.system.NodeService - Node [6bb76ec5-a34a-486f-8e3e-2627ebb6a639] added with address [http://192.168.1.149:9011]
2021-11-12 8:41:08.873 PM INFO  io.fusionauth.api.service.system.AsyncTaskManager - [Delete Tenant] Tenant Id [e57016a7-735f-42af-8426-083cea1cb4bc].
2021-11-12 8:41:08.873 PM INFO  io.fusionauth.api.service.system.AsyncTaskManager - [Delete Tenant] Not found, task is complete.
```

Those are tenants which I had to manually remove before. Now I can delete tenants. 
Is there a way to tell whether scheduler is running or not? I don't see any scheduler exceptions for the past 3 weeks in the logs, so I didn't even know it was down.

**Comment by robotdan** [comment]
The scheduler always is running, on startup you'll see the message about starting up and running. 

```
2021-11-12 8:41:08.873 PM INFO  io.fusionauth.api.service.system.AsyncTaskManager - [Delete Tenant] Tenant Id [e57016a7-735f-42af-8426-083cea1cb4bc].
2021-11-12 8:41:08.873 PM INFO  io.fusionauth.api.service.system.AsyncTaskManager - [Delete Tenant] Not found, task is complete.
```

This messaging would indicate that the tenant did end up being deleted. Perhaps the job was stuck in a running state, otherwise it would have been cleaned up - not sure that happens exactly.

Do you see other older messages for `io.fusionauth.api.service.system.AsyncTaskManager` in the log indicating another node is processing the delete request?

**Comment by vkorn** [comment]
@robotdan nope, not a single log entry about the task manager for the past 3 weeks besides original startup. Only after nodes restart I can see that tasks being picked up.

**Comment by robotdan** [comment]
We added some enhancements to the async tenant delete feature in 1.33.0 that came out in February. 

https://github.com/FusionAuth/fusionauth-issues/issues/1559
https://fusionauth.io/docs/v1/tech/release-notes#version-1-33-0

I'm fairly certain this should be resolved through that issue, if you can still recreate the issue after upgrading to 133.0 or beyond please re-open and we'll take another look. Thanks!
