### ISSUE TITLE
Missing Column "enabled" in lambdas in version 1.35.0 when called via api

### ISSUE THREAD

**Issue by darkeagle1337** [FusionAuth/fusionauth-issues#1656]
### Description 
When calling a GET-request on `/api/lambda?type=JWTPopulate` the following error orrcur. In 1.35.0 database migration the following sql query was executed:
```
ALTER TABLE lambdas
  DROP COLUMN enabled,
  ADD COLUMN engine_type VARCHAR(255) NULL;
```

```
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'enabled' in 'where clause'        
### The error may exist in io/fusionauth/api/domain/LambdaMapper.java (best guess)                                       
### The error may involve io.fusionauth.api.domain.LambdaMapper.retrieveEnabledByType-Inline                             
### The error occurred while setting parameters                                                                          
### SQL: SELECT * FROM lambdas WHERE type = ? AND enabled = TRUE ORDER BY name                                           
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'enabled' in 'where clause'                                  
    at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)                             
    at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:153)                       
    at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:145)                       
    at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)                       
    at jdk.internal.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)                                             
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)          
    at java.base/java.lang.reflect.Method.invoke(Method.java:564)                                                        
    at org.apache.ibatis.session.SqlSessionManager$SqlSessionInterceptor.invoke(SqlSessionManager.java:357)              
    at com.sun.proxy.$Proxy53.selectList(Unknown Source)                                                                 
    at org.apache.ibatis.session.SqlSessionManager.selectList(SqlSessionManager.java:206)                                
    at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)                                      
    at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)                                              
    at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145)                             
    at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)                                                 
    at com.sun.proxy.$Proxy105.retrieveEnabledByType(Unknown Source)                                                     
    at io.fusionauth.api.service.system.DefaultLambdaService.retrieveEnabledByType(DefaultLambdaService.java:96)         
    at io.fusionauth.app.action.api.LambdaAction.get(LambdaAction.java:61)                                               
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                    
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                  
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)          
    at java.base/java.lang.reflect.Method.invoke(Method.java:564)                                                        
    at org.primeframework.mvc.util.ReflectionUtils.invoke(ReflectionUtils.java:414)                                      
    at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.execute(DefaultActionInvocationWorkflow.java:79)    
    at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.perform(DefaultActionInvocationWorkflow.java:62)    
    at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)                       
    at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:47)            
    at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)                       
    at org.primeframework.mvc.security.DefaultSecurityWorkflow.perform(DefaultSecurityWorkflow.java:81)                  
    at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)                       
    at org.primeframework.mvc.parameter.DefaultPostParameterWorkflow.perform(DefaultPostParameterWorkflow.java:50)       
    at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)                       
    at org.primeframework.mvc.content.DefaultContentWorkflow.perform(DefaultContentWorkflow.java:52)                     
    at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)                       
    at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:57)               
    at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)                       
    at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:102)        
    at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)                       
    at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:58)         
    at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)                       
    at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:44)                     
    at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)                       
    at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:126)         
    at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)                       
    at org.primeframework.mvc.workflow.StaticResourceWorkflow.perform(StaticResourceWorkflow.java:97)                    
    at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)                       
    at org.primeframework.mvc.parameter.RequestBodyWorkflow.perform(RequestBodyWorkflow.java:91)                         
    at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)                       
    at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:64)          
    at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)                       
    at io.fusionauth.app.primeframework.CORSRequestWorkflow.perform(CORSRequestWorkflow.java:51)                         
    at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)                       
    at io.fusionauth.app.primeframework.FusionAuthMVCWorkflow.perform(FusionAuthMVCWorkflow.java:86)                     
    at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44)               
    at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50)                  
    at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:78)                                          
    at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:63)         
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)                 
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)                         
    at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27)                                                     
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)                 
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)                         
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)                               
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)                                
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)                            
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)                                     
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)                                      
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)                                  
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:353)                                       
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)                                        
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)                                  
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)                           
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1629)                               
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)                                   
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)                         
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)                         
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)                                
    at java.base/java.lang.Thread.run(Thread.java:832)                                                                   
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'enabled' in 'where clause'                                  
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)                                       
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)                                        
    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)               
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)                       
    at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)                               
    at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)                             
    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)                    
    at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)             
    at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)               
    at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)                                         
    at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)                                  
    at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)                                              
    at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)                                        
    at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:89)                                         
    at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151)                       
    ... 75 common frames omitted                                                                                         
```

### Affects versions
1.35.0 

### Steps to reproduce
1. Call the api for lambda via postman or with something else
2. See error

### Expected behavior
No exception :D

**Comment by robotdan** [comment]
Can you confirm you are using the correct version of FusionAuth? This error would indicate you have upgraded your schema to 1.35.0 but you have a version of FusionAuth `< 1.35.0` accessing the database.

**Comment by darkeagle1337** [comment]
Unfortunately, I trusted my operator too much. He updated several servers, but only on this one he only updated the database schema, but not the runtime. It was 1.30.1 on the server, but the database had 1.35.0.

My mistake, I will close this issue.
