### ISSUE TITLE
Unable to delete key from key master when it is used by a deactivated application

### ISSUE THREAD

**Issue by voidmain** [FusionAuth/fusionauth-issues#1676]
### Description 

If you have an application that is deactivated, you can't deleted any of the keys associated with it. However, this causes a `500` error and spits out an exception to the logs like this:

```
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "keys" violates foreign key constraint "applications_fk_7" on table "applications"
  Detail: Key (id)=(9bfdeebb-a831-fa43-fc66-576ac1857cea) is still referenced from table "applications".
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:155)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
```

This foreign key looks like it isn't being checked properly when the application is in a disabled state.

### Affects versions
`1.34.1`

### Steps to reproduce
1. Create an Key
2. Create an Application and assign it that key under SAML
3. Deactivate the Application
4. Attempt to delete the Key from Key Master

**Comment by spwitt** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/120
- https://github.com/FusionAuth/fusionauth-api/pull/54
