### ISSUE TITLE
Freemarker error - reactorStatus not found

### ISSUE THREAD

**Issue by Kaisbn** [FusionAuth/fusionauth-issues#1695]
### Description 
A freemarker exception trace appears after updating to 1.36. Freemarker seems to be missing a `reactorStatus` variable and makes the dashboard unusable.

Tried a fresh install with a clean database, the same error comes up shortly after leaving maintenance mode.

When browsing in Incognito mode, the login doesn't show up (see screenshot below).

### Affects versions
1.36+

### Steps to reproduce
1. Setup FusionAuth
2. Login
3. Setup a new application
4. Error appears

### Expected behavior

Not getting this error.

### Screenshots

![FreeMarker Exception](https://user-images.githubusercontent.com/10171288/164418202-cf9b4a93-31ea-41e9-8733-232066428bd6.png)

![Main tab](https://user-images.githubusercontent.com/10171288/164418500-66353f10-cf35-4477-949e-bf1d5d04ae3f.png)

![Users tab](https://user-images.githubusercontent.com/10171288/164418355-8e1d81ae-8312-4cf3-8c9d-63f4f3abf034.png)

![Incognito mode](https://user-images.githubusercontent.com/10171288/164419550-a6819649-2dbd-4f4c-b1a2-7f15f225e6ff.png)

### Platform
 - Device: Desktop
 - OS: Linux
 - Chrome 98
 - Database PostgresSQL 12.8 on Amazon RDS
 - Running docker image with Amazon ECS

### Logs

```
2022-04-19 8:42:37.382 AM SEVERE freemarker.runtime - Error executing FreeMarker template
2022-04-19 8:42:37.548 AM ERROR org.primeframework.mvc.servlet.PrimeFilter - Error encountered
io.fusionauth.api.service.NotFoundException: null
	at io.fusionauth.app.service.FrontEndSupport.frontEndErrorHandling(FrontEndSupport.java:273)
	at io.fusionauth.client.LambdaDelegate.execute(LambdaDelegate.java:62)
	at io.fusionauth.app.action.BaseAction.basePostParameterMethod(BaseAction.java:168)
	at jdk.internal.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.primeframework.mvc.util.ReflectionUtils.invokeAll(ReflectionUtils.java:441)
	at org.primeframework.mvc.parameter.DefaultPostParameterHandler.handle(DefaultPostParameterHandler.java:32)
	at org.primeframework.mvc.control.form.Form.prepareActionInvocation(Form.java:204)
	at org.primeframework.mvc.control.form.Form.renderStart(Form.java:144)
	at org.primeframework.mvc.control.FreeMarkerControlProxy.execute(FreeMarkerControlProxy.java:61)
	at freemarker.core.Environment.visit(Environment.java:451)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:102)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeNestedContent(Environment.java:620)
	at freemarker.core.BodyInstruction.accept(BodyInstruction.java:60)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:876)
	at freemarker.core.Environment.invokeMacro(Environment.java:812)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeNestedContent(Environment.java:620)
	at freemarker.core.BodyInstruction.accept(BodyInstruction.java:60)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:876)
	at freemarker.core.Environment.invokeMacro(Environment.java:812)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:334)
	at freemarker.core.Environment.visit(Environment.java:340)
	at freemarker.core.Environment.process(Environment.java:313)
	at freemarker.template.Template.process(Template.java:383)
	at org.primeframework.mvc.freemarker.DefaultFreeMarkerService.render(DefaultFreeMarkerService.java:76)
	at org.primeframework.mvc.action.result.AbstractForwardResult.execute(AbstractForwardResult.java:93)
	at org.primeframework.mvc.action.result.DefaultResultInvocationWorkflow.perform(DefaultResultInvocationWorkflow.java:108)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:44)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.scope.DefaultScopeStorageWorkflow.perform(DefaultScopeStorageWorkflow.java:62)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.workflow.DefaultErrorWorkflow.perform(DefaultErrorWorkflow.java:46)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at io.fusionauth.app.primeframework.FusionAuthMVCWorkflow.perform(FusionAuthMVCWorkflow.java:91)
	at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44)
	at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50)
	at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:78)
	at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:367)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:639)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:881)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1647)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by mooreds** [comment]
Hmmm. I'm unable to replicate this issue. I tried in docker, both with and without a kickstart file, with 1.36.4.

Can you provide a few more details:

* do you have a license or are you on the community edition?
* does the ECS cluster have outbound connectivity? (Not a requirement for FusionAuth in general, just trying to narrow things down so we can reproduce the issue.)
* what version did you see this issue with (1.36.4?)
* for the fresh install, did you do that locally or on the ECS cluster?

**Comment by Kaisbn** [comment]
- Community edition
- Yes, I opened the security group for both inbound and outbound traffic
- I tried 1.36.1 to 1.36.3
- On the ECS cluster with a new database. The service is fully deployed via Terraform. I destroyed everything before redeploying.

**Comment by Kaisbn** [comment]
I have done a new fresh install with version 1.35.0 this time. 

Everything works for the moment. I'm not getting the error anymore. I still don't know if it comes from my configuration or from v1.36. I didn't change anything except the image tag.

**Comment by mooreds** [comment]
Hmmm. thanks for the info. Nothing obvious jumps out as being problematic. Let me think about this a bit more and see if I can replicate.

**Comment by robotdan** [comment]
If this can still be recreated, please re-open.
