### ISSUE TITLE
Freemarker Error on the account add 2FA screen

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1718]
### Description 
Freemarker Error 

### Affects versions
Dev Setup

### Steps to reproduce
Add a 2Fa method using the hosted account pages.

### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]
 - Database [MySQL | PostgresSQL] & and version

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

````
----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${secretBase32Encoded}  [in template "##75a068fd-e94b-451a-9aeb-3ddb9a3b5987##/WEB-INF/templates/account/two-factor/enable.ftl" at line 70, column 33]
	~ Reached through: #nested  [in template "##75a068fd-e94b-451a-9aeb-3ddb9a3b5987##/WEB-INF/templates/_helpers.ftl" in macro "head" at line 123, column 3]
	~ Reached through: @helpers.head title=theme.message("au...  [in template "##75a068fd-e94b-451a-9aeb-3ddb9a3b5987##/WEB-INF/templates/account/two-factor/enable.ftl" at line 60, column 3]
	~ Reached through: #nested  [in template "##75a068fd-e94b-451a-9aeb-3ddb9a3b5987##/WEB-INF/templates/_helpers.ftl" in macro "html" at line 31, column 3]
	~ Reached through: @helpers.html  [in template "##75a068fd-e94b-451a-9aeb-3ddb9a3b5987##/WEB-INF/templates/account/two-factor/enable.ftl" at line 59, column 1]
----
	at org.primeframework.mvc.freemarker.DefaultFreeMarkerService.render(DefaultFreeMarkerService.java:84)
	at org.primeframework.mvc.action.result.AbstractForwardResult.execute(AbstractForwardResult.java:93)
	at org.primeframework.mvc.action.result.DefaultResultInvocationWorkflow.perform(DefaultResultInvocationWorkflow.java:108)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:44)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.scope.DefaultScopeStorageWorkflow.perform(DefaultScopeStorageWorkflow.java:62)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.workflow.DefaultErrorWorkflow.perform(DefaultErrorWorkflow.java:46)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at io.fusionauth.app.primeframework.FusionAuthMVCWorkflow.perform(FusionAuthMVCWorkflow.java:91)
	at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44)
	at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50)
	at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:78)
	at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:367)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:526)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:881)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1647)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> secretBase32Encoded  [in template "##75a068fd-e94b-451a-9aeb-3ddb9a3b5987##/WEB-INF/templates/account/two-factor/enable.ftl" at line 70, column 35]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${secretBase32Encoded}  [in template "##75a068fd-e94b-451a-9aeb-3ddb9a3b5987##/WEB-INF/templates/account/two-factor/enable.ftl" at line 70, column 33]
	~ Reached through: #nested  [in template "##75a068fd-e94b-451a-9aeb-3ddb9a3b5987##/WEB-INF/templates/_helpers.ftl" in macro "head" at line 123, column 3]
	~ Reached through: @helpers.head title=theme.message("au...  [in template "##75a068fd-e94b-451a-9aeb-3ddb9a3b5987##/WEB-INF/templates/account/two-factor/enable.ftl" at line 60, column 3]
	~ Reached through: #nested  [in template "##75a068fd-e94b-451a-9aeb-3ddb9a3b5987##/WEB-INF/templates/_helpers.ftl" in macro "html" at line 31, column 3]
	~ Reached through: @helpers.html  [in template "##75a068fd-e94b-451a-9aeb-3ddb9a3b5987##/WEB-INF/templates/account/two-factor/enable.ftl" at line 59, column 1]
----
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
	at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:481)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370)
	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeNestedContent(Environment.java:620)
	at freemarker.core.BodyInstruction.accept(BodyInstruction.java:60)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:876)
	at freemarker.core.Environment.invokeMacro(Environment.java:812)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeNestedContent(Environment.java:620)
	at freemarker.core.BodyInstruction.accept(BodyInstruction.java:60)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:876)
	at freemarker.core.Environment.invokeMacro(Environment.java:812)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:334)
	at freemarker.core.Environment.visit(Environment.java:340)
	at freemarker.core.Environment.process(Environment.java:313)
	at freemarker.template.Template.process(Template.java:383)
	at org.primeframework.mvc.freemarker.DefaultFreeMarkerService.render(DefaultFreeMarkerService.java:76)
	... 35 common frames omitted
	```

**Comment by robotdan** [comment]
Can you add some additional details such as version, license state, recreate steps, is this on dev, master, or demo, etc?
