### ISSUE TITLE
duplicate key possible when using the Grant API

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1813]
### Description 
Looks like we are missing some validation.

```
### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "entity_user_grant_permissions_uk_1"
  Detail: Key (entity_user_grants_id, entity_type_permissions_id)=(<redacted>, <redacted>) already exists.
### The error may exist in io/fusionauth/api/domain/EntityMapper.java (best guess)
### The error may involve io.fusionauth.api.domain.EntityMapper.createUserGrantPermissions-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO entity_user_grant_permissions (entity_user_grants_id, entity_type_permissions_id) VALUES    (?, ?)
### Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "entity_user_grant_permissions_uk_1"
  Detail: Key (entity_user_grants_id, entity_type_permissions_id)=(<redacted>, <redacted>) already exists.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:196)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181)
	at jdk.internal.reflect.GeneratedMethodAccessor114.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.ibatis.session.SqlSessionManager$SqlSessionInterceptor.invoke(SqlSessionManager.java:350)
	at jdk.proxy3/jdk.proxy3.$Proxy52.insert(Unknown Source)
	at org.apache.ibatis.session.SqlSessionManager.insert(SqlSessionManager.java:236)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	at jdk.proxy3/jdk.proxy3.$Proxy124.createUserGrantPermissions(Unknown Source)
	at io.fusionauth.api.service.entity.DefaultEntityService.upsertGrant(DefaultEntityService.java:338)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:100)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:100)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:100)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:100)
	at io.fusionauth.app.action.api.entity.GrantAction.put(GrantAction.java:110)
	at io.fusionauth.app.action.api.entity.GrantAction.post(GrantAction.java:106)
```

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mmanes** [comment]
Unable to reproduce in 1.42.0. Validators are properly de-duping permissions in request.
