### ISSUE TITLE
Docker image latest fusionauth-app:1.39.0 throws  MySQLHelper Exception

### ISSUE THREAD

**Issue by JogiPrasadPakki** [FusionAuth/fusionauth-issues#1879]
### Description 
I recently migrated fusionauth docker image from 1.36.0 to latest 1.39.0. And i follow this instructions https://fusionauth.io/community/forum/topic/2144/fusionauth-1-37-is-released/12 to add mysql connector MYSQL_CONNECTOR_VERSION=8.0.21 to docker file.
It is working fine in production environment. For upgrade database i changed runtime mode to development  but docker image not started and through this exception **Exception in thread "main" java.lang.NoClassDefFoundError: com/inversoft/mysql/MySQLHelper**
The full log is
```
2022-09-15 08:28:05.611 AM INFO  com.inversoft.maintenance.MaintenanceModePoller - Poller started to Wait for configuration to be completed.
fusionauth_1  | 2022-09-15 08:28:05.613 AM INFO  io.fusionauth.app.primeframework.FusionHTTPContextAuthSetup - Initializing the FusionAuth HTTP Context.
fusionauth_1  | Exception in thread "main" java.lang.NoClassDefFoundError: com/inversoft/mysql/MySQLHelper
fusionauth_1  | 	at com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService.loadDriver(JDBCMaintenanceModeDatabaseService.java:430)
fusionauth_1  | 	at com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService.determineDatabaseStatus(JDBCMaintenanceModeDatabaseService.java:162)
fusionauth_1  | 	at com.inversoft.maintenance.db.DatabaseInteractiveWorkflowTask.perform(DatabaseInteractiveWorkflowTask.java:27)
fusionauth_1  | 	at com.inversoft.maintenance.DefaultMaintenanceModeWorkflow.getCurrentStage(DefaultMaintenanceModeWorkflow.java:63)
fusionauth_1  | 	at com.inversoft.maintenance.BaseMaintenanceModePrimeMain.modules(BaseMaintenanceModePrimeMain.java:71)
fusionauth_1  | 	at org.primeframework.mvc.BasePrimeMain.hup(BasePrimeMain.java:65)
fusionauth_1  | 	at org.primeframework.mvc.BasePrimeMain.start(BasePrimeMain.java:93)
fusionauth_1  | 	at io.fusionauth.app.FusionAuthMain.main(FusionAuthMain.java:23)
fusionauth_1  | Caused by: java.lang.ClassNotFoundException: com.inversoft.mysql.MySQLHelper
fusionauth_1  | 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
fusionauth_1  | 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
fusionauth_1  | 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
fusionauth_1  | 	... 8 more
fusionauth_1  | Exception in thread "Thread-0" java.lang.NullPointerException: Cannot invoke "org.primeframework.mvc.netty.PrimeHTTPServer.shutdown()" because "this.server" is null
fusionauth_1  | 	at org.primeframework.mvc.BasePrimeMain.shutdown(BasePrimeMain.java:84)
fusionauth_1  | 	at org.primeframework.mvc.BasePrimeMain$PrimeHTTPServerShutdown.run(BasePrimeMain.java:106)
```

### Affects versions
1.39.0

### Platform
docker image with docker-compose

**Comment by mooreds** [comment]
Hiya,

Unfortunately we can't bundle the mysql JDBC driver with the FusionAuth docker install, because of legal concerns.

You have to build your own docker image. Here's an example build file: https://github.com/FusionAuth/fusionauth-containers/blob/master/docker/fusionauth/fusionauth-app-mysql/Dockerfile

Can you please try that and let us know if it solves your problem?
