### ISSUE TITLE
Users list

### ISSUE THREAD

**Issue by forenheith** [FusionAuth/fusionauth-issues#194]
Hi all, each time when I create a user, user info page opens, but if I exit it and return to the list of users by pressing at the link Users on the left side of the page, the users list will be empty. And I see the following dialog

![chrome_I6eCDbkfRc](https://user-images.githubusercontent.com/7276744/60033423-38edd800-96b1-11e9-847b-2c1e642cd9f2.png)

When I checking the database tables, created users still in place. What am I missing?

**Comment by tyduptyler13** [comment]
Hi, could you copy your FusionAuth log and post it here?

It is located at the root of the FusionAuth directory under `logs`.

**Comment by forenheith** [comment]
Hi, I only have this file at logs directory
![TOTALCMD_wakPhbQVEQ](https://user-images.githubusercontent.com/7276744/60037720-ffba6580-96ba-11e9-877c-67a707543d47.png)

**Comment by robotdan** [comment]
@forenheith do you have any errors on the stdout of the console where you started FusionAuth? 

It sounds like Elasticsearch is not running, or has an error. Can you confirm that the search service is also running? If so, navigate to `System --> Reindex` and request a reindex of the search engine.

**Comment by forenheith** [comment]
> @forenheith do you have any errors on the stdout of the console where you started FusionAuth?
> 
> It sounds like Elasticsearch is not running, or has an error. Can you confirm that the search service is also running? If so, navigate to `System --> Reindex` and request a reindex of the search engine.

You are compeltely right. ElasticSearch service was stopped. I don`t know what wrong with it
Here is screenshot from my Event Viewer

![mmc_2cSyghnL7A](https://user-images.githubusercontent.com/7276744/60093356-ddbff200-9751-11e9-8e13-5253454cac17.png)

**Comment by forenheith** [comment]
I uninstalled preinstalled ElasticSearch from my pc, after that I reinstalled FusionAuth from the zip archive and ElasicSearch service as well and currently fusionauth app can`t start at all and crushes  with several errors while starting.

**Comment by forenheith** [comment]
I uninstalled ElasticSearch from my pc that was preinstalled, after that I extracted FusionAuth from the zip archive and ElasicSearch service as well and currently elasticsearch still doesnt work. Is there any user friendly way to deploy an application without magic and possible errors during the installation steps? I have to present FusionAuth at our company but I cant do this about two weeks.

**Comment by forenheith** [comment]
`25-Jun-2019 15:04:14.278 SEVERE [main] org.apache.tomcat.util.net.SSLUtilBase.getStore Failed to load keystore type [JKS] with path [C:\fusionauth\fusionauth-app\apache-tomcat\..\..\config/keystore] due to [Illegal character in opaque part at index 2: C:\fusionauth\fusionauth-app\apache-tomcat\..\..\config/keystore]
 java.lang.IllegalArgumentException: Illegal character in opaque part at index 2: C:\fusionauth\fusionauth-app\apache-tomcat\..\..\config/keystore
	at java.net.URI.create(URI.java:852)
	at java.net.URI.resolve(URI.java:1036)
	at org.apache.tomcat.util.file.ConfigFileLoader.getInputStream(ConfigFileLoader.java:88)
	at org.apache.tomcat.util.net.SSLUtilBase.getStore(SSLUtilBase.java:132)
	at org.apache.tomcat.util.net.SSLHostConfigCertificate.getCertificateKeystore(SSLHostConfigCertificate.java:204)
	at org.apache.tomcat.util.net.jsse.JSSEUtil.getKeyManagers(JSSEUtil.java:184)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:114)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:87)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:225)
	at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1086)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.init(AbstractJsseEndpoint.java:268)
	at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:581)
	at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:68)
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:993)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.core.StandardService.initInternal(StandardService.java:549)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:875)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:632)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:655)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:309)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)`

**Comment by robotdan** [comment]
> IndexFormatTooNewException: Format version is not supported 

This sounds like you're running an incompatible version of Elasticsearch. We ship with version 6.3.1, but you can install your own if it is an equivalent version. 
https://fusionauth.io/docs/v1/tech/installation-guide/system-requirements

The simplest way to get running on Windows is to use the FastPath. https://fusionauth.io/docs/v1/tech/installation-guide/fast-path This will download both zip packages (FusionAuth and Elasticsearch) to the current directory and unzip them correctly. 

```
iex (new-object net.webclient).downloadstring('https://raw.githubusercontent.com/FusionAuth/fusionauth-install/master/install.ps1')
```

**Comment by forenheith** [comment]
![cmd_wjMKo6ZpJg](https://user-images.githubusercontent.com/7276744/60109012-461ecb80-9772-11e9-9b79-96049f80f542.png)

**Comment by forenheith** [comment]
Thanks it helped. Now list is working fine

**Comment by robotdan** [comment]
Looks like you resolved your `iex` issue, as long as you meet the Windows min. requirements you should be ok. 

https://fusionauth.io/docs/v1/tech/installation-guide/system-requirements

**Comment by robotdan** [comment]
I'll close out this issue unless there are any remaining issues with getting the search service up and running.
