### ISSUE TITLE
Setup Password Results in a FreeMarker Error on MFA enabled User

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1965]
### Problem
When completing a forgot password workflow, if you have an MFA enabled, the workflow will work (if we have some state, see below when we don't), but we cannot seem to reconstitute `state` correction (or something else is causing the domain object of `application` to be `null`).

#### Env
- Tested on a clean build of docker / FusionAuth-App /  `1.41.0` 

### Additional context

Updated to the latest `fogot-password` template:

```
Your account has been created and you must setup a password. Click on the following link to setup your password.
<p>
  <a href="https://local.fusionauth.io/password/change/${changePasswordId}?tenantId=${user.tenantId}">
    https://local.fusionauth.io/password/change/${changePasswordId}?tenantId=${user.tenantId}
  </a>
</p>
- FusionAuth Admin
```

#### Request resulting in a FreeMarker error (but can still continue)

```
curl --request POST \
  --url https://local.fusionauth.io/api/user/forgot-password \
  --header 'Content-Type: application/json' \
  --header 'X-FusionAuth-TenantId: bf63679c-e31f-5e49-bc2f-c4bd6e40b22d' \
  --data '{
	"loginId": "joshua@fusionauth.io",
	"applicationId": "cd1c234f-7324-4f1a-b40c-4c4d78294aae",
	"state": {
		"clientId": "cd1c234f-7324-4f1a-b40c-4c4d78294aae",
		"redirect_uri": "http://www.google.com",
		"response_type": "code"
	}
}'
```

##### Screenshot

```
A FreeMarker exception occurred. See the FusionAuth Event Log for additional details.

Blamed expression: application
Line number: 44
Column number: 20
End column number: 30
Theme Id: 75a068fd-e94b-451a-9aeb-3ddb9a3b5987
Template name: /oauth2/two-factor.ftl

Message:
The following has evaluated to null or missing:
==> application  [in template "##75a068fd-e94b-451a-9aeb-3ddb9a3b5987##templates/oauth2/two-factor.ftl" at line 44, column 20]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #if application.externalIdentifierCon...  [in template "##75a068fd-e94b-451a-9aeb-3ddb9a3b5987##templates/oauth2/two-factor.ftl" at line 44, column 15]
	~ Reached through: #nested  [in template "##75a068fd-e94b-451a-9aeb-3ddb9a3b5987##templates/_helpers.ftl" in macro "main" at line 193, column 11]
	~ Reached through: @helpers.main title=theme.message("tw...  [in template "##75a068fd-e94b-451a-9aeb-3ddb9a3b5987##templates/oauth2/two-factor.ftl" at line 30, column 5]
	~ Reached through: #nested  [in template "##75a068fd-e94b-451a-9aeb-3ddb9a3b5987##templates/_helpers.ftl" in macro "body" at line 132, column 3]
	~ Reached through: @helpers.body  [in template "##75a068fd-e94b-451a-9aeb-3ddb9a3b5987##templates/oauth2/two-factor.ftl" at line 24, column 3]
	~ Reached through: #nested  [in template "##75a068fd-e94b-451a-9aeb-3ddb9a3b5987##templates/_helpers.ftl" in macro "html" at line 31, column 3]
	~ Reached through: @helpers.html  [in template "##75a068fd-e94b-451a-9aeb-3ddb9a3b5987##templates/oauth2/two-factor.ftl" at line 14, column 1]
```

### When trying the below request `500` error is returned

This request 
```
curl --request POST \
  --url https://local.fusionauth.io/api/user/forgot-password \
  --header 'Content-Type: application/json' \
  --header 'X-FusionAuth-TenantId: bf63679c-e31f-5e49-bc2f-c4bd6e40b22d' \
  --data '{
	"loginId": "joshua@fusionauth.io",
	"applicationId": "cd1c234f-7324-4f1a-b40c-4c4d78294aae"
}'
```

Get a 500 error.

```2022-11-15 04:10:25.918 AM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "<parameter1>" is null
        at io.fusionauth.app.action.oauth2.BaseOAuthAction.safeGet(BaseOAuthAction.java:822)
        at io.fusionauth.app.action.oauth2.BaseOAuthAction.unpackSavedState(BaseOAuthAction.java:860)
        at io.fusionauth.app.action.password.ChangeAction.validateGet(ChangeAction.java:197)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.primeframework.mvc.util.ReflectionUtils.invoke(ReflectionUtils.java:414)
        at org.primeframework.mvc.validation.DefaultValidationProcessor.validate(DefaultValidationProcessor.java:77)
        at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:44)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.security.DefaultSecurityWorkflow.perform(DefaultSecurityWorkflow.java:58)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.parameter.DefaultPostParameterWorkflow.perform(DefaultPostParameterWorkflow.java:49)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.content.DefaultContentWorkflow.perform(DefaultContentWorkflow.java:72)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:58)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:92)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:50)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:113)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:65)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.cors.CORSRequestWorkflow.perform(CORSRequestWorkflow.java:65)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.workflow.DefaultMVCWorkflow.perform(DefaultMVCWorkflow.java:108)
        at org.primeframework.mvc.PrimeMVCRequestHandler.handle(PrimeMVCRequestHandler.java:71)
        at io.fusionauth.http.server.HTTPWorker.run(HTTPWorker.java:50)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

<img width="999" alt="image" src="https://user-images.githubusercontent.com/16090626/201823950-62c7f57f-9e54-4079-b5fb-fd57de8bcb16.png">

### Related Context -
- https://inversoft.slack.com/archives/C039RUBAAE6/p1667521433497809

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by jobannon** [comment]
Attempted with  `client_id` when building the URL.
```
Your account has been created and you must setup a password. Click on the following link to setup your password.
<p>
  <a href="http://localhost:9011/password/change/${changePasswordId}?client_id=${(application.oauthConfiguration.clientId)!''}&tenantId=${user.tenantId}">
    http://localhost:9011/password/change/${changePasswordId}?client_id=${(application.oauthConfiguration.clientId)!''}&tenantId=${user.tenantId}
  </a>
</p>
- FusionAuth Admin
```

```
curl --request POST \
  --url https://local.fusionauth.io/api/user/forgot-password \
  --header 'Authorization: w4WgFdyKQVo34e0XrIisnrUOqYY529oy1Oeb1z8g6bTqXOo7pkUTvHt8' \
  --header 'Content-Type: application/json' \
  --data '{
	"loginId": "joshua@fusionauth.io"

}'
```

And received 500 error.

```
2022-11-15 05:00:40.398 PM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "<parameter1>" is null
        at io.fusionauth.app.action.oauth2.BaseOAuthAction.safeGet(BaseOAuthAction.java:822)
        at io.fusionauth.app.action.oauth2.BaseOAuthAction.unpackSavedState(BaseOAuthAction.java:860)
        at io.fusionauth.app.action.password.ChangeAction.validateGet(ChangeAction.java:197)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.primeframework.mvc.util.ReflectionUtils.invoke(ReflectionUtils.java:414)
        at org.primeframework.mvc.validation.DefaultValidationProcessor.validate(DefaultValidationProcessor.java:77)
        at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:44)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.security.DefaultSecurityWorkflow.perform(DefaultSecurityWorkflow.java:58)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.parameter.DefaultPostParameterWorkflow.perform(DefaultPostParameterWorkflow.java:49)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.content.DefaultContentWorkflow.perform(DefaultContentWorkflow.java:72)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:58)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:92)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:50)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:113)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:65)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.cors.CORSFilter.doFilter(CORSFilter.java:171)
        at org.primeframework.mvc.cors.CORSRequestWorkflow.perform(CORSRequestWorkflow.java:63)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.workflow.DefaultMVCWorkflow.perform(DefaultMVCWorkflow.java:108)
        at org.primeframework.mvc.PrimeMVCRequestHandler.handle(PrimeMVCRequestHandler.java:71)
        at io.fusionauth.http.server.HTTPWorker.run(HTTPWorker.java:50)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by jobannon** [comment]
Update: Bug is also present when adding the applicationId.


```
curl --request POST \
  --url https://local.fusionauth.io/api/user/forgot-password \
  --header 'Authorization: w4WgFdyKQVo34e0XrIisnrUOqYY529oy1Oeb1z8g6bTqXOo7pkUTvHt8' \
  --header 'Content-Type: application/json' \
  --data '{
	"loginId": "joshua@fusionauth.io",
	"applicationId": "cd1c234f-7324-4f1a-b40c-4c4d78294aae"
}'
```

Same 500 error is presented as directly above ☝🏻
