### ISSUE TITLE
Serbian Locale causing an exception when the User is actioned

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1978]
### Description 

Manually selecting values `Serbian` ,`Serbian (Montenegro)`, and `Serbian (Serbia)` from the drop down resulted in the error logs below:

```
java.lang.IllegalArgumentException: Unsupported locale [sr]
java.lang.IllegalArgumentException: Unsupported locale [sr_CS]
java.lang.IllegalArgumentException: Unsupported locale [sr_RS]
```

Need to test the Import API, the User API, the locale selector in the admin UI and attempt to action a user with this locale. 

```
2022-11-21 11:30:58.545 PM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
java.lang.IllegalArgumentException: Unsupported locale [sr_RS]
	at com.inversoft.time.DurationFormatter.format(DurationFormatter.java:107)
	at io.fusionauth.api.l10n.Localizer.localize(Localizer.java:32)
	at io.fusionauth.api.service.useraction.DefaultActionService.actionUser(DefaultActionService.java:141)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:100)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:100)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:100)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:100)
	at io.fusionauth.app.action.api.user.ActionAction.post(ActionAction.java:89)
```

The issue looks to be in our `com.inversoft.time.DurationFormatter` utility which is not accounting for this locale.  We should probably just fall back to english if we don't have a localized version instead of throwing an exception. 

### Affects versions
TBD

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/161
