### ISSUE TITLE
Unhealthy Hikari Pool Connection in Cloud Run with Cloud SQL Postgres

### ISSUE THREAD

**Issue by TanguyGiton** [FusionAuth/fusionauth-issues#1980]
### Description

Hello,

I tried to deploy the Fusionauth container on GCP Cloud Run connected to a Cloud SQL Postgres managed database. And the search engine is Elastic Search.
It works globally correctly.

However, the status path `/api/status` return a 423 error "Unhealthy Hikari Pool Connection". Here is the full answer: [status.json](https://github.com/FusionAuth/fusionauth-issues/files/10070625/status.json.txt)

I also have errors in the container logs:

```
2022-11-22 07:37:51.956 PM WARN com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Failed to validate connection org.postgresql.jdbc.PgConnection@52fde4dc (This connection has been closed.). Possibly consider using a shorter maxLifetime value.
Container Sandbox: Unsupported syscall UNKNOWN[435/0x1b3](0x3e1e73efdc30,0x58,0x3e1ed2494850,0x8,0x3e1e6afff640,0x3e1e73efdd4f). It is very likely that you can safely ignore this message and that this is not the cause of any error you might be troubleshooting. Please, refer to https://gvisor.dev/docs/user_guide/compatibility/linux/amd64/#UNKNOWN[435/0x1b3] for more information.
Container Sandbox: Unsupported syscall UNKNOWN[435/0x1b3](0x3e1e6affe160,0x58,0x3e1ed2494850,0x8,0x3e1e6b1ff640,0x3e1e6affe27f). It is very likely that you can safely ignore this message and that this is not the cause of any error you might be troubleshooting. Please, refer to https://gvisor.dev/docs/user_guide/compatibility/linux/amd64/#UNKNOWN[435/0x1b3] for more information.
2022-11-22 07:37:52.156 PM ERROR com.inversoft.license.v2.DefaultLicenseProvider$LocalReloader - Error reloading local license. Disabling license. See stack trace for error
org.apache.ibatis.exceptions.PersistenceException:
### Error querying database. Cause: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 3099ms.
### The error may exist in io/fusionauth/api/domain/InstanceMapper.java (best guess)
### The error may involve io.fusionauth.api.domain.InstanceMapper.retrieve
### The error occurred while executing a query
### Cause: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 3099ms.
 at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
 at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:153)
 at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:145)
 at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
 at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
 at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 at org.apache.ibatis.session.SqlSessionManager$SqlSessionInterceptor.invoke(SqlSessionManager.java:357)
 at jdk.proxy2/jdk.proxy2.$Proxy52.selectOne(Unknown Source)
 at org.apache.ibatis.session.SqlSessionManager.selectOne(SqlSessionManager.java:166)
 at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87)
 at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145)
 at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
 at jdk.proxy2/jdk.proxy2.$Proxy59.retrieve(Unknown Source)
 at io.fusionauth.api.license.FusionAuthLicenseMetaDataManager.localLookup(FusionAuthLicenseMetaDataManager.java:50)
 at com.inversoft.license.v2.BaseConfigurationLicenseMetaDataManager.lookup(BaseConfigurationLicenseMetaDataManager.java:30)
 at com.inversoft.license.v2.local.DefaultLocalLicenseSystem.load(DefaultLocalLicenseSystem.java:35)
 at com.inversoft.license.v2.DefaultLicenseProvider$LocalReloader.run(DefaultLicenseProvider.java:131)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
 at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
 at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 3099ms.
 at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
 at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181)
 at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
 at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
 at org.apache.ibatis.transaction.jdbc.JdbcTransaction.openConnection(JdbcTransaction.java:139)
 at org.apache.ibatis.transaction.jdbc.JdbcTransaction.getConnection(JdbcTransaction.java:61)
 at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:337)
 at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:86)
 at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
 at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
 at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
 at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
 at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:89)
 at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151)
 ... 23 common frames omitted
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
 at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:907)
 at org.postgresql.jdbc.PgConnection.setNetworkTimeout(PgConnection.java:1649)
 at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:561)
 at com.zaxxer.hikari.pool.PoolBase.isConnectionDead(PoolBase.java:168)
 at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:170)
 ... 35 common frames omitted
```

I've updated the env variable `DATABASE_MAX_LIFETIME` to `180000`

I know Cloud Run is not officially supported, but I find it interesting to be able to deploy FusionAuth on a PaaS service.

I'm writing to you to better understand this error and get your recommendations.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by TanguyGiton** [comment]
I suspect the following request to be responsible for the slowdowns (I only have the beginning of the request):

```sql
SELECT
  a.id AS a_id,
  a.access_token_populate_lambdas_id AS a_access_token_populate_lambdas_id,
  a.access_token_signing_keys_id AS a_access_token_signing_keys_id,
  a.active AS a_active,
  a.data AS a_data,
  a.email_update_email_templates_id AS a_email_update_email_templates_id,
  a.email_verification_email_templates_id AS a_email_verification_email_templates_id,
  a.email_verified_email_templates_id AS a_email_verified_email_templates_id,
  a.forgot_password_email_templates_id AS a_forgot_password_email_templates_id,
  a.login_id_in_use_on_create_email_templates_id AS a_login_id_in_use_on_create_email_templates_id,
  a.login_id_in_use_on_update_email_templates_id AS a_login_id_in_use_on_update_email_templates_id,
  a.login_new_device_email_templates_id AS a_login_new_device_email_templates_id,
  a.login_suspicious_email_templates_id AS a_login_suspicious_email_templates_id,
  a.forms_id AS a_forms_id,
  a.id_token_populate_lambdas_id AS a_id_token_populate_lambdas_id,
  a.id_token_signing_keys_id AS a_id_token_signing_keys_id,
  a.inse
```

![image](https://user-images.githubusercontent.com/16117761/204088508-e8c1a82b-10cb-4c7d-9675-8e8f4336df75.png)
![image](https://user-images.githubusercontent.com/16117761/204088543-c4ff59c4-200f-4a5e-9a3f-787c9a98097e.png)

As you can see, this request seems heavy with an average execution time of 4.8s. Do you know why? Do you have a tip to optimize its execution?

**Comment by RicardoViteriR** [comment]
Hi @TanguyGiton I have the same issue. Accessing /api/status reports Unhealthy Hikari Pool Connection and 

```"HikariPool-1.pool.Connection99Percent": {
"healthy": false,
"message": "99th percentile connection wait time of 499ms exceeds the threshold 250ms"
},```

**Comment by TanguyGiton** [comment]
Hi @RicardoViteriR,

Are you using Cloud Run too?

I still haven't found a solution except increasing the value of `DATABASE_CONNECTION_HEALTHCHECK_99PERCENT_MS` (documented here https://fusionauth.io/docs/v1/tech/reference/configuration#overview)

And I don't have any feedback from FusionAuth team (@mooreds, @robotdan) on this issue 😢 

Nevertheless, happy holidays !

**Comment by RicardoViteriR** [comment]
Happy holidays @TanguyGiton 

Yes we are using Cloud Run, it's cost/benefit is outstanding for us. We configure our services to scale down to zero instances and saves us quite a bit. 

So, changing this setting fully solves your issue?

**Comment by TanguyGiton** [comment]
No, it's just a fallback to reduce the number of alerts we get in monitoring. But it doesn't solve the problem, the connection delay should not exceed 250ms in my opinion.

**Comment by RicardoViteriR** [comment]
I have the impression that Fusionauth is a stateful application. I see logs in the application that register that some async tasks have not completed. This makes sense to me when I consider that cloud run only assigns cpu to the container during the request lifetime. 

Maybe that is the common source of the issues we are seeing.

**Comment by TanguyGiton** [comment]
Indeed, this may be a reason. But in my case I always leave an active instance that goes to idle if no request is made.

Therefore, I would like to have feedback from the FusionAuth team to enlighten us about the application life cycle and find a way to optimize its hosting on Cloud Run.

I think compatibility with Cloud Run or PaaS services in general would be a strong asset for FusionAuth.

**Comment by RicardoViteriR** [comment]
By any chance are you leveraging container probes?

Wondering if there are any reliable Fusionauth endpoints that can be used for probes

https://cloud.google.com/run/docs/configuring/healthchecks

**Comment by robotdan** [comment]
This all looks to be working as designed. If we report a `453` it is because we are waiting too long for a database connection from the connection pool. 

This generally means the database is undersized. If Cloud Run is latently spinning up capacity to account for usage - and this latency is causing us to wait too long for a connection, we will begin to return a `453`. 

You can increase this configuration beyond  the default of `250ms`, and this may fix the status code, but the application will perform poorly. 

See `database.connection-healthcheck-99percent-ms`
- https://fusionauth.io/docs/v1/tech/reference/configuration#overview

HikariCP
- https://github.com/brettwooldridge/HikariCP/wiki/Dropwizard-HealthChecks#pool-namepoolconnectivitycheck

**Comment by TanguyGiton** [comment]
I have configured the startup and liveness probes as follows, and they are working well:

**Startup probe**
http /api/status
periodSeconds: 2s
initialDelaySeconds: 0s
timeoutSeconds: 1s
failureThreshold: 10

**Liveness probe**
http /api/status
periodSeconds: 10s
initialDelaySeconds: 0s
timeoutSeconds: 1s
failureThreshold: 3
