### ISSUE TITLE
Performance issues after upgrade to 1.41

### ISSUE THREAD

**Issue by cmarodrigues** [FusionAuth/fusionauth-issues#2002]
### Description
After upgrade from Fusionauth 1.30.2 to 1.41.2, we are facing some performance issues.
We are running Fusionauth over kubernetes with nginx as reverse proxy and Postgresql database.

Our environment has about 30k users and after login via admin, the nginx return timeout.

Opening directly the Fusionauth admin interface from 9011 port, the dashboard appears unformatted and with following errors:
![Screenshot from 2022-12-06 12-12-35](https://user-images.githubusercontent.com/2933578/207140167-f92ba52b-5fcf-4876-aef6-3521d4e9d38e.png)

The event log also has multiples FreeMaker messages as can see on the following image:
![image](https://user-images.githubusercontent.com/2933578/207141203-3030b60b-1a72-442b-8e46-86c9ef787b81.png)

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
Hi @cmarodrigues -- I think this is a known issue. 

nginx defaults to HTTP 1.0 for upstream connections, so you may need to explicitly configure this to be HTTP 1.1. 

> A change to the FusionAuth HTTP server may cause issues with reverse proxies that default upstream connections to HTTP/1.0. The HTTP server we are using no longer supports HTTP/1.0. We have identified that nginx defaults all upstream connections to HTTP/1.0, and the HTTP server we are using no longer supports HTTP/1.0. For nginx specifically, you will need to set the proxy version by adding proxy_http_version 1.1; to your proxy config.


https://fusionauth.io/docs/v1/tech/release-notes#version-1-41-0

Sorry for the inconvenience, we made a change in `1.41.0` and as a result no longer support `HTTP 1.0` natively. Let us know if this solve the issue for you.

**Comment by cmarodrigues** [comment]
Hi @robotdan, thank you for your answer.

I know about this known issue (yes i read the release notes :smile:) and i have the configuration for HTTP 1.1 ingress rule for kubernetes nginx:
`nginx.ingress.kubernetes.io/proxy-http-version: "1.1"`

Also, as you can see in the first screenshot that i post, this is the result of dashboard after connect directly to 9011 port (without nginx at the front) and with long time wait.

I think this is a performance issue, because the dashboard has some statistics about users and logins, and with 30k users, this page take to much time to render and also brakes some templates after long time wait.

Some other pages, take some time to render but at the end, the result its ok.

**Comment by robotdan** [comment]
Ok, thanks @cmarodrigues. We've heard this from a few folks so far - but have been unable to identify the cause. 

Can you provide some details about your instance of FusionAuth:

1. What flavor of postgres are you using, where is hosted, etc. 
2. User count is ~ 30k? 
3. How many tenants, are all users in one tenant?
4. How many applications, and how many roles per application.
5. How many groups, and are you using application roles with your groups?
6. Are most of your users registered for each app, and on average how many roles per user, and are those roles assigned by the user registration, or the group membership?

Thanks! I'd love to get to the bottom of this one.

**Comment by cmarodrigues** [comment]
Answers inline:
1. What flavor of postgres are you using, where is hosted, etc.
R: The Postgres is running on kubernetes. The version is 10.6
2. User count is ~ 30k?
R: User count is 30880
3. How many tenants, are all users in one tenant?
R: 2776 tenants and there is a tenant with 6500 users and others with a few dozen
4. How many applications, and how many roles per application.
R: 2776 applications and there is a application with 6000 roles and others with a few dozen
5. How many groups, and are you using application roles with your groups?
R: There are no groups
6. Are most of your users registered for each app, and on average how many roles per user, and are those roles assigned by the user registration, or the group membership?
R: All users are registered on each app and there is one role per each user. There are no groups.

**Comment by robotdan** [comment]
@cmarodrigues we've identified some improvements that benefit PostgreSQL in particular. 

What we haven't been able to identify is what would have caused the change between `1.30.2` and `1.41.1`. From your description, it sounds like this performed acceptable (?) at version `1.30.2`, and with essentially the same configuration (number of apps, tenants, etc) after upgrading, the performance was measurably worse? 

The SQL performance would have been equally poor at version `1.30.2` from what I can tell.

**Comment by cmarodrigues** [comment]
@robotdan Yes, the performance issue was detected after upgrade to `1.41.2`.
Also, i tried to downgrade the fusionauth instances to version `1.39.0` and works fine.

In our tests, we set the `log_min_duration_statement` parameter to `1000` to identify possible slow queries in our Postgresql instance, but no slow queries was logged.
So, this issue doesn't seem related to SQL performance. 

And the problem is mainly in the dashboard page. Others pages like Users, Applications and Tenants are render properly and without timeout errors.

**Comment by pyderator** [comment]
I am facing the same issue as of @cmarodrigues. The dashboard is loading too slowly and I get the following error in the stdout.

```
2023-02-04 10:27:08.898 AM ERROR io.fusionauth.http.server.HTTPServerThread - An exception was thrown during processing
java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:66)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:217)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:153)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:563)
	at java.base/java.nio.channels.SocketChannel.write(SocketChannel.java:642)
	at io.fusionauth.http.server.HTTPServerThread.write(HTTPServerThread.java:298)
	at io.fusionauth.http.server.HTTPServerThread.run(HTTPServerThread.java:158)
```
