### ISSUE TITLE
Idp Initiated SAML login where FusionAuth is the IdP throws a 500 exception when malformed application Id provided

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2252]
### Description 

You can cause a 500 error when using IdP initiated SAML login bu modifying the application Id.

### Affects versions

1.45.1

### Steps to reproduce
1. Create an application
2. Enable SAML (I used garbage values for issuer, authorized redirect urls, etc)
3. Enable IdP Initiated SAML
4. Save the application
5. View the application
6. Scroll to `Initiate login URL` and copy the URL.
7. Open an incognito browser
8. Paste the url. Add any character to the application Id
9. Hit enter.

Boom.

Here's the exception in the system logs:

```
2023-05-05 05:11:00.192 PM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
java.lang.NullPointerException: Cannot read field "samlv2Configuration" because "<parameter1>" is null
	at io.fusionauth.api.service.samlv2.DefaultSAMLv2ProviderService.resolveACSDuringIdPInitiatedLoginRequest(DefaultSAMLv2ProviderService.java:400)
	at io.fusionauth.api.service.samlv2.DefaultSAMLv2ProviderService.validateInitiatedLoginRequest(DefaultSAMLv2ProviderService.java:442)
	at io.fusionauth.app.action.samlv2.InitiateLoginAction.validate(InitiateLoginAction.java:82)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.primeframework.mvc.util.ReflectionUtils.invoke(ReflectionUtils.java:414)
	at org.primeframework.mvc.validation.DefaultValidationProcessor.validate(DefaultValidationProcessor.java:77)
	at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:44)
```

### Expected behavior

A 404 page is reasonable, I think. 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
Still see this issue in 1.54.0
