### ISSUE TITLE
PostgreSQL  15 maintenance mode error - Unexpected error is ORDINARY_USER_MISSING_PRIVS

### ISSUE THREAD

**Issue by ceefour** [FusionAuth/fusionauth-issues#2264]
### Description 

The UI doesn't show any error message:

![image](https://github.com/FusionAuth/fusionauth-issues/assets/24123/df0a8853-4fe4-46b6-a8f7-77248fd3e2bb)

It seems it should show an error message that is not retrievable.

But the Kubernetes container error log:

```
2023-05-13T05:56:28.057Z |   - Overriding default value of property [database.mysql.enforce-utf8mb4] with value [true]
2023-05-13T05:56:28.057Z |   - Overriding default value of property [FUSIONAUTH_APP_RUNTIME_MODE] with value [development]
2023-05-13T05:56:28.057Z |   - Overriding default value of property [SEARCH_TYPE] with value [database]
2023-05-13T05:56:28.057Z | 
2023-05-13T05:56:28.423Z | 2023-05-13 05:56:28.422 AM INFO  c.inversoft.maintenance.action.MaintenanceModeDatabaseConfigurationAction - [3] Request an update to the database status using root credentials.
2023-05-13T05:56:28.612Z | 2023-05-13 05:56:28.580 AM ERROR c.inversoft.maintenance.action.MaintenanceModeDatabaseConfigurationAction - Unexpected error is ORDINARY_USER_MISSING_PRIVS
2023-05-13T05:56:28.620Z | 2023-05-13 05:56:28.612 AM ERROR org.primeframework.mvc.workflow.DefaultExceptionHandler - Unhandled exception occurred
2023-05-13T05:56:28.620Z | org.primeframework.mvc.message.l10n.MissingMessageException: Message could not be found for the URI [/maintenance-mode-database-configuration] and key [[ORDINARY_USER_MISSING_PRIVS]]
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.message.l10n.ResourceBundleMessageProvider.getMessage(ResourceBundleMessageProvider.java:79)
2023-05-13T05:56:28.620Z |  at com.inversoft.maintenance.action.BaseMaintenanceModeAction.addGeneralError(BaseMaintenanceModeAction.java:60)
2023-05-13T05:56:28.620Z |  at com.inversoft.maintenance.action.MaintenanceModeDatabaseConfigurationAction.post(MaintenanceModeDatabaseConfigurationAction.java:141)
2023-05-13T05:56:28.620Z |  at jdk.internal.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
2023-05-13T05:56:28.620Z |  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-05-13T05:56:28.620Z |  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.util.ReflectionUtils.invoke(ReflectionUtils.java:414)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.execute(DefaultActionInvocationWorkflow.java:77)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.perform(DefaultActionInvocationWorkflow.java:60)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:50)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:45)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.security.DefaultSecurityWorkflow.perform(DefaultSecurityWorkflow.java:60)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.parameter.DefaultPostParameterWorkflow.perform(DefaultPostParameterWorkflow.java:49)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.content.DefaultContentWorkflow.perform(DefaultContentWorkflow.java:74)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:58)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:92)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:50)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:113)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:65)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
2023-05-13T05:56:28.620Z |  at com.inversoft.maintenance.primeframework.MaintenanceModePrimeWorkflow.perform(MaintenanceModePrimeWorkflow.java:49)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
2023-05-13T05:56:28.620Z |  at com.inversoft.maintenance.primeframework.mvc.MaintenanceModeMVCWorkflow.perform(MaintenanceModeMVCWorkflow.java:96)
2023-05-13T05:56:28.620Z |  at org.primeframework.mvc.PrimeMVCRequestHandler.handle(PrimeMVCRequestHandler.java:72)
2023-05-13T05:56:28.620Z |  at io.fusionauth.http.server.HTTPWorker.run(HTTPWorker.java:50)
2023-05-13T05:56:28.620Z |  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2023-05-13T05:56:28.620Z |  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-05-13T05:56:28.620Z |  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-05-13T05:56:28.620Z |  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-05-13T05:56:28.620Z |  at java.base/java.lang.Thread.run(Thread.java:833)
```

### Affects versions

1.45.2

### Steps to reproduce
1. Set up FusionAuth 1.45.2 using PostgreSQL 15
2. Get this error

### Expected behavior

A clear error message.

### Screenshots
(see above)

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1944
- https://github.com/FusionAuth/fusionauth-issues/issues/2015
- https://github.com/FusionAuth/fusionauth-issues/issues/2312
- https://github.com/FusionAuth/fusionauth-site/issues/2821 (a user ran into this with PG 14.0)

### Platform

 - Device: Client: MacBook Pro, FusionAuth: AWS t3.medium
 - OS: Client: Microsoft Edge
 - Browser + version: Microsoft Edge
 - Database: AWS RDS PostgreSQL 15

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Release Notes
Resolve an issue with running a new FusionAuth instance with AWS RDS PostgreSQL 15.2. Changes in the default permissions for public schemas in these versions prevented FusionAuth from creating the tables needed for it to run. These permissions are being explicitly granted now. In addition to this, the error message was being suppressed when a database user had insufficient permissions, so this condition was not being reported back to the user in the database configuration page. This has been remedied as well.

**Comment by ceefour** [comment]
Error related to https://github.com/FusionAuth/fusionauth-issues/issues/2015

**Comment by robotdan** [comment]
Internal:
- Missing message for `[ORDINARY_USER_MISSING_PRIVS]`
- Not handling some PostgreSQL state

**Comment by andrewpai** [comment]
Internal
- https://github.com/inversoft/inversoft-maintenance-mode/pull/4
- https://github.com/FusionAuth/fusionauth-app/pull/360
