### ISSUE TITLE
Error creating starting fusionauth in kubernetes

### ISSUE THREAD

**Issue by whiskerch** [FusionAuth/fusionauth-issues#237]
## (Put bug title here)
ERROR: role already exists when starting kubernetes pods
### Description 
I'm attempting to run up an instance of the fusion auth containers (version 1.7.2) in kubernetes. 
However, when the fusion auth pod starts, it fails to run the autoconfig with the following error: 

```
---------------------------------------------------------------------------------------------------------
---------------------------------- Entering Silent Configuration Mode -----------------------------------
---------------------------------------------------------------------------------------------------------

Jul 29, 2019 9:04:25.758 AM ERROR com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService - Exception caught executing [CREATE ROLE xxxxx WITH LOGIN PASSWORD 'xxxxx']
org.postgresql.util.PSQLException: ERROR: role "xxxxx" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:303)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:289)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:262)
	at com.inversoft.maintenance.db.SQLExecutor.executeStatementWithError(SQLExecutor.java:55)
	at com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService.createOrdinaryUser(JDBCMaintenanceModeDatabaseService.java:148)
	at com.inversoft.maintenance.db.DatabaseSilentConfigurationWorkflowTask.perform(DatabaseSilentConfigurationWorkflowTask.java:54)
	at com.inversoft.maintenance.DefaultMaintenanceModeSilentConfigurationWorkflow.perform(DefaultMaintenanceModeSilentConfigurationWorkflow.java:36)
	at com.inversoft.maintenance.servlet.MaintenanceModePrimeServletContextListener.contextInitialized(MaintenanceModePrimeServletContextListener.java:41)
	at io.fusionauth.app.primeframework.FusionAuthAppPrimeServletContextListener.contextInitialized(FusionAuthAppPrimeServletContextListener.java:29)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4792)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5256)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Jul 29, 2019 9:04:25.758 AM ERROR com.inversoft.maintenance.db.DatabaseSilentConfigurationWorkflowTask - ERROR: role "xxxxx" already exists
```

This is a brand new set of pods so there is no data in the database (or roles) when the fusion auth pod starts
### Platform
Kubernetes

**Comment by robotdan** [comment]
The maintenance mode should tolerate this type of error so that if you provide existing user credentials to the database we continue to use them. 

What version of PostgreSQL are you using?

**Comment by whiskerch** [comment]
I am using postgreSQL 9.6

I changed the username back to `fusionauth` and this has resolved the issue. I had been using the username `taZdJ2cmDxgsjdT8` when I was having issues

Regards

Chris

**Comment by robotdan** [comment]
Got it thanks! Trying to figure out why the db fails during a statement execution can be tricky. 

I've added some additional code to hopefully catch this exception properly, the expected behavior is to ignore users that already exist and continue on.

**Comment by henri9813** [comment]
Hello,

I have the same problem, with username MKCSN7VRVBgjaH4A.

This issue seems to be closed, however, i have this issue for fusionauth 1.15.8


Regards.

**Comment by henri9813** [comment]
Hello @robotdan ,

I have the same problem, with username MKCSN7VRVBgjaH4A.

This issue seems to be closed, however, i have this issue for fusionauth 1.15.8

Regards.

**Comment by robotdan** [comment]
@henri9813 looks like a case issue from the error message. We parse the error but I think we are expecting `MKCSN7VRVBgjaH4A`. 

To work around this - you can create lower case the username. We can re-open this issue to resolve the case checking.
