### ISSUE TITLE
Reset password with re-hash on login : Invalid factor value

### ISSUE THREAD

**Issue by colundrum** [FusionAuth/fusionauth-issues#250]
### Description 
`java.lang.IllegalArgumentException: Invalid factor value [26624]` when doing forget password with re-hash on login activated

### Steps to reproduce
1. Have a user with bcrypt password
2. Go in System > Settings > Passwords
3. Scroll down to Cryptographic hash settings
4 . Set :
 - Scheme : Salted PBKDF2 with SHA-256
 - Factor : 26624
 - Re-hash on login : activated

### Expected behavior
All fine on reset password

From log :

```
Jul 31, 2019 5:28:22.968 PM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
java.lang.IllegalArgumentException: Invalid factor value [26624]
        at io.fusionauth.api.security.BCryptPasswordEncryptor.encrypt(BCryptPasswordEncryptor.java:30) ~[fusionauth-api-1.6.1.jar:1.6.1]
        at io.fusionauth.api.service.user.DefaultPasswordService.hashPassword(DefaultPasswordService.java:68) ~[fusionauth-api-1.6.1.jar:1.6.1]
        at io.fusionauth.api.service.user.DefaultUserService._updatePassword(DefaultUserService.java:1529) ~[fusionauth-api-1.6.1.jar:1.6.1]
        at io.fusionauth.api.service.user.DefaultUserService.updatePasswordByChangePasswordId(DefaultUserService.java:963) ~[fusionauth-api-1.6.1.jar:1.6.1]
        at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96) ~[mybatis-guice-3.10.0.jar:3.10]
        at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96) ~[mybatis-guice-3.10.0.jar:3.10]
        at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96) ~[mybatis-guice-3.10.0.jar:3.10]
        at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96) ~[mybatis-guice-3.10.0.jar:3.10]
        at io.fusionauth.app.action.api.user.ChangePasswordAction.post(ChangePasswordAction.java:105) ~[fusionauth-app-1.6.1.jar:1.6.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
        at org.primeframework.mvc.util.ReflectionUtils.invoke(ReflectionUtils.java:436) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.execute(DefaultActionInvocationWorkflow.java:84) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.perform(DefaultActionInvocationWorkflow.java:64) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:47) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.security.DefaultSecurityWorkflow.perform(DefaultSecurityWorkflow.java:81) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.parameter.DefaultPostParameterWorkflow.perform(DefaultPostParameterWorkflow.java:50) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.content.DefaultContentWorkflow.perform(DefaultContentWorkflow.java:52) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:57) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:102) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:58) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:45) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:126) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.workflow.StaticResourceWorkflow.perform(StaticResourceWorkflow.java:97) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.parameter.RequestBodyWorkflow.perform(RequestBodyWorkflow.java:89) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:57) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.workflow.DefaultMVCWorkflow.perform(DefaultMVCWorkflow.java:91) ~[prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44) [prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50) [prime-mvc-1.13.3.jar:1.13.3]
        at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:84) [prime-mvc-1.13.3.jar:1.13.3]
        at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:59) [inversoft-maintenance-mode-0.12.8.jar:0.12.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.31]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.31]
        at com.inversoft.servlet.CORSFilter.handleNonCORS(CORSFilter.java:748) [inversoft-servlet-0.1.1.jar:0.1.1]
        at com.inversoft.servlet.CORSFilter.doFilter(CORSFilter.java:646) [inversoft-servlet-0.1.1.jar:0.1.1]
```

After a switch to Factor to 5000

I obtain the same error :
```
io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
java.lang.IllegalArgumentException: Invalid factor value [26624]
```

The factor hasn't changed.

Can you tell me how to fix this critical issue ?

FusionAuth version : 1.6.1

Regards

**Comment by robotdan** [comment]
Interesting, it seems to be using the factor validation for bcrypt which does have an enforced maximum factor value of `30`. 


I'll have to investigate further.

**Comment by robotdan** [comment]
It seems like the only way this could happen is if the `factor` stored on the user was not defined, but I don't know how this would happen. 

If you're comfortable in SQL, you could select the user to see if the db state is as expected. 

`> SELECT encryption_scheme, factor FROM identities where email = 'an email address'`

**Comment by colundrum** [comment]
Effectively, we have a problem in the db :
```
encryption_scheme | factor
-------------------+--------
 bcrypt            |  26624
```

On the user with the problem, maybe I need to switch the factor to 30 …

Why not overwritten directly encryption_scheme and factor because it's a forgotten password

**Comment by robotdan** [comment]
Ok, so a fix to the current issue would be

`UPDATE identities SET factor = 12 WHERE encryption_scheme = 'bcrypt' AND factor > 30`

A factor of `30` while allowed, is extremely large, the bcrypt work factor is not linear, our default is `12`. 

```
2^ 12 = 4,096
2^ 30 = 1,073,741,824
```

With a work factor of `30`, your login request may never come back. :-) 

Do you know the order of how this happened? Was the user imported like this, or were they working and then through a change password or something like that it stopped working?

**Comment by colundrum** [comment]
Output : UPDATE 2982

I've a good cpu so not really a problem and we're not working on public cloud so we have full control of our stack.

It's due to a very big import directly via fusionauth api (python client) + sql import ...
SQL import was a terrible idea but this bug was affecting only few persons and not all and it's the problem because a lot of people was able to connect/forget password without this problem.
It's incroyable strange.

Again thanks a lot

**Comment by robotdan** [comment]
Thanks for the update. To make sure I follow, you used the Import API and some direct SQL imports? 

I want to make sure we don't have a bug here, but it sounds like you've identified the issue as using a direct SQL import? 

If that is not correct and this mismatch of encryption scheme and factor occurred as a result of a FusionAuth API or workflow, then let me know and we can re-open.

**Comment by colundrum** [comment]
Create user and inject sql queries

Yes, I think the problem was in this SQL query :
`update identities set encryption_scheme='bcrypt', password = '{1}' where email='{0}';".format(json_email, json_pwd)`

But "factor" wasn't set so why this bug today ?

**Comment by robotdan** [comment]
We do not support making direct updates to the database, so it is hard to say what was happening.  You will want to use the Import API so that we can validate and default the correct values. 

Is there a reason why you are making direct SQL updates instead of using the API?

**Comment by colundrum** [comment]
My mistake about miss using Import API
But it's also most quick to send a big SQL file to the server and run it than API requests when I'm in roadwarrior mode (3/4G + VPN)
