### ISSUE TITLE
Internal Server Error caused by NPE

### ISSUE THREAD

**Issue by Unisay** [FusionAuth/fusionauth-issues#254]
### Description 
Server (running in docker container via docker-compose) responds with status code `500`:

```
fusionauth_1  | Aug 03, 2019 11:38:22.805 AM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
fusionauth_1  | java.lang.NullPointerException: null
fusionauth_1  | 	at io.fusionauth.domain.UserRegistration.normalize(UserRegistration.java:165)
fusionauth_1  | 	at io.fusionauth.app.action.api.user.RegistrationAction.validate(RegistrationAction.java:112)
fusionauth_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
fusionauth_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
fusionauth_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
fusionauth_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
fusionauth_1  | 	at org.primeframework.mvc.util.ReflectionUtils.invoke(ReflectionUtils.java:436)
fusionauth_1  | 	at org.primeframework.mvc.validation.DefaultValidationProcessor.validate(DefaultValidationProcessor.java:77)
fusionauth_1  | 	at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:46)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at org.primeframework.mvc.security.DefaultSecurityWorkflow.perform(DefaultSecurityWorkflow.java:81)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at org.primeframework.mvc.parameter.DefaultPostParameterWorkflow.perform(DefaultPostParameterWorkflow.java:50)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at org.primeframework.mvc.content.DefaultContentWorkflow.perform(DefaultContentWorkflow.java:52)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:57)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:102)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:58)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:45)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:126)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at org.primeframework.mvc.workflow.StaticResourceWorkflow.perform(StaticResourceWorkflow.java:97)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at org.primeframework.mvc.parameter.RequestBodyWorkflow.perform(RequestBodyWorkflow.java:89)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:57)
fusionauth_1  | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1  | 	at org.primeframework.mvc.workflow.DefaultMVCWorkflow.perform(DefaultMVCWorkflow.java:91)
fusionauth_1  | 	at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44)
fusionauth_1  | 	at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50)
fusionauth_1  | 	at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:84)
fusionauth_1  | 	at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:59)
fusionauth_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
fusionauth_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
fusionauth_1  | 	at com.inversoft.servlet.CORSFilter.handleNonCORS(CORSFilter.java:748)
fusionauth_1  | 	at com.inversoft.servlet.CORSFilter.doFilter(CORSFilter.java:646)
fusionauth_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
fusionauth_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
fusionauth_1  | 	at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27)
fusionauth_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
fusionauth_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
fusionauth_1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
fusionauth_1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
fusionauth_1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
fusionauth_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
fusionauth_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
fusionauth_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
fusionauth_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
fusionauth_1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
fusionauth_1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
fusionauth_1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
fusionauth_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)
fusionauth_1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
fusionauth_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
fusionauth_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
fusionauth_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
fusionauth_1  | 	at java.lang.Thread.run(Thread.java:748)
```

### Steps to reproduce
```
http POST http://localhost:9011/api/user/registration/ Authorization:*** < example.json
HTTP/1.1 500 
Connection: close
Content-Length: 313
Content-Type: application/json;charset=UTF-8
Date: Sat, 03 Aug 2019 11:43:40 GMT

{
    "fieldErrors": {
        "userId": [
            {
                "code": "[couldNotConvert]userId",
                "message": "Invalid userId [index]. This must be a valid UUID String (e.g. 25a872da-bb44-4af8-a43d-e7bcb5351ebc)."
            }
        ]
    },
    "generalErrors": [
        {
            "code": "[Exception]",
            "message": "FusionAuth encountered an unexpected error. Please contact support for assistance."
        }
    ]
}
```

### Expected behavior
Status code 400 (The request was invalid and/or malformed.)

### Platform
 - Device: Desktop
 - OS: Fedora Linux 

### Additional context
example.json:
```json
{
  "usersTwoFactorDelivery":null,
  "user":{
    "username":null,
    "twoFactorSecret":null,
    "twoFactorEnabled":null,
    "timezone":null,
    "preferredLanguages":null,
    "passwordChangeRequired":null,
    "password":null,
    "mobilePhone":null,
    "middleName":null,
    "lastName":null,
    "imageUrl":null,
    "id":null,
    "fullName":null,
    "firstName":null,
    "factor":null,
    "expiry":null,
    "encryptionScheme":null,
    "email":"unisay@noreply.github.com",
    "data":null,
    "birthDate":null
  },
  "skipVerification":null,
  "skipRegistrationVerification":null,
  "sendSetPasswordEmail":null,
  "registration":{
    "username":null,
    "timezone":null,
    "roles":null,
    "preferredLanguages":null,
    "id":null,
    "data":null,
    "applicationId":"63ba6d7e-af6c-44bf-9516-41c1152ab784"
  },
  "generateAuthenticationToken":null
}
```

**Comment by robotdan** [comment]
We don't currently support null values on the inbound JSON request body. 

https://fusionauth.io/docs/v1/tech/apis/

Can try to reproduce after removing the those from the request body?

Also the API URL should not end in a slash unless another value is provided after the slash.

My guess is that is the cause for the two errors you're seeing. 

If you remove the nulls, the other error should return as a 400.

**Comment by Unisay** [comment]
@robotdan 

Thank you for explaining why request is bad,
however this is not the point here:
expected behaviour is response code 400 instead of 500 (internal server error)

HTTP status code semantics prescribe to respond `Bad Request` when problem has to be fixed by client, and 500 if it has to be fixed by server [developer]

**Comment by Unisay** [comment]
Context: http://restcookbook.com/HTTP%20Methods/400-vs-500/

**Comment by robotdan** [comment]
You're correct in this case the 500 is not an ideal response because it is caused by the caller sending an invalid request.

We only return 400 when it is something expected that we can validate and communicate back to the caller to correct. 

In theory we could be very defensive and check everything for null and then validate that with a 400 response code. We have chosen not to do that and instead document that we don't support null values in JSON.

It is possible we will revisit this limitation once the underlying JSON library we use supports removing all null values during deserialization.

Thanks for the feedback.

**Comment by robotdan** [comment]
Please re-open if this still occurs.
