### ISSUE TITLE
[Bug]: Creating a Google Identity Provider and then hitting back and save again causes a 500 error

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2719]
### What happened?

* create a google identity provider
* hit the back button
* resubmit it

You see an error message stating a 500 server error occurred.

In System -> Logs, I see this:

```
2024-04-19 06:51:30.015 PM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
org.primeframework.mvc.message.l10n.MissingMessageException: Message could not be found for the URI [/admin/identity-provider/add] and key [[GoogleAlreadyCreated]]
	at org.primeframework.mvc.message.l10n.ResourceBundleMessageProvider.getMessage(ResourceBundleMessageProvider.java:79)
	at io.fusionauth.app.service.FrontEndSupport.addGeneralError(FrontEndSupport.java:225)
	at io.fusionauth.app.service.FrontEndSupport.lambda$transfer$6(FrontEndSupport.java:734)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.fusionauth.app.service.FrontEndSupport.transfer(FrontEndSupport.java:734)
	at io.fusionauth.app.service.FrontEndSupport.transfer(FrontEndSupport.java:684)
	at io.fusionauth.app.service.FrontEndSupport.frontEndErrorHandling(FrontEndSupport.java:380)
	at io.fusionauth.client.LambdaDelegate.execute(LambdaDelegate.java:62)
	at io.fusionauth.app.action.admin.identityProvider.AddAction.post(AddAction.java:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.primeframework.mvc.util.ReflectionUtils.invoke(ReflectionUtils.java:443)
	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.execute(DefaultActionInvocationWorkflow.java:77)
	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.perform(DefaultActionInvocationWorkflow.java:60)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:50)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:45)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.security.DefaultSecurityWorkflow.perform(DefaultSecurityWorkflow.java:79)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.parameter.DefaultPostParameterWorkflow.perform(DefaultPostParameterWorkflow.java:49)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.content.DefaultContentWorkflow.perform(DefaultContentWorkflow.java:74)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:58)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:92)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:50)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:119)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:65)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.cors.CORSRequestWorkflow.perform(CORSRequestWorkflow.java:65)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.workflow.DefaultMVCWorkflow.perform(DefaultMVCWorkflow.java:108)
	at org.primeframework.mvc.PrimeMVCRequestHandler.handle(PrimeMVCRequestHandler.java:73)
	at io.fusionauth.http.server.HTTPWorker.run(HTTPWorker.java:50)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### Version

1.49.2

**Comment by robotdan** [comment]
Working as designed I suppose. We just don't expect this error in the UI because we keep you from clicking the Add button again if you already have a Google IdP configured. 

Internal:
- We could adjust the cache control state on this page to avoid the back button issue, but this has some UX concerns. 
- We could validate this better on page load and kick you out. 
- We could just add this error to the UI for this edge case so that we don't explode but show a nice error.

**Comment by mooreds** [comment]
Certainly seems like adding the known error key would be easiest.

```
Message could not be found for the URI [/admin/identity-provider/add] and key [[GoogleAlreadyCreated]]
```

**Comment by wied03** [comment]
Now we support more than 1 Google IDP, so I think this issue is now a moot point. Happy to reopen if that's not the case.
