### ISSUE TITLE
Malformed session token right after user registration

### ISSUE THREAD

**Issue by johnmaia** [FusionAuth/fusionauth-issues#274]
### Description

Following the same steps described on a previous [issue](https://github.com/FusionAuth/fusionauth-issues/issues/252):
- Create a new `tenant`
- Create a new `application` on the previous `tenant`
- Create a new `lambda` for the previous `application`:
```js
function populate(jwt, user, registration) { jwt.foobarId = user.data.foobarId; }
```
- Create a new `user` on previous the `application` with a `foobarId` value on its `data` 
- Login the previous `user`
- FusionAuth returns a `jwt` that is missing the `foobarId`

### Expected behavior
Return a `jwt` with the `user` `foobarId` value.

### Stack

```
Aug 14, 2019 4:41:31.600 PM ERROR io.fusionauth.api.service.jwt.DefaultJWTService - Failed to apply lambda during JWT creation.
io.fusionauth.api.service.system.LambdaInvocationException: javax.script.ScriptException: TypeError: Cannot read property "foobarId" from undefined in <eval> at line number 1
	at io.fusionauth.api.service.system.DefaultLambdaInvocationService.invoke(DefaultLambdaInvocationService.java:57)
	at io.fusionauth.api.service.jwt.DefaultJWTService.applyLambda(DefaultJWTService.java:328)
	at io.fusionauth.api.service.jwt.DefaultJWTService.generateJWTWithExpiration(DefaultJWTService.java:386)
	at io.fusionauth.api.service.jwt.DefaultJWTService.createJWT(DefaultJWTService.java:97)
	at io.fusionauth.app.action.api.BaseLoginAction.addTokensToResponse(BaseLoginAction.java:118)
	at io.fusionauth.app.action.api.BaseLoginAction.handleAuthenticationResult(BaseLoginAction.java:212)
	at io.fusionauth.app.action.api.BaseLoginAction.callLogin(BaseLoginAction.java:179)
	at io.fusionauth.app.action.api.LoginAction.post(LoginAction.java:147)
	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.primeframework.mvc.util.ReflectionUtils.invoke(ReflectionUtils.java:436)
	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.execute(DefaultActionInvocationWorkflow.java:84)
	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.perform(DefaultActionInvocationWorkflow.java:64)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:47)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.security.DefaultSecurityWorkflow.perform(DefaultSecurityWorkflow.java:81)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.parameter.DefaultPostParameterWorkflow.perform(DefaultPostParameterWorkflow.java:50)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.content.DefaultContentWorkflow.perform(DefaultContentWorkflow.java:52)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:57)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:102)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:58)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:45)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:126)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.workflow.StaticResourceWorkflow.perform(StaticResourceWorkflow.java:97)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.parameter.RequestBodyWorkflow.perform(RequestBodyWorkflow.java:89)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:57)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.workflow.DefaultMVCWorkflow.perform(DefaultMVCWorkflow.java:91)
	at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44)
	at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50)
	at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:84)
	at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.inversoft.servlet.CORSFilter.handleNonCORS(CORSFilter.java:748)
	at com.inversoft.servlet.CORSFilter.doFilter(CORSFilter.java:646)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.script.ScriptException: TypeError: Cannot read property "foobarId" from undefined in <eval> at line number 1
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at io.fusionauth.api.domain.CompiledLambda.invoke(CompiledLambda.java:72)
	at io.fusionauth.api.service.system.DefaultLambdaInvocationService.invoke(DefaultLambdaInvocationService.java:40)
	... 68 common frames omitted
Caused by: jdk.nashorn.internal.runtime.ECMAException: TypeError: Cannot read property "foobarId" from undefined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.runtime.Undefined.get(Undefined.java:157)
	at jdk.nashorn.internal.scripts.Script$Recompilation$2595238$43AAA$\^eval\_.populate(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:663)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
	... 71 common frames omitted
```

### Notes: 
- If we wait a few seconds and login the same `user` the `jwt` token includes the `foobarId` value

- The issue here only happens if we `login` the `user` right after its registration

- The error stack suggests that at the time of the `user` `login` the `data` property does not exist which is kinda weird

**Comment by robotdan** [comment]
This looks to be likely the same root cause as you described in issue https://github.com/FusionAuth/fusionauth-issues/issues/252.

However, we never cache the user object itself, so if you create a user and set `foobarId` on the user data, it will be available immediately. So that part is interesting.

I'll see if I can recreate, and if not we can see if the symptom is resolved once at 1.8.0.

**Comment by johnmaia** [comment]
@robotdan on a fusionauth that has fewer `tenants` and this issue does not occur. 
We have two fusionauth instances running in two separate environments (`test` and `staging`). On our `staging` environment that has less usage and therefore fewer `tenants` this issue does not occur.

**Comment by johnmaia** [comment]
@robotdan please note that we are only using a single instance of `fusionauth` on both environments.

**Comment by johnmaia** [comment]
@robotdan we've update `fusionauth` version to `1.10.1` and this is still happening on our test environment were we have over 4k tenants. This issue is not happening on our staging environment where we have just 95 tenants.

**Comment by johnmaia** [comment]
Not the total number of users of the test environment is around 14k and staging only has a few hundred.

**Comment by robotdan** [comment]
Thanks for the additional details @johnmaia .

If you're not on the Slack channel yet, please request an invite on our community page. We have not really envisioned a use case for 4k tenants.

So, if you're interested, I'd like to set up a call to discuss your use case. There may be some performance considerations with this number of tenants, so perhaps we can recommend an alternate approach or make some enhancements to make sure it works well for you. 

Thanks!

https://fusionauth.io/community

**Comment by robotdan** [comment]
Trying to recreate, are you creating a new lambda in each iteration of your test, or do you create one lambda and use it for all tenants / applications? 

Here is what I'm currently testing with, I've tried creating the lambda outside of this loop and inside of the loop. 

```
do 5_000 times 
  - Create tenant
  - Create lambda to add user.data.foobarId to the JWT
  - Create application using the lambda
  - Create user w/ data.foobarId
  - Create User Registration
  - Login
  - Assert the JWT contains foobarId
```

**Comment by johnmaia** [comment]
Yes, I'm creating a new lambda in each iteration. With 5k tenants and your not getting the same issue?

**Comment by robotdan** [comment]
Yeah, so far I've tried creating a Lambda once and re-using it and building a new one per tenant. 

Just for clarification, you do not need to create a lambda per tenant, you can use one lambda for all tenants. But I understand if this is just how your tests are built. 

> Please note that the error is not related with the lambda. The error indicates that at the moment when the JWT is created, the user.data object does not exist (undefined):

Yes, I think we are on the same page. I'm using your Lambda function verbatim. 

I can try to recreate again..  let me know if any other details come to mind that may help me recreate. It could be a threading issue, my tests are perhaps not hitting the system via multiple threads as would be in production or your tests. I can try throwing our load tests at this to see if that yields different results.

**Comment by robotdan** [comment]
I ran a login load test w/ a lambda used during login with 5k tenants, and have not had any issues.

**Comment by johnmaia** [comment]
I'll have to recheck our flow and see if we are doing anything differently that could be causing this issue. By the way, how much memory is your instance with 5k tenants using?

**Comment by johnmaia** [comment]
This could be related to the environment where FusionAuth is running. We're using FusionAuth in Kubernetes and you're probably running in directly on your system. Our devops team suggested that probably this is not happening to you because on your system when the application runs the login process the data has already propagated and the it has no issue accessing the `user` `data` property.

Just to be clear, this is only happening on the first login attempt that is processed programmatically right after registering the user. If we attempt to login the same user just a few seconds after this error no longer exists.

**Comment by robotdan** [comment]
I'd have to re-run to check RAM consumption, but I was likely running with 1GB of heap available. I am running on my dev box (Macbook Pro, 32G RAM)

>  Our devops team suggested that probably this is not happening to you because on your system when the application runs the login process the data has already propagated and the it has no issue accessing the user data property.

We never cache the user object, so I still don't know how this can happen. It obviously is... :-) 
> ![debugging](https://user-images.githubusercontent.com/1148709/67341444-ea303d80-f4ec-11e9-8326-c1d4f4de620b.jpg)


Have you tried recreating and re-using the lambda instead of creating a new one on each iteration?

**Comment by johnmaia** [comment]
Hi @robotdan I have some new updates related to this issue. We've took another look on our side and it looks like the issue is no longer related to the lambda function but rather related to the `jwt/validate` or `jwt/refresh` endpoints.

- We are getting a `401` from the `jwt/validate` endpoint when we programmatically do:
```
  - Create tenant
  - Create lambda to add user.data.foobarId to the JWT
  - Create application using the lambda
  - Create user w/ data.foobarId
  - Create User Registration
  - Login
  - Validate token
```

Here is the tcpdump from `fusionauth`:
```
GET /api/jwt/validate HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjdWWTBPTlhteUdXNHJtM1VXc0IzdlJBTDJGV2lxTE1zIn0.eyJhdWQiOiI4MmMyMTY1MC02YTliLTQ5NzItYjBlOC02NmFkZTNmODNkZDIiLCJleHAiOjE1NzE5MTM1MzQsImlhdCI6MTU3MTkwOTkzNCwiaXNzIjoic2x5ay5pbyIsInN1YiI6ImJjNTc2MTUwLTJjMWMtNGQzMS05NmU4LWU5YzdkNjQ1M2ViZCIsImF1dGhlbnRpY2F0aW9uVHlwZSI6IlBBU1NXT1JEIiwiZW1haWwiOiJmb29iYXJAZm9vLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhcHBsaWNhdGlvbklkIjoiODJjMjE2NTAtNmE5Yi00OTcyLWIwZTgtNjZhZGUzZjgzZGQyIiwicm9sZXMiOlsib3duZXIiXX0.FZ7GV1rukZJJz7nmYkPWm2-QgMsELZCfmE4wqiO28a8
X-FusionAuth-TenantId: 82c21650-6a9b-4972-b0e8-66ade3f83dd2
Host: fusionauth-svc:9011
Connection: close

HTTP/1.1 401
Content-Length: 0
Date: Thu, 24 Oct 2019 09:38:53 GMT
Connection: close
```

- And we are getting a `400` from the `jwt/refresh` endpoint when we programmatically do:
```
  - Create tenant
  - Create lambda to add user.data.foobarId to the JWT
  - Create application using the lambda
  - Create user w/ data.foobarId
  - Create User Registration
  - Login
  - Change password
  - Refresh token
```

Here is the tcpdump from `fusionauth`:
```
POST /api/jwt/refresh HTTP/1.1
Authorization: Wx3aFrAYfNK1KbHLIGSY1e7d4C6ET7YDNNrbNp8qhxI
X-FusionAuth-TenantId: 74331b35-77dd-40a2-ab70-39b4d692b9b1
Content-Type: application/json
Content-Length: 73
Host: fusionauth-svc:9011
Connection: close

{"refreshToken":"LcR1Msxc9jRAUOw76Be7lKtL6rPx6H-P0JV-qxzWSmQ6180fo8cQTQ"}HTTP/1.1 400
Content-Type: application/json;charset=UTF-8
Content-Length: 127
Date: Thu, 24 Oct 2019 10:02:11 GMT
Connection: close

{"fieldErrors":{"refreshToken":[{"code":"[invalid]refreshToken","message":"The refresh token was not found or has expired."}]}}
```

Sadly we also noted that although the lamdba function related error, shown in the beginning of this issue, is no longer thrown by fusionauth the `foobarId` attribute is still not present on the `jwt` that is generated on the first login.

**Comment by robotdan** [comment]
There is likely some timing issues occurring due to some caching. 

You could try adding a short pause in your tests after you create a tenant, application or lambda to allow the lambda cache or key cache to complete reload.

**Comment by johnmaia** [comment]
Yes, during debugging we've tried some `console.log` and `try catch` and we've noticed that the error didn't occurred so frequently. 

We're trying to find what's the best solution for this issue. We would prefer to implement a more fail resistant solution instead of a `sleep` or a `retry` system on our side. 

I don't know if it's possible to implement, but it would be preferable to have the option to not use cache in some FusionAuth endpoints. This option should be disabled by default but would be an more fail resistant solution.

**Comment by robotdan** [comment]
Because one Lambda can be used for all tenants in theory (if the business logic applies), is this a dev / test issue, or do you intend to also use FusionAuth like this in production? 

In other words, would the following be a more likely production scenario for you? 

```
- Create lambda to add user.data.foobarId to the JWT
- Create tenant
- Create application using the lambda
- Create user w/ data.foobarId
- Create User Registration
- Login
- Change password
- Refresh token
```

And if so, in this case does the error still occur?

**Comment by johnmaia** [comment]
Hello there @robotdan! Fantastic news :)

We've followed your suggestion and used a single lambda function for all our tenants. By doing so, the JWT now comes well constructed and with all the expected values. 

We also noticed that the FusionAuth memory usage was drastically reduced, from almost 9GB to only 1.4GB (currently).

Thank you very much for all your help!

**Comment by robotdan** [comment]
Awesome!! Ha.. yeah, I didn't even think about that, but totally makes sense that so many Lambdas would bloat the heap. 

Each lambda has to be created in it's own engine to preserve thread safety and we have to compile them and keep them ready - so 5k lambdas is a lot! :-) 

I'll close out this issue.  You have an interesting model, if you're interested in doing a joint case study or anything interesting like that once you get this into prod let me know.  You have my email. :-)

**Comment by johnmaia** [comment]
@robotdan sadly we are still having the issues related to the `jwt/validate` or `jwt/refresh` endpoints but its less often. When we programmatically register, login and validate the token we get `401` from the `jwt/validate` endpoint.
This is most definitely related to cache given that if we delay the call of the`jwt/validate` endpoint it won't throw a `401`.

Is it possible to enhance these endpoints in order to avoid these kind of issues?  

We celebrated too early :P

**Comment by robotdan** [comment]
Hi @johnmaia my guess is that this is because when you create a tenant or application with specific JWT signing keys we reload the JWT verifier cache.

> Is it possible to enhance these endpoints in order to avoid these kind of issues?

From what I can tell this is working as designed. My assumption is that this is a dev time / test issue and that you won't need to create a tenant, application, user and then validate the JWT within milliseconds in a production mode? 

Making all of this be synchronous would impact performance and doesn't seem like a real world use case, but let me know if you have a production use case where this all needs to happen within milliseconds.
