### ISSUE TITLE
[Bug]: Unable to see any Provider, when an OIDC Discover URL don't work

### ISSUE THREAD

**Issue by konvergence** [FusionAuth/fusionauth-issues#2842]
### What happened?

[fusionauth-webapp-79fbff7d4f-jf5p2_fusionauth.log](https://github.com/user-attachments/files/16659635/fusionauth-webapp-79fbff7d4f-jf5p2_fusionauth.log)

I don't know if the error is related to the issue, but on startup we get this error into the pod logs

```
2024-08-19 10:20:12.847 AM ERROR com.inversoft.scheduler.LogAndRetainFailureHandler - The scheduled service [class io.fusionauth.api.service.cache.IdentityProviderCacheLoader] failed but will be re-run.
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "name" is null
	at com.inversoft.http.Cookie.addAttribute(Cookie.java:192)
	at com.inversoft.http.Cookie.fromResponseHeader(Cookie.java:178)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.inversoft.rest.ClientResponse.setHeaders(ClientResponse.java:129)
	at com.inversoft.rest.RESTClient.go(RESTClient.java:410)
	at io.fusionauth.api.service.identity.OpenIdConnectIdentityProviderHelper.resolveOpenIDConnectEndpoints(OpenIdConnectIdentityProviderHelper.java:80)
	at io.fusionauth.api.service.cache.IdentityProviderCacheLoader.retrieveAllAndResolveOpenIDConnectEndpoints(IdentityProviderCacheLoader.java:73)
	at io.fusionauth.api.service.cache.IdentityProviderCacheLoader.internalLoad(IdentityProviderCacheLoader.java:53)
	at com.inversoft.cache.BaseCacheLoader.load(BaseCacheLoader.java:21)
	at io.fusionauth.api.service.cache.IdentityProviderCacheLoader.run(IdentityProviderCacheLoader.java:48)
	at com.inversoft.scheduler.InjectableRunnable.run(InjectableRunnable.java:56)
	at com.inversoft.scheduler.DefaultScheduler.<init>(DefaultScheduler.java:70)
	at com.inversoft.scheduler.DefaultScheduler$$FastClassByGuice$$c8dd959.GUICE$TRAMPOLINE(<generated>)
	at com.inversoft.scheduler.DefaultScheduler$$FastClassByGuice$$c8dd959.apply(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at org.primeframework.mvc.guice.GuiceBootstrap.initialize(GuiceBootstrap.java:60)
	at org.primeframework.mvc.BasePrimeMain.hup(BasePrimeMain.java:69)
	at org.primeframework.mvc.BasePrimeMain.start(BasePrimeMain.java:100)
	at io.fusionauth.app.FusionAuthMain.main(FusionAuthMain.java:27)
```

### Version

1.48.3

**Comment by konvergence** [comment]
After a long time, we discovered that the error came from an OIDC provider using the “Discover endpoints” mode.
The OIDC provider was working some months ago. After removing the OIDC provider, all other providers are working again.

We have tried to recreate the same OIDC provider. But this time, it causes an error during creation.
`FusionAuth encountered an unexpected error. Please review the troubleshooting guide found in the documentation for assistance and the available support channels`

and into the logs of pod
```
2024-08-19 01:20:49.723 PM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "name" is null
	at com.inversoft.http.Cookie.addAttribute(Cookie.java:192)
	at com.inversoft.http.Cookie.fromResponseHeader(Cookie.java:178)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.inversoft.rest.ClientResponse.setHeaders(ClientResponse.java:129)
	at com.inversoft.rest.RESTClient.go(RESTClient.java:410)
	at io.fusionauth.api.service.identity.OpenIdConnectIdentityProviderValidator.validateIssuer(OpenIdConnectIdentityProviderValidator.java:105)
	at io.fusionauth.api.service.identity.OpenIdConnectIdentityProviderValidator.lambda$validate$4(OpenIdConnectIdentityProviderValidator.java:66)
	at com.inversoft.validator.Validator.validate(Validator.java:1349)
	at io.fusionauth.api.service.identity.OpenIdConnectIdentityProviderValidator.lambda$validate$5(OpenIdConnectIdentityProviderValidator.java:66)
	at com.inversoft.validator.Validator.ifFalse(Validator.java:435)
	at io.fusionauth.api.service.identity.OpenIdConnectIdentityProviderValidator.validate(OpenIdConnectIdentityProviderValidator.java:65)
	at io.fusionauth.app.action.api.IdentityProviderAction.validate(IdentityProviderAction.java:134)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.primeframework.mvc.util.ReflectionUtils.invoke(ReflectionUtils.java:443)
	at org.primeframework.mvc.validation.DefaultValidationProcessor.validate(DefaultValidationProcessor.java:77)
	at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:44)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.security.DefaultSecurityWorkflow.perform(DefaultSecurityWorkflow.java:79)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.parameter.DefaultPostParameterWorkflow.perform(DefaultPostParameterWorkflow.java:49)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.content.DefaultContentWorkflow.perform(DefaultContentWorkflow.java:74)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:58)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:92)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:50)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:119)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:65)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.cors.CORSFilter.doFilter(CORSFilter.java:171)
	at org.primeframework.mvc.cors.CORSRequestWorkflow.perform(CORSRequestWorkflow.java:63)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.workflow.DefaultMVCWorkflow.perform(DefaultMVCWorkflow.java:108)
	at org.primeframework.mvc.PrimeMVCRequestHandler.handle(PrimeMVCRequestHandler.java:73)
	at io.fusionauth.http.server.HTTPWorker.run(HTTPWorker.java:50)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

So the problem is with the provider already declared. 
If a discover URL no longer works. This shouldn't block all other providers.

**Comment by konvergence** [comment]
We discovered that the real problem was with the **jwks_uri** information returned by the **<issuer>/.well-known/openid-configuration**
The **jwks_uri** URL was protected.

But this should not block other providers declared

**Comment by robotdan** [comment]
Thanks @konvergence we'll dig into this one, appreciate you reporting it.

**Comment by konvergence** [comment]
Is there a way to have more detailed logs ?

**Comment by konvergence** [comment]
Hello, the issue is more  linked to the Cookie

https://github.com/inversoft/restify/blob/master/src/main/java/com/inversoft/http/Cookie.java

**Comment by konvergence** [comment]
I create an issue on https://github.com/inversoft/restify/issues/11

**Comment by konvergence** [comment]
We finally found the reason.
The url /well-known/openid-configuration gave a cookie with a ; at the end of its value. This is not tolerated by the restify library.

**Comment by konvergence** [comment]
Thanks

**Comment by mooreds** [comment]
Let's leave this bug open even though the fix is in the inversoft repo.

**Comment by Jank1310** [comment]
I got a similar error in version 1.51.2.
The configured issuer url is down which blocks updates to the configured provider.

```
fusionauth-1  | java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "name" is null
fusionauth-1  | 	at com.inversoft.http.Cookie.addAttribute(Cookie.java:192)
fusionauth-1  | 	at com.inversoft.http.Cookie.fromResponseHeader(Cookie.java:178)
fusionauth-1  | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
fusionauth-1  | 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
fusionauth-1  | 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
fusionauth-1  | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
fusionauth-1  | 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
fusionauth-1  | 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
fusionauth-1  | 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
fusionauth-1  | 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
fusionauth-1  | 	at com.inversoft.rest.ClientResponse.setHeaders(ClientResponse.java:129)
fusionauth-1  | 	at com.inversoft.rest.RESTClient.go(RESTClient.java:410)
fusionauth-1  | 	at io.fusionauth.api.service.identity.OpenIdConnectIdentityProviderHelper.resolveOpenIDConnectEndpoints(OpenIdConnectIdentityProviderHelper.java:80)
fusionauth-1  | 	at io.fusionauth.api.service.cache.IdentityProviderCacheLoader.retrieveAllAndResolveOpenIDConnectEndpoints(IdentityProviderCacheLoader.java:73)
fusionauth-1  | 	at io.fusionauth.api.service.cache.IdentityProviderCacheLoader.internalLoad(IdentityProviderCacheLoader.java:53)
fusionauth-1  | 	at com.inversoft.cache.BaseCacheLoader.load(BaseCacheLoader.java:21)
fusionauth-1  | 	at io.fusionauth.api.service.cache.IdentityProviderCacheLoader.run(IdentityProviderCacheLoader.java:48)
fusionauth-1  | 	at com.inversoft.scheduler.InjectableRunnable.run(InjectableRunnable.java:56)
fusionauth-1  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
fusionauth-1  | 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
fusionauth-1  | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
fusionauth-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
fusionauth-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
fusionauth-1  | 	at java.base/java.lang.Thread.run(Thread.java:833)
fusionauth-1  | 2024-12-18 01:07:49.954 PM ERROR com.inversoft.scheduler.LogAndRetainFailureHandler - The scheduled service [class io.fusionauth.api.service.cache.IdentityProviderCacheLoader] failed AGAIN! The service will still continue to run, but we are going to stop logging the errors.
```

**Comment by robotdan** [comment]
Is this a duplicate of this issue? 
- https://github.com/FusionAuth/fusionauth-issues/issues/2978

And perhaps the same error described here?
- https://github.com/inversoft/restify/issues/11

I think this will be solved via this PR and then via this GH issue for FusionAuth:
- https://github.com/inversoft/restify/pull/14
- https://github.com/FusionAuth/fusionauth-issues/issues/2978

If that all looks correct, can I close this one out?

**Comment by konvergence** [comment]
Yes it was related to others
