### ISSUE TITLE
Got Exception While Installation named as "com.google.inject.ProvisionException"

### ISSUE THREAD

**Issue by pushoo-sharma** [FusionAuth/fusionauth-issues#291]
### Description

**Before Starting FusionAuth v 1.8.1**

```
-- Integrations
INSERT INTO integrations(data)
  VALUES ('{}');
.  Cause: java.sql.SQLSyntaxErrorException: FUNCTION fusionauth.TO_BASE64 does not exist
        at org.apache.ibatis.jdbc.ScriptRunner.executeFullScript(ScriptRunner.java:133)
        at org.apache.ibatis.jdbc.ScriptRunner.runScript(ScriptRunner.java:108)
        at com.inversoft.maintenance.db.SQLExecutor.executeSQLScriptWithError(SQLExecutor.java:43)
        at com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService.createSchema(JDBCMaintenanceModeDatabaseService.java:160)
        at com.inversoft.maintenance.action.MaintenanceModeDatabaseConfigurationAction.post(MaintenanceModeDatabaseConfigurationAction.java:122)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

```

**When Starting FusionAuth**

A series of error

```
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NullPointerException
  at io.fusionauth.api.primeframework.FusionAuthMVCConfiguration.<init>(FusionAuthMVCConfiguration.java:40)
  while locating io.fusionauth.api.primeframework.FusionAuthMVCConfiguration
  at io.fusionauth.app.guice.FusionAuthModule.configure(FusionAuthModule.java:95)
  while locating org.primeframework.mvc.config.MVCConfiguration
    for the 2nd parameter of io.fusionauth.app.primeframework.FusionAuthObjectMapperProvider.<init>(FusionAuthObjectMapperProvider.java:21)
  while locating io.fusionauth.app.primeframework.FusionAuthObjectMapperProvider
  at io.fusionauth.app.guice.FusionAuthContentModule.configure(FusionAuthContentModule.java:16) (via modules: io.fusionauth.app.guice.FusionAuthModule -> com.google.inject.util.Modules$OverrideModule -> io.fusionauth.app.guice.FusionAuthContentModule)
  while locating com.fasterxml.jackson.databind.ObjectMapper
    for the 1st parameter of io.fusionauth.api.service.system.ScriptEngineConfiguration.<init>(ScriptEngineConfiguration.java:26)
  while locating io.fusionauth.api.service.system.ScriptEngineConfiguration
    for the 1st parameter of io.fusionauth.api.service.cache.LambdaCacheLoader.<init>(LambdaCacheLoader.java:32)
  while locating io.fusionauth.api.service.cache.LambdaCacheLoader
    for the 8th parameter of io.fusionauth.api.service.cache.FusionAuthCacheFactory.<init>(FusionAuthCacheFactory.java:56)
  while locating io.fusionauth.api.service.cache.FusionAuthCacheFactory
  while locating com.inversoft.cache.CacheFactory annotated with @com.google.inject.internal.Element(setName=,uniqueId=137, type=MULTIBINDER, keyType=)
  while locating java.util.Set<com.inversoft.cache.CacheFactory>
```

**My Fusion Auth properties file look like this.**

```
#
# Copyright (c) 2018, FusionAuth, All Rights Reserved
#

#------------------------------------------------------------------------------
# Database
# - Specify the URL and credentials for your database here
# - Required on each node running FusionAuth App webservice
#------------------------------------------------------------------------------
database.url=jdbc:mysql://localhost:3306/fusionauth?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
database.username=fusionauth
database.password=1234

#------------------------------------------------------------------------------
# Database Encoding Validation for MySQL
# - This value is ignored if using PostgreSQL
# - Disable (set to false) only if you understand the MySQL limitations not using 'utf8mb4' character sets.
#------------------------------------------------------------------------------
database.enforce-utf8mb4=true

#------------------------------------------------------------------------------
# fusionauth-search
# - Required on each node running FusionAuth Search
#------------------------------------------------------------------------------
fusionauth-search.transport-port=9020
fusionauth-search.http-port=9021
fusionauth-search.memory=256M
fusionauth-search.additional-java-args=

# Special values include: _local_, _site_. Values can be combined in a comma separated list.
fusionauth-search.hosts=_local_

# Specify the location of your FusionAuth Search servers. Multiple values may be specified using a comma separator.
# This configuration is used by ElasticSearch to configure clustering. The specified port should be the configured value
# for 'fusionauth-search.transport-port'.
#
# Single host example: localhost:9020
# Multiple hosts example: localhost:9020,192.168.1.42:9020
fusionauth-search.servers=localhost:9020

# Specify the full path to the ElasticSearch data directory. This defaults to /usr/local/fusionauth/data/search/esv6
# on Linux/Unix and %FUSIONAUTH_HOME%\data\search\esv6 on Windows if not specified
fusionauth-search.data-directory=

#------------------------------------------------------------------------------
# fusionauth-app
# - Required on each node running FusionAuth App webservice
#------------------------------------------------------------------------------

# Optionally specify an addressable URL or IP address to access this node from other FusionAuth nodes.
# - In most cases this should be left empty and it will be determined at runtime.
# - Ideally this is a site local IP address that is not publicly routable but accessible from other FusionAuth nodes.
fusionauth-app.public-url=

# Specify the location of your FusionAuth Search servers. Multiple values may be specified using a comma separator.
# This configuration is used by FusionAuth App to connect to the ElasticSearch nodes. The specified port should be the
# configured value for 'fusionauth-search.http-port'.
#
# Single host example: http://localhost:9021
# Multiple hosts example: http://localhost:9021,http://192.168.1.42:9021
fusionauth-app.search-servers=http://localhost:9200

# Specify the management and HTTP ports for Tomcat
fusionauth-app.management-port=9010
fusionauth-app.http-port=9011
fusionauth-app.https-port=9013
fusionauth-app.ajp-port=9019

# Specify the memory size here. You can use M for megabytes and G for gigabytes
fusionauth-app.memory=256M

# Specify any additional JVM arguments here
fusionauth-app.additional-java-args=
```

**Comment by robotdan** [comment]
What version of MySQL are you running? 

`TO_BASE64` was added in version `5.6` and `5.7.9` is the minimum version required. 

https://fusionauth.io/docs/v1/tech/installation-guide/system-requirements

**Comment by robotdan** [comment]
Closing this one out, if you're running MySQL version 5.6 or newer and you see this exception let me know.
