### ISSUE TITLE
[Bug]: Latest docker-compose.yml and .env will cause maintenance mode failure

### ISSUE THREAD

**Issue by anphex** [FusionAuth/fusionauth-issues#2923]
### What happened?

I tried starting the docker compose setup by using:
- the quick install as described on https://fusionauth.io/download
- the slightly longer install as described on https://fusionauth.io/docs/quickstarts/5-minute-docker

Deploying variants:
docker-compose
docker compose (after updating to docker 27. because I thought my compose-variant was incompatible)
portainer stack

Whats' weird, all containers show a big, green "healthy" flag and show not irregularities in the logs.
![image](https://github.com/user-attachments/assets/e2eb4209-762b-4187-bf5f-1b45d4c9b7a4)
![image](https://github.com/user-attachments/assets/9da78145-7997-4e34-a9d2-877b0f4b5d55)
![image](https://github.com/user-attachments/assets/d3dc9cbc-e7fd-4eaf-94a2-0ddf77052eda)

Elasticsearch is reachable on localhost:9200 too.

Edit: I scrolled up in the FusionApp Container logs:
```

> 	... 6 common frames omitted
> 
> Caused by: java.net.NoRouteToHostException: No route to host
> 
> 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
> 
> 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
> 
> 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
> 
> 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
> 
> 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
> 
> 	at java.base/java.net.Socket.connect(Socket.java:751)
> 
> 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
> 
> 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
> 
> 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:136)
> 
> 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262)
> 
> 	... 13 common frames omitted
> 
> 2024-11-14 07:48:21.295 PM INFO  io.fusionauth.api.configuration.DefaultFusionAuthConfiguration - Loading FusionAuth configuration file [/usr/local/fusionauth/config/fusionauth.properties]
> 
> 2024-11-14 07:48:21.295 PM INFO  io.fusionauth.api.configuration.DefaultFusionAuthConfiguration - Set property [fusionauth-app.url] set to [http://fusionauth:9011] using configured value.
> 
> 2024-11-14 07:48:21.296 PM INFO  com.inversoft.configuration.BasePropertiesFileInversoftConfiguration - 
> 
>   - Overriding default value of property [database.mysql.enforce-utf8mb4] with value [true]
> 
>   - Overriding default value of property [FUSIONAUTH_APP_RUNTIME_MODE] with value [development]
> 
>   - Overriding default value of property [SEARCH_TYPE] with value [elasticsearch]
> 
> 2024-11-14 07:48:21.340 PM INFO  com.inversoft.maintenance.MaintenanceModePoller - Poller started to Wait for configuration to be completed.
> 
> 2024-11-14 07:48:21.340 PM INFO  io.fusionauth.app.primeframework.FusionHTTPContextAuthSetup - Initializing the FusionAuth HTTP Context.
> 
> 2024-11-14 07:48:21.343 PM INFO  org.primeframework.mvc.PrimeMVCRequestHandler - Initializing Prime
> 
> 2024-11-14 07:48:21.343 PM INFO  org.primeframework.mvc.PrimeMVCRequestHandler - Initializing Prime
> 
> 2024-11-14 07:48:21.343 PM INFO  io.fusionauth.http.server.HTTPServer - Starting the HTTP server. Buckle up!
> 
> 2024-11-14 07:48:21.345 PM INFO  io.fusionauth.http.server.HTTPServer - HTTP server listening on port [9011]
> 
> 2024-11-14 07:48:21.345 PM INFO  io.fusionauth.http.server.HTTPServer - HTTP server started successfully
> 
> 2024-11-14 07:48:21.345 PM INFO  io.fusionauth.http.server.HTTPServer - Starting the HTTP server. Buckle up!
> 
> 2024-11-14 07:48:21.345 PM INFO  io.fusionauth.http.server.HTTPServer - HTTP server listening on port [9012]
> 
> 2024-11-14 07:48:21.345 PM INFO  io.fusionauth.http.server.HTTPServer - HTTP server started successfully
> 
> Starting fusionauth-app...
> 
>   --> Logging to /usr/local/fusionauth/logs/fusionauth-app.log
> 
> 2024-11-14 07:51:00.932 PM INFO  io.fusionauth.api.configuration.DefaultFusionAuthConfiguration - Loading FusionAuth configuration file [/usr/local/fusionauth/config/fusionauth.properties]
> 
> 2024-11-14 07:51:00.944 PM INFO  io.fusionauth.api.configuration.DefaultFusionAuthConfiguration - Set property [fusionauth-app.url] set to [http://fusionauth:9011] using configured value.
> 
> 2024-11-14 07:51:00.945 PM INFO  com.inversoft.configuration.BasePropertiesFileInversoftConfiguration - 
> 
>   - Overriding default value of property [database.mysql.enforce-utf8mb4] with value [true]
> 
>   - Overriding default value of property [FUSIONAUTH_APP_RUNTIME_MODE] with value [development]
> 
>   - Overriding default value of property [SEARCH_TYPE] with value [elasticsearch]
> 
> 2024-11-14 07:51:00.967 PM INFO  io.fusionauth.api.configuration.DefaultFusionAuthConfiguration - Loading FusionAuth configuration file [/usr/local/fusionauth/config/fusionauth.properties]
> 
> 2024-11-14 07:51:00.967 PM INFO  io.fusionauth.api.configuration.DefaultFusionAuthConfiguration - Set property [fusionauth-app.url] set to [http://fusionauth:9011] using configured value.
> 
> 2024-11-14 07:51:00.968 PM INFO  com.inversoft.configuration.BasePropertiesFileInversoftConfiguration - 
> 
>   - Overriding default value of property [database.mysql.enforce-utf8mb4] with value [true]
> 
>   - Overriding default value of property [FUSIONAUTH_APP_RUNTIME_MODE] with value [development]
> 
>   - Overriding default value of property [SEARCH_TYPE] with value [elasticsearch]
> 
> 2024-11-14 07:51:01.043 PM INFO  com.inversoft.maintenance.DefaultMaintenanceModeWorkflow - 
> 
> ---------------------------------------------------------------------------------------------------------
> 
> ---------------------------------- Entering Silent Configuration Mode -----------------------------------
> 
> ---------------------------------------------------------------------------------------------------------
> 
> 2024-11-14 07:51:01.079 PM ERROR com.inversoft.maintenance.db.DatabaseSilentModeWorkflowTask - Encountered an error while running silent mode
> 
> java.lang.IllegalStateException: Unable to capture database lock. This indicates that the database either doesn't support locks or is misconfigured.
> 
> 	at com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService.lockDatabase(JDBCMaintenanceModeDatabaseService.java:322)
> 
> 	at com.inversoft.maintenance.db.DatabaseSilentModeWorkflowTask.perform(DatabaseSilentModeWorkflowTask.java:43)
> 
> 	at com.inversoft.maintenance.DefaultMaintenanceModeWorkflow.performSilentConfiguration(DefaultMaintenanceModeWorkflow.java:47)
> 
> 	at com.inversoft.maintenance.BaseMaintenanceModePrimeMain.modules(BaseMaintenanceModePrimeMain.java:70)
> 
> 	at org.primeframework.mvc.BasePrimeMain.hup(BasePrimeMain.java:69)
> 
> 	at org.primeframework.mvc.BasePrimeMain.start(BasePrimeMain.java:100)
> 
> 	at io.fusionauth.app.FusionAuthMain.main(FusionAuthMain.java:27)
> 
> Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
> 
> 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:358)
> 
> 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
> 
> 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273)
> 
> 	at org.postgresql.Driver.makeConnection(Driver.java:446)
> 
> 	at org.postgresql.Driver.connect(Driver.java:298)
> 
> 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
> 
> 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
> 
> 	at com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService.lockDatabase(JDBCMaintenanceModeDatabaseService.java:304)
> 
> 	... 6 common frames omitted
> 
> Caused by: java.net.NoRouteToHostException: No route to host
> 
> 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
> 
> 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
> 
> 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
> 
> 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
> 
> 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
> 
> 	at java.base/java.net.Socket.connect(Socket.java:751)
> 
> 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
> 
> 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
> 
> 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:136)
> 
> 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262)
> 
> 	... 13 common frames omitted
> 
> 2024-11-14 07:51:01.223 PM INFO  io.fusionauth.api.configuration.DefaultFusionAuthConfiguration - Loading FusionAuth configuration file [/usr/local/fusionauth/config/fusionauth.properties]
> 
> 2024-11-14 07:51:01.223 PM INFO  io.fusionauth.api.configuration.DefaultFusionAuthConfiguration - Set property [fusionauth-app.url] set to [http://fusionauth:9011] using configured value.
> 
> 2024-11-14 07:51:01.224 PM INFO  com.inversoft.configuration.BasePropertiesFileInversoftConfiguration - 
> 
>   - Overriding default value of property [database.mysql.enforce-utf8mb4] with value [true]
> 
>   - Overriding default value of property [FUSIONAUTH_APP_RUNTIME_MODE] with value [development]
> 
>   - Overriding default value of property [SEARCH_TYPE] with value [elasticsearch]
> 
> 2024-11-14 07:51:01.307 PM INFO  com.inversoft.maintenance.MaintenanceModePoller - Poller started to Wait for configuration to be completed.
> 
> 2024-11-14 07:51:01.308 PM INFO  io.fusionauth.app.primeframework.FusionHTTPContextAuthSetup - Initializing the FusionAuth HTTP Context.
> 
> 2024-11-14 07:51:01.312 PM INFO  org.primeframework.mvc.PrimeMVCRequestHandler - Initializing Prime
> 
> 2024-11-14 07:51:01.312 PM INFO  org.primeframework.mvc.PrimeMVCRequestHandler - Initializing Prime
> 
> 2024-11-14 07:51:01.312 PM INFO  io.fusionauth.http.server.HTTPServer - Starting the HTTP server. Buckle up!
> 
> 2024-11-14 07:51:01.315 PM INFO  io.fusionauth.http.server.HTTPServer - HTTP server listening on port [9011]
> 
> 2024-11-14 07:51:01.316 PM INFO  io.fusionauth.http.server.HTTPServer - HTTP server started successfully
> 
> 2024-11-14 07:51:01.316 PM INFO  io.fusionauth.http.server.HTTPServer - Starting the HTTP server. Buckle up!
> 
> 2024-11-14 07:51:01.316 PM INFO  io.fusionauth.http.server.HTTPServer - HTTP server listening on port [9012]
> 
> 2024-11-14 07:51:01.316 PM INFO  io.fusionauth.http.server.HTTPServer - HTTP server started successfully
> 
> 

```
      
I am slightly confused. Shouldn't it work out of the box since it's using its dedicated internal docker networks?

### Version

latest community version as of 14th Nov 2024

**Comment by mooreds** [comment]
hi @anphex . It should work. I just tried to replicate the issue with the instructions at fusionauth.io/download and was unable to do so.

Here's my docker version:

```
% docker -v
Docker version 27.3.1, build ce12230
```

And I'm on MacOS Sequoia.

Can you share more information about where you are running docker and the version you are using?

**Comment by anphex** [comment]
Hi and thank you for your response! I seem to have a similar issue with another compose that involves postgres/port 5432. So it seems the issue is on my, the users side. I will investigate further for errors on my system. Thank you for the verification!

**Comment by anphex** [comment]
I just want to add my solution for anyone trying to Deploy it on a Virtualmin Managed Server. I do not remember changing any config related to FirewallD and docker, so I think the flaw is by design from Virtualmin. Here is the solution achieved with the help of Claude Sonnet 3.5 November edition:

> The core issue was a conflict between Docker's network management and firewalld zones. Here's what happened:
> 
> The main error was:
> 
> CopyFailed to program NAT chain: ZONE_CONFLICT: 'docker0' already bound to 'trusted'
> The problem occurred because:
> 
> Docker manages its own networking and creates its own firewall rules
> We had accidentally assigned the docker0 interface to the trusted zone in firewalld
> This created a conflict because the same network interface (docker0) was being managed by two different systems
> 
> It's like having two traffic cops trying to direct traffic at the same intersection - they'll conflict with each other!
> The fix involved:
> 
> Removing the docker0 interface from the trusted zone
> Cleaning up the Docker network configurations
> Letting Docker manage its own networking through its default docker zone
> 
> Best practices going forward:
> 
> Let Docker manage its own networking through the docker zone
> Don't manually assign Docker's interfaces to other firewalld zones
> If you need to add specific rules, add them to the docker zone rather than trusted
> 
> This is why it started working on the clean test network we created - it didn't have any conflicting zone assignments. The solution ensured that only one system (Docker) was managing the container networking, removing the conflict.

**Comment by mooreds** [comment]
@anphex Thanks so much for sharing your fix! Glad you got it sorted out.
