### ISSUE TITLE
Android SDK SSL Handshake Error on login

### ISSUE THREAD

**Issue by DaveInAus** [FusionAuth/fusionauth-issues#2930]
### Description 
When using the FusionAuth Android SDK one receives a `javax.net.ssl.SSLHandshakeException: Connection closed by peer` on the first attempt of 
`val authState: FusionAuthState = AuthorizationManager.oAuth(this@TokenActivity)
                    .handleRedirect(intent)` when using https

This can be recreated by using the FusionAuth Android SDK Changebank example

### Observed versions
1.53.3

### Steps to reproduce
1. Download the Android SDK Changebank example
2. Setup a FusionAuth Instance on Ubuntu with https on port 9013
3. Open the application on an Android device and login

### Expected behavior
should not generate an SSL handshake error on login

### Platform
(Please complete the following information)
 - Device: Android
 - OS: Android
 - Browser + version [chrome]
 - Database [MySQL | PostgresSQL] & and version

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
The application does work in docker on http port 9011

**Comment by ColinFrick** [comment]
Hi @DaveInAus 

Thanks for reporting this issue. How are you setting up https for FusionAuth?

**Comment by DaveInAus** [comment]
Hi @ColinFrick 

I've had further issues with FusionAuth where it totally locks up with the following error:

`
2024-11-27 05:27:09.189 AM ERROR io.fusionauth.http.server.HTTPServerThread - An exception was thrown during processing
javax.net.ssl.SSLException: Unrecognized record version (D)TLS-0.0 , plaintext connection?
	at java.base/sun.security.ssl.SSLEngineInputRecord.bytesInCompletePacket(SSLEngineInputRecord.java:97)
	at java.base/sun.security.ssl.SSLEngineInputRecord.bytesInCompletePacket(SSLEngineInputRecord.java:64)
	at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:612)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:506)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:482)
	at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:679)
	at io.fusionauth.http.server.HTTPS11Processor.decrypt(HTTPS11Processor.java:393)
	at io.fusionauth.http.server.HTTPS11Processor.read(HTTPS11Processor.java:199)
	at io.fusionauth.http.server.HTTPServerThread.read(HTTPServerThread.java:338)
	at io.fusionauth.http.server.HTTPServerThread.run(HTTPServerThread.java:148)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "I/O dispatcher 7"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Thread-2"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "I/O dispatcher 4"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "HTTP Server Thread"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "HTTP Server Thread"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "I/O dispatcher 3"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "I/O dispatcher 5"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-2-thread-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "I/O dispatcher 2"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "I/O dispatcher 1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "I/O dispatcher 8"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "I/O dispatcher 6"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "HTTP Server Thread"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "HttpClient-1-SelectorManager"
`

**Comment by ColinFrick** [comment]
Hi @DaveInAus 

I was not able to reproduce the `SSLHandshakeException` error.
How do you generate the Let's Encrypt certificate? Are you using the `fusionauth-app.https.*` settings to set up HTTPS?

Could you post your docker run / docker-compose file?

This shouldn't apply to you, but to get self-signed certificates to work under Android, their CA must be added to the network security config: https://developer.android.com/privacy-and-security/security-config

It locks up the FusionAuth server right? And not the android app?

**Comment by DaveInAus** [comment]
Hi @ColinFrick 

I seem to get these errors below in the FusionAuth log on occasion and then lock FusionAuth up- It could have been attributed to the fact that I had a GoDaddy wildcard and Lets Encrypt bound to the same public IP even though the GoDaddy wildcard SSL was on IIS and the Lets Encrypt was on Ubuntu on port 9013. I've removed the wildcard SSL and haven't had a FusionAuth lockup again so will monitor to see if this has resolved the FusionAuth lockup issue.

`
2024-11-28 03:28:35.627 PM ERROR io.fusionauth.http.server.HTTPServerThread - An exception was thrown during processing
javax.net.ssl.SSLException: Unrecognized record version (D)TLS-0.0 , plaintext connection?
	at java.base/sun.security.ssl.SSLEngineInputRecord.bytesInCompletePacket(SSLEngineInputRecord.java:97)
	at java.base/sun.security.ssl.SSLEngineInputRecord.bytesInCompletePacket(SSLEngineInputRecord.java:64)
	at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:612)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:506)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:482)
	at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:679)
	at io.fusionauth.http.server.HTTPS11Processor.decrypt(HTTPS11Processor.java:393)
	at io.fusionauth.http.server.HTTPS11Processor.read(HTTPS11Processor.java:199)
	at io.fusionauth.http.server.HTTPServerThread.read(HTTPServerThread.java:338)
	at io.fusionauth.http.server.HTTPServerThread.run(HTTPServerThread.java:148)
`

**Comment by DaveInAus** [comment]
Hi @ColinFrick 

When using a Lets Encrypt Certificate do the changes below need to be made?

i.e. Your certificate authority does not ship with the version of Java that FusionAuth uses.

[Link](https://fusionauth.io/docs/operate/secure-and-monitor/securing)

`
Custom Certificate Authority

FusionAuth ships with the default cacerts file from OpenJDK, which contains a list of root certificate authorities. There are times when you need to add a certificate authority to this file. This might occur if:

You are using a self signed certificate.
Your certificate authority does not ship with the version of Java that FusionAuth uses.
`

**Comment by DaveInAus** [comment]
Established that this is not an Android issue but a FusionAuth lockup issue - raising as a separated issue
