### ISSUE TITLE
Unexpected "Options" Fields Display in Test Area of Managed Domains

### ISSUE THREAD

**Issue by sanjesh1000** [FusionAuth/fusionauth-issues#2958]
**Description**
When navigating to Settings > Identity Provider > Add OpenID Connect, the "Options" fields sometimes appear incorrectly in the Test Area of the Managed Domains section. This intermittent issue occurs when accessing Managed Domains via the Options menu.

**Observed Versions**
FusionAuth Cloud version: 1.54.0

**Affects Versions**
1.54.0
Other versions: Unknown

**Steps to Reproduce**
Log in to FusionAuth and navigate to Settings > Identity Provider > Add OpenID Connect.
From the Options menu, navigate to Managed Domains.
Observe the Text Area under Managed Domains.
Notice that "Options" related fields are incorrectly displayed in this section.
Expected Behavior
The "Options" fields should not be visible in the Test Area of the Managed Domains section. Only fields related to Managed Domains should appear.

**Screenshots**
(Add the screenshot showing the issue here)
<img width="790" alt="add-openId-connect" src="https://github.com/user-attachments/assets/87012453-50b7-4aae-9e8e-251b101c37ea" />

**Platform**
Device: Desktop
OS: Windows 10 Enterprise
Browser: Google Chrome Version 119.0.0.1
Community Guidelines

**Additional Context**
This issue disrupts the workflow for configuring Identity Providers and may lead to user confusion during Managed Domain setup.

**Comment by andrewpai** [comment]
Hi @sanjesh1000, we are unable to reproduce this behavior on various browser and OS combinations. Could you try a couple of things for us?
* Reloading the page with Ctrl-Shift-R, bypassing the browser cache?
* Looking at your console output with Ctrl-Shift-J, to see if there are any JavaScript error messages?

Thanks,
Andy

**Comment by sanjesh1000** [comment]
I can still re-generate it on Chrome & Brave browsers.

Steps to reproduce:
1. login > Settings > Identity Providers >Add OpenID Connect (new) > Click on Options > then click on Managed domains
2. Now again clock on Options then Refresh the browser
3. now click on the Managed Domains

Error on Console 
<img width="743" alt="idp_issue_err" src="https://github.com/user-attachments/assets/02083745-ab87-40e8-8937-6efe1ec4fa89" />

**Comment by mooreds** [comment]
I see this on 1.56.0 on sandbox.fusionauth.io using the above replication steps on Chrome 134.0.6998.89 on my mac.

Here's the console message.

It appears whether I cmd-R or cmd-shift-R.

Here's the error message in my console.

```
PrimeElement.js:37 Uncaught TypeError: Cannot read properties of null (reading 'nodeType')
    at new l (PrimeElement.js:37:34)
    at l.value (PrimeElement.js:84:58)
    at new FusionAuth.UI.TextEditor (TextEditor.js?version=1.56.0:25:41)
    at FusionAuth.Admin.IdentityProviderForm._handleTabSelect (IdentityProviderForm.js?version=1.56.0:300:30)
    at t.value (Tabs.js:207:24)
    at t.value (Tabs.js:366:14)
l @ PrimeElement.js:37
value @ PrimeElement.js:84
FusionAuth.UI.TextEditor @ TextEditor.js?version=1.56.0:25
_handleTabSelect @ IdentityProviderForm.js?version=1.56.0:300
value @ Tabs.js:207
value @ Tabs.js:366
IdentityProviderForm.js?version=1.56.0:293 Uncaught TypeError: Cannot read properties of undefined (reading 'render')
    at FusionAuth.Admin.IdentityProviderForm._handleTabSelect (IdentityProviderForm.js?version=1.56.0:293:12)
    at t.value (Tabs.js:207:24)
    at t.value (Tabs.js:366:14)
_handleTabSelect @ IdentityProviderForm.js?version=1.56.0:293
value @ Tabs.js:207
value @ Tabs.js:366
```
