### ISSUE TITLE
Database Upgrade to 1.8.0-RC.1 fails

### ISSUE THREAD

**Issue by gmpreussner** [FusionAuth/fusionauth-issues#349]
### Description 
When upgrading FusionAuth to the latest 1.8.0-RC.1 via the fast-path script on CentOS 7, the database migration fails with the following exception:
```
Cause: java.sql.SQLSyntaxErrorException: Table 'themes' already exists
        at org.apache.ibatis.jdbc.ScriptRunner.executeFullScript(ScriptRunner.java:133)
        at org.apache.ibatis.jdbc.ScriptRunner.runScript(ScriptRunner.java:108)
        at com.inversoft.maintenance.db.SQLExecutor.executeSQLScriptWithError(SQLExecutor.java:43)
        at com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService.upgrade(JDBCMaintenanceModeDatabaseService.java:332)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more
Caused by: java.sql.SQLSyntaxErrorException: Table 'themes' already exists
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:781)
        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:666)
        at org.apache.ibatis.jdbc.ScriptRunner.executeStatement(ScriptRunner.java:236)
        at org.apache.ibatis.jdbc.ScriptRunner.executeFullScript(ScriptRunner.java:128)
        ... 7 more
```

### Steps to reproduce

1. On a CentOS 7 with an existing FusionAuth installation (unfortunately, I don't know the previously installed version), run the update script: `sh -c "curl -fsSL https://raw.githubusercontent.com/FusionAuth/fusionauth-install/master/install.sh | sh"`
2. Navigate to the FusionAuth web page
3. Click the "Submit" button on the database upgrade page

Result: FusionAuth app service crashes; after restarting the service, maintenance page is shown again with the option to upgrade the database.

### Expected behavior
Database upgrade completes successfully, and FusionAuth is functional again.

### Platform
- OS: CentOS 7.7.1908
- Browser: Firefox 69.0.3
- Database: MariaDB 5.5.64

**Comment by robotdan** [comment]
Probably related 
https://github.com/FusionAuth/fusionauth-issues/issues/327

**Comment by gmpreussner** [comment]
I can confirm that the root issue is #327. The exception posted in this issue report is thrown only after the initial upgrade attempt failed, and the database is in an inconsistent state.

MariaDB 5.5.x is no longer supported with the latest upgrades as it lacks the JSON specific SQL syntax that is now required. MariaDB 10.x is currently also not supported, because its JSON syntax is slightly different from MySQL.

I reverted my installation to FusionAuth 1.7.2 from a backup. I am planning to migrate my database to PostgreSQL or MySQL and perform the upgrade afterwards.
