### ISSUE TITLE
Error on startup after upgrading to 1.12.0 using RPM packages

### ISSUE THREAD

**Issue by colingm** [FusionAuth/fusionauth-issues#408]
### Description
I was trying to upgrade from version 1.11.0 to 1.12.0 using RPM packages today and the application was unable to startup and I got what a NullPointerException in the logs. I was able to rollback to 1.11.0 and it started up just fine so not sure what is going on. I have included logs from both fusionauth-app and fusionauth-search below

### FusionAuth App
```
16-Dec-2019 16:32:42.738 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
16-Dec-2019 16:32:43.294 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-9011"]
16-Dec-2019 16:32:43.412 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
16-Dec-2019 16:32:43.429 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["https-jsse-nio-9013"]
16-Dec-2019 16:32:44.305 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
16-Dec-2019 16:32:44.318 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-9019"]
16-Dec-2019 16:32:44.324 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
16-Dec-2019 16:32:44.331 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 2164 ms
16-Dec-2019 16:32:44.337 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
16-Dec-2019 16:32:44.337 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.43
16:32:47,807 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
16:32:47,807 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
16:32:47,807 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/usr/local/fusionauth/fusionauth-app/web/WEB-INF/lib/fusionauth-app-1.12.0.jar!/logback.xml]
16:32:47,820 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@b6bd669 - URL [jar:file:/usr/local/fusionauth/fusionauth-app/web/WEB-INF/lib/fusionauth-app-1.12.0.jar!/logback.xml] is not of type file
16:32:47,855 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
16:32:47,862 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [jar:file:/usr/local/fusionauth/fusionauth-app/web/WEB-INF/lib/fusionauth-app-1.12.0.jar!/logback.xml]
16:32:47,862 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 1 minutes
16:32:47,883 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
16:32:47,885 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
16:32:47,890 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:32:47,930 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [io.fusionauth] to INFO
16:32:47,930 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [io.fusionauth] to false
16:32:47,930 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[io.fusionauth]
16:32:47,930 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.primeframework] to INFO
16:32:47,931 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.primeframework] to false
16:32:47,931 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[org.primeframework]
16:32:47,931 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.inversoft.migration] to INFO
16:32:47,931 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [com.inversoft.migration] to false
16:32:47,931 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[com.inversoft.migration]
16:32:47,931 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.inversoft.maintenance] to INFO
16:32:47,931 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [com.inversoft.maintenance] to false
16:32:47,931 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[com.inversoft.maintenance]
16:32:47,931 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [io.fusionauth.api.plugin.importer] to DEBUG
16:32:47,931 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [io.fusionauth.api.plugin.importer] to false
16:32:47,931 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [FILE]. Did you define it below instead of above in the configuration file?
16:32:47,931 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - See http://logback.qos.ch/codes.html#appender_order for more details.
16:32:47,931 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.kafka.common.utils.AppInfoParser] to ERROR
16:32:47,931 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.apache.kafka.common.utils.AppInfoParser] to false
16:32:47,931 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[org.apache.kafka.common.utils.AppInfoParser]
16:32:47,931 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.kafka.clients.consumer.ConsumerConfig] to ERROR
16:32:47,931 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.apache.kafka.clients.consumer.ConsumerConfig] to false
16:32:47,931 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[org.apache.kafka.clients.consumer.ConsumerConfig]
16:32:47,931 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.kafka.clients.producer.ProducerConfig] to ERROR
16:32:47,931 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.apache.kafka.clients.producer.ProducerConfig] to false
16:32:47,931 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[org.apache.kafka.clients.producer.ProducerConfig]
16:32:47,931 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.kafka.clients.producer.KafkaProducer] to ERROR
16:32:47,931 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.apache.kafka.clients.producer.KafkaProducer] to false
16:32:47,931 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[org.apache.kafka.clients.producer.KafkaProducer]
16:32:47,932 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.kafka.clients.NetworkClient] to ERROR
16:32:47,932 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.apache.kafka.clients.NetworkClient] to false
16:32:47,932 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[org.apache.kafka.clients.NetworkClient]
16:32:47,932 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
16:32:47,932 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
16:32:47,932 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
16:32:47,932 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@3709d4f5 - Registering current configuration as safe fallback point

Dec 16, 2019 4:32:48 PM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Dec 16, 2019 4:32:50.215 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Loading FusionAuth configuration file [/usr/local/fusionauth/fusionauth-app/apache-tomcat/../../config/fusionauth.properties]
Dec 16, 2019 4:32:50.219 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Dynamically set property [fusionauth-app.public-url] set to [http://10.3.4.9:9011]
Dec 16, 2019 4:32:50.219 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - FusionAuth Runtime Mode [Production]
Dec 16, 2019 4:32:50.452 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Loading FusionAuth configuration file [/usr/local/fusionauth/fusionauth-app/apache-tomcat/../../config/fusionauth.properties]
Dec 16, 2019 4:32:50.473 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Dynamically set property [fusionauth-app.public-url] set to [http://10.3.4.9:9011]
Dec 16, 2019 4:32:50.473 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - FusionAuth Runtime Mode [Production]
Dec 16, 2019 4:32:50 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class [io.fusionauth.app.primeframework.FusionAuthAppPrimeServletContextListener]
java.lang.VerifyError: Stack map does not match the one at exception handler 77
Exception Details:
  Location:
    com/fasterxml/jackson/databind/deser/std/StdDeserializer._parseDate(Lcom/fasterxml/jackson/core/JsonParser;Lcom/fasterxml/jackson/databind/DeserializationContext;)Ljava/util/Date; @77: astore
  Reason:
    Type 'com/fasterxml/jackson/core/JsonParseException' (current frame, stack[0]) is not assignable to 'com/fasterxml/jackson/core/exc/StreamReadException' (stack map, stack[0])
  Current Frame:
    bci: @69
    flags: { }
    locals: { 'com/fasterxml/jackson/databind/deser/std/StdDeserializer', 'com/fasterxml/jackson/core/JsonParser', 'com/fasterxml/jackson/databind/DeserializationContext' }
    stack: { 'com/fasterxml/jackson/core/JsonParseException' }
  Stackmap Frame:
    bci: @77
    flags: { }
    locals: { 'com/fasterxml/jackson/databind/deser/std/StdDeserializer', 'com/fasterxml/jackson/core/JsonParser', 'com/fasterxml/jackson/databind/DeserializationContext' }
    stack: { 'com/fasterxml/jackson/core/exc/StreamReadException' }
  Bytecode:
    0x0000000: 2bb6 0035 aa00 0000 0000 0081 0000 0003
    0x0000010: 0000 000b 0000 007a 0000 0081 0000 0081
    0x0000020: 0000 0034 0000 0041 0000 0081 0000 0081
    0x0000030: 0000 0081 0000 0071 2a2b b600 11b6 0012
    0x0000040: 2cb6 006b b02b b600 4742 a700 223a 052c
    0x0000050: 2ab4 0002 2bb6 006e 126f 03bd 0004 b600
    0x0000060: 70c0 002d 3a06 1906 b600 4c42 bb00 7159
    0x0000070: 21b7 0072 b02a 2cb6 0073 c000 71b0 2a2b
    0x0000080: 2cb6 0074 b02c 2ab4 0002 2bb6 0025 c000
    0x0000090: 71b0
  Exception Handler Table:
    bci [69, 74] => handler: 77
    bci [69, 74] => handler: 77
  Stackmap Table:
    same_frame(@56)
    same_frame(@69)
    same_locals_1_stack_item_frame(@77,Object[#365])
    append_frame(@108,Long)
    chop_frame(@117,1)
    same_frame(@126)
    same_frame(@133)

	at com.inversoft.json.JacksonModule.<init>(JacksonModule.java:39)
	at com.inversoft.search.AbstractElasticSearchSearchEngine.<clinit>(AbstractElasticSearchSearchEngine.java:36)
	at io.fusionauth.api.service.search.ElasticsearchSearchEngine$$FastClassByGuice$$8b90d228.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
	at com.inversoft.maintenance.servlet.MaintenanceModePrimeServletContextListener.contextInitialized(MaintenanceModePrimeServletContextListener.java:51)
	at io.fusionauth.app.primeframework.FusionAuthAppPrimeServletContextListener.contextInitialized(FusionAuthAppPrimeServletContextListener.java:29)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4699)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5165)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

16-Dec-2019 16:32:50.581 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
16-Dec-2019 16:32:50.581 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
Dec 16, 2019 4:32:50 PM org.apache.catalina.core.StandardContext listenerStop
SEVERE: Exception sending context destroyed event to listener instance of class [io.fusionauth.app.primeframework.FusionAuthAppPrimeServletContextListener]
java.lang.NullPointerException
	at org.primeframework.mvc.guice.GuiceBootstrap.shutdown(GuiceBootstrap.java:88)
	at org.primeframework.mvc.servlet.PrimeServletContextListener.contextDestroyed(PrimeServletContextListener.java:47)
	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4746)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5403)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

16-Dec-2019 16:32:50.710 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-9011"]
16-Dec-2019 16:32:50.735 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["https-jsse-nio-9013"]
16-Dec-2019 16:32:50.737 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-9019"]
16-Dec-2019 16:32:50.739 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 6407 ms
```

### FusionAuth Search
```
[Dec 16, 2019 4:32:44.813 PM][INFO ][o.e.n.Node               ] [] initializing ...
[Dec 16, 2019 4:32:44.900 PM][INFO ][o.e.e.NodeEnvironment    ] [WF4-dav] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [37.1gb], net total_space [39.9gb], types [rootfs]
[Dec 16, 2019 4:32:44.900 PM][INFO ][o.e.e.NodeEnvironment    ] [WF4-dav] heap size [245.5mb], compressed ordinary object pointers [true]
[Dec 16, 2019 4:32:45.062 PM][INFO ][o.e.n.Node               ] [WF4-dav] node name derived from node ID [WF4-davuRpuOGHMhpYEX8A]; set [node.name] to override
[Dec 16, 2019 4:32:45.062 PM][INFO ][o.e.n.Node               ] [WF4-dav] version[6.3.1], pid[1505], build[default/tar/eb782d0/2018-06-29T21:59:26.107521Z], OS[Linux/3.10.0-957.27.2.el7.x86_64/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_171/25.171-b11]
[Dec 16, 2019 4:32:45.062 PM][INFO ][o.e.n.Node               ] [WF4-dav] JVM arguments [-XX:+HeapDumpOnOutOfMemoryError, -XX:+DisableExplicitGC, -Dfusionauth.home.directory=/usr/local/fusionauth/fusionauth-search/elasticsearch/.., -Dfusionauth.config.directory=/usr/local/fusionauth/fusionauth-search/elasticsearch/../../config, -Dfusionauth.plugin.directory=/usr/local/fusionauth/fusionauth-search/elasticsearch/../../plugins, -Djava.awt.headless=true, -Dlog4j2.disable.jmx=true, -DfusionAuthSearchEngine87AFBG16, -Xms256M, -Xmx256M, -Des.path.home=/usr/local/fusionauth/fusionauth-search/elasticsearch, -Des.path.conf=/usr/local/fusionauth/fusionauth-search/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=tar]
[Dec 16, 2019 4:32:51.558 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [aggs-matrix-stats]
[Dec 16, 2019 4:32:51.558 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [analysis-common]
[Dec 16, 2019 4:32:51.558 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [ingest-common]
[Dec 16, 2019 4:32:51.558 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [lang-expression]
[Dec 16, 2019 4:32:51.558 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [lang-mustache]
[Dec 16, 2019 4:32:51.558 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [lang-painless]
[Dec 16, 2019 4:32:51.558 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [mapper-extras]
[Dec 16, 2019 4:32:51.559 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [parent-join]
[Dec 16, 2019 4:32:51.559 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [percolator]
[Dec 16, 2019 4:32:51.559 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [rank-eval]
[Dec 16, 2019 4:32:51.559 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [reindex]
[Dec 16, 2019 4:32:51.559 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [repository-url]
[Dec 16, 2019 4:32:51.559 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [transport-netty4]
[Dec 16, 2019 4:32:51.559 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [tribe]
[Dec 16, 2019 4:32:51.559 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [x-pack-core]
[Dec 16, 2019 4:32:51.559 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [x-pack-deprecation]
[Dec 16, 2019 4:32:51.559 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [x-pack-graph]
[Dec 16, 2019 4:32:51.559 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [x-pack-logstash]
[Dec 16, 2019 4:32:51.560 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [x-pack-ml]
[Dec 16, 2019 4:32:51.560 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [x-pack-monitoring]
[Dec 16, 2019 4:32:51.560 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [x-pack-rollup]
[Dec 16, 2019 4:32:51.560 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [x-pack-security]
[Dec 16, 2019 4:32:51.568 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [x-pack-sql]
[Dec 16, 2019 4:32:51.568 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [x-pack-upgrade]
[Dec 16, 2019 4:32:51.568 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] loaded module [x-pack-watcher]
[Dec 16, 2019 4:32:51.568 PM][INFO ][o.e.p.PluginsService     ] [WF4-dav] no plugins loaded
[Dec 16, 2019 4:32:52.263 PM][INFO ][i.n.u.i.PlatformDependent] Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
[Dec 16, 2019 4:32:56.269 PM][DEBUG][o.e.a.ActionModule       ] Using REST wrapper from plugin org.elasticsearch.xpack.security.Security
[Dec 16, 2019 4:32:56.597 PM][INFO ][i.n.u.i.PlatformDependent] Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
[Dec 16, 2019 4:32:56.629 PM][INFO ][o.e.d.DiscoveryModule    ] [WF4-dav] using discovery type [zen]
[Dec 16, 2019 4:32:57.685 PM][INFO ][o.e.n.Node               ] [WF4-dav] initialized
[Dec 16, 2019 4:32:57.685 PM][INFO ][o.e.n.Node               ] [WF4-dav] starting ...
[Dec 16, 2019 4:32:57.855 PM][INFO ][o.e.t.TransportService   ] [WF4-dav] publish_address {127.0.0.1:9020}, bound_addresses {[::1]:9020}, {127.0.0.1:9020}
[Dec 16, 2019 4:33:00.955 PM][INFO ][o.e.c.s.MasterService    ] [WF4-dav] zen-disco-elected-as-master ([0] nodes joined)[, ], reason: new_master {WF4-dav}{WF4-davuRpuOGHMhpYEX8A}{uAZHDRGJTOOyYTxlpR6ZcA}{127.0.0.1}{127.0.0.1:9020}{xpack.installed=true}
[Dec 16, 2019 4:33:00.961 PM][INFO ][o.e.c.s.ClusterApplierService] [WF4-dav] new_master {WF4-dav}{WF4-davuRpuOGHMhpYEX8A}{uAZHDRGJTOOyYTxlpR6ZcA}{127.0.0.1}{127.0.0.1:9020}{xpack.installed=true}, reason: apply cluster state (from master [master {WF4-dav}{WF4-davuRpuOGHMhpYEX8A}{uAZHDRGJTOOyYTxlpR6ZcA}{127.0.0.1}{127.0.0.1:9020}{xpack.installed=true} committed version [1] source [zen-disco-elected-as-master ([0] nodes joined)[, ]]])
[Dec 16, 2019 4:33:01.140 PM][INFO ][o.e.x.s.t.n.SecurityNetty4HttpServerTransport] [WF4-dav] publish_address {127.0.0.1:9021}, bound_addresses {[::1]:9021}, {127.0.0.1:9021}
[Dec 16, 2019 4:33:01.147 PM][INFO ][o.e.n.Node               ] [WF4-dav] started
[Dec 16, 2019 4:33:01.553 PM][WARN ][o.e.x.s.a.s.m.NativeRoleMappingStore] [WF4-dav] Failed to clear cache for realms [[]]
[Dec 16, 2019 4:33:01.578 PM][INFO ][o.e.l.LicenseService     ] [WF4-dav] license [21e9c15f-2f79-457d-b702-352cfdadf7fd] mode [basic] - valid
[Dec 16, 2019 4:33:01.588 PM][INFO ][o.e.g.GatewayService     ] [WF4-dav] recovered [1] indices into cluster_state
[Dec 16, 2019 4:33:02.048 PM][INFO ][o.e.c.r.a.AllocationService] [WF4-dav] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[fusionauth_user][3]] ...]).
```

**Comment by robotdan** [comment]
This is a bit strange, I have one theory even though it is unlikely. 

If you are able to recreate, I could give you a jar to replace with one in your class path to see if it resolves the issue. 

As a sanity check, have you modified anything with this RPM install and can you confirm it is using the version of Java installed by the RPM or FusionAuth installer?

**Comment by colingm** [comment]
@robotdan Yeah I should be able to reproduce the issue easy enough tomorrow. We haven't done anything special with the RPM install but I can double check the java version that it is using tomorrow as well.

**Comment by robotdan** [comment]
Ok, great. If you are able to recreate, do the following:

Step 1
- Stop FusionAuth App `sudo service fusionauth-app stop`
- Remove Jar `sudo rm /usr/local/fusionauth/fusionauth-app/web/WEB-INF/lib/java-client-3.6.0.jar`

Step 2
- Download this JAR https://drive.google.com/open?id=1so5SP02YxoAXn52jaEc9GQGkYXdfl_OA
- Place jar here: `/usr/local/fusionauth/fusionauth-app/web/WEB-INF/lib/`.
- Start FusionAuth App `sudo service fusionauth-app start`


Ok, that was more than 2 steps. :-)

**Comment by colingm** [comment]
@robotdan apparently 5th time is the charm, I went to reproduce the issue today after having rolled back yesterday and it actually started up just fine 😮 Sorry for the inconvenience.

**Comment by robotdan** [comment]
Thanks for the update, if it happens again, let us know.
