### ISSUE TITLE
NullPointerException on Refresh of token on React Native

### ISSUE THREAD

**Issue by karice** [FusionAuth/fusionauth-issues#414]
### Description 
Exception is thrown when trying to refresh JWT token on React Native. The issue appears to be the origin is sent as file:// per the logs Expected authority at index 7: file://

### Steps to reproduce
1. System CORS settings set to Allowed Origins: *
2. User JWT expires
3. We call api/jwt/refresh with Refresh Token
4. Origin header is set to file:// because it's mobile app running React Native
5. Exception is thrown and we failed to refresh 

### Screenshots
<img width="917" alt="Screen Shot 2019-12-18 at 8 19 52 PM" src="https://user-images.githubusercontent.com/1577871/71140877-2247ba00-21d8-11ea-8356-e0e5bed2667a.png">

### Platform
 - Device: iPhone X 
 - OS: iOS
 - React Native

### Additional context

ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown

java.lang.IllegalArgumentException: Expected authority at index 7: file://

at java.net.URI.create(URI.java:852)

at io.fusionauth.app.primeframework.CORSFilter.isSameOrigin(CORSFilter.java:609)

at io.fusionauth.app.primeframework.CORSFilter.doFilter(CORSFilter.java:220)

at io.fusionauth.app.primeframework.CORSRequestWorkflow.perform(CORSRequestWorkflow.java:48)

at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)

at io.fusionauth.app.primeframework.FusionAuthMVCWorkflow.perform(FusionAuthMVCWorkflow.java:88)

at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44)

at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50)

at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:84)

at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:59)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)

at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)

at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)

at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)

at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)

at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)

at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)

at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)

at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)

at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)

at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1775)

at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

at java.lang.Thread.run(Thread.java:748)

Caused by: java.net.URISyntaxException: Expected authority at index 7: file://

at java.net.URI$Parser.fail(URI.java:2848)

at java.net.URI$Parser.failExpecting(URI.java:2854)

at java.net.URI$Parser.parseHierarchical(URI.java:3102)

at java.net.URI$Parser.parse(URI.java:3053)

at java.net.URI.<init>(URI.java:588)

at java.net.URI.create(URI.java:850)

... 30 common frames omitted

**Comment by karice** [comment]
This is the other exception I see in the logs. 

ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown


java.lang.NullPointerException: null


at io.fusionauth.api.service.jwt.DefaultJWTService.createBaseJWT(DefaultJWTService.java:411)


at io.fusionauth.api.service.jwt.DefaultJWTService.refreshAccessToken(DefaultJWTService.java:162)


at io.fusionauth.app.action.api.jwt.RefreshAction.post(RefreshAction.java:140)


at sun.reflect.GeneratedMethodAccessor173.invoke(Unknown Source)


at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


at java.lang.reflect.Method.invoke(Method.java:498)


at org.primeframework.mvc.util.ReflectionUtils.invoke(ReflectionUtils.java:414)


at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.execute(DefaultActionInvocationWorkflow.java:79)


at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.perform(DefaultActionInvocationWorkflow.java:62)


at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)


at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:47)


at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)


at org.primeframework.mvc.security.DefaultSecurityWorkflow.perform(DefaultSecurityWorkflow.java:65)


at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)


at org.primeframework.mvc.parameter.DefaultPostParameterWorkflow.perform(DefaultPostParameterWorkflow.java:50)


at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)


at org.primeframework.mvc.content.DefaultContentWorkflow.perform(DefaultContentWorkflow.java:52)


at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)


at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:57)


at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)


at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:102)


at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)


at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:58)


at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)


at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:45)


at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)


at io.fusionauth.app.primeframework.FrontEndTenantWorkflow.perform(FrontEndTenantWorkflow.java:69)


at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)


at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:126)


at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)


at org.primeframework.mvc.workflow.StaticResourceWorkflow.perform(StaticResourceWorkflow.java:97)


at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)


at org.primeframework.mvc.parameter.RequestBodyWorkflow.perform(RequestBodyWorkflow.java:89)


at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)


at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:57)


at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)


at io.fusionauth.app.primeframework.CORSFilter.handleNonCORS(CORSFilter.java:289)


at io.fusionauth.app.primeframework.CORSFilter.doFilter(CORSFilter.java:250)


at io.fusionauth.app.primeframework.CORSRequestWorkflow.perform(CORSRequestWorkflow.java:48)


at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)


at io.fusionauth.app.primeframework.FusionAuthMVCWorkflow.perform(FusionAuthMVCWorkflow.java:88)


at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44)


at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50)


at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:84)


at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:59)


at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)


at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27)


at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)


at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)


at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)


at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)


at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)


at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)


at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)


at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)


at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)


at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)


at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)


at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1775)


at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)


at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)


at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)


at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)


at java.lang.Thread.run(Thread.java:748)

**Comment by robotdan** [comment]
Is `file://` a valid Origin for React to send? That isn't a valid URI, and I wouldn't expect it to be a valid Origin header either. 

If you send something like `file://foo/index.html` that would be ok and be handled correctly. I am not familiar with React, do you have any documentation that indicates this is a valid and normal Origin header in that world?

**Comment by karice** [comment]
It's coming from React Native which is used to build mobile applications across platforms. React Native interprets javascript components back to native components and uses a Javascript engine to run the logic for the application to achieve cross platform compatibility. There isn't an html file involved in that process. It's just javascript being interpreted and executed. 

The odd thing to me is I can execute API requests to FusionAuth for login or change password without issues from React Native and I see the same file:// origin being passed. I've setup the same process in a web page to test the FusionAuth configuration and everything works fine in the browser. It's just the React Native app that is having issues on the refresh token API call.

**Comment by robotdan** [comment]
I could potentially allow this case, but the fact that React is sending an invalid URL as an origin header makes me think this is a bug in React and not necessary something FusionAuth should account for. 

Do you know if any React Native documentation that indicates this is an expected or valid Origin header?

**Comment by karice** [comment]
I've looked around for some documentation but I haven't been able to find anything around the origin header relating to RN. 

What's the difference between the login api endpoint and the refresh token endpoint? The login API endpoint passes along the same origin and works fine.

**Comment by robotdan** [comment]
It may depend upon how you are using the endpoints, the exception that you see is coming from our CORS filter, so if the request to the Login endpoint does not end up being considered a CORS request (no origin header) it will not use the same code path. 

I'll have to do some more research and see why React is sending this type of origin header. We could fall back to doing some sort of String comparison on the Origin header since the Java `java.net.URI` class does not handle parsing `file://`.

**Comment by robotdan** [comment]
Found the Tomcat source code, they are handling `file://` - so while it is not a valid URI, the spec seems to indicate that if the Origin begins with `file://` anything is allowed. 

This will be fixed in the upcoming release. 

Thanks for reporting!

**Comment by karice** [comment]
Thanks!
