### ISSUE TITLE
Can't find application logs

### ISSUE THREAD

**Issue by prabhakarreddy1234** [FusionAuth/fusionauth-issues#448]
### Description
I setup Fusionauth on AKS. When i `exec` into the pod and navigate to `\usr\local\fusionauth\`, i can't find logs folder in there. I do see `bin`, `config`, `fusionauth-app`, `java` folder in there.

Do i need to explicitly create logs folder? or did i miss any configuration?

It would be good to allow external plugins (seq, serilog, prometheus, logstash etc) to see real time logs. It's becoming increasingly difficult to find traces and analyze performance of the app.

FusionAuth : 1.14.0
AKS : 1.15.7

**Comment by robotdan** [comment]
If you running a container in AKS the logs are written to stdout and not to a log directory. 

https://github.com/FusionAuth/fusionauth-containers/blob/master/docker/fusionauth/fusionauth-app/Dockerfile

**Comment by prabhakarreddy1234** [comment]
@robotdan  Thanks. logs are written to stdout but only when there is an exception or booting up fusion instance. I can't see the traces. 

We have serious performance issues with fusionauth login. Our login is taking approx 20 seconds for the first time and 5-10 seconds 2nd time onwards. So we want to know what is causing such delay. Dependencies are elastic search and postgres. If we can see the traces then we can identify the performance bottleneck.

Is there anyway i can set log level to `trace` and switch it back to `error` after the troubleshooting is complete ?

**Comment by robotdan** [comment]
If you have a support contract with us, we can help you debug performance issues through our support channels. 

If you want to debug on your own, you can verify you have a low latency connection to your db and your db is configured properly for the number of users you're storing in FusionAuth. You can also verify you have not increased your password hash factor to a very high number which will cause the login to be much slower. 

Re: logging, it is possible to change the logging level to TRACE or DEBUG, but I doubt it will provide much insight because are a very light on tracing or debug logging.

**Comment by prabhakarreddy1234** [comment]
@robotdan 

I see below logs
```
com.inversoft.scheduler.LogAndRetainFailureHandler - The scheduled service [class io.fusionauth.api.service.useraction.UserActionEndEventSender] failed but will be re-run.
org.apache.ibatis.exceptions.PersistenceException:
### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: canceling statement due to lock timeout
  Where: while locking tuple (0,1) in relation "locks"
### The error may exist in io/fusionauth/api/domain/LockMapper.java (best guess)
### The error may involve io.fusionauth.api.domain.LockMapper.lock-Inline
### The error occurred while setting parameters
### SQL: SELECT type FROM locks WHERE type = ? FOR UPDATE
### Cause: org.postgresql.util.PSQLException: ERROR: canceling statement due to lock timeout
  Where: while locking tuple (0,1) in relation "locks"
        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77)
        at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.ibatis.session.SqlSessionManager$SqlSessionInterceptor.invoke(SqlSessionManager.java:350)
        at com.sun.proxy.$Proxy46.selectOne(Unknown Source)
        at org.apache.ibatis.session.SqlSessionManager.selectOne(SqlSessionManager.java:166)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:83)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
        at com.sun.proxy.$Proxy75.lock(Unknown Source)
        at io.fusionauth.api.service.lock.DefaultLockService.acquireLock(DefaultLockService.java:29)
        at io.fusionauth.api.service.useraction.DefaultActionService.sendEndEvents(DefaultActionService.java:350)
        at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
        at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
        at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
        at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
        at io.fusionauth.api.service.useraction.UserActionEndEventSender.run(UserActionEndEventSender.java:23)
        at com.inversoft.scheduler.InjectableRunnable.run(InjectableRunnable.java:37)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
Also, From our query insights we see that below query is taking 3 seconds on average to execute and it's locking the table causing latency. This query is causing the above exception as well.
`SELECT type FROM locks WHERE type = $1 FOR UPDATE` 

We have around 650 users and no concurrent users. App is almost idle most of the time. 
Do you suggest anything based on above information? Do you think webhooks add additional latency to the application ?
