### ISSUE TITLE
Kick-start option to run the setup wizard

### ISSUE THREAD

**Issue by johnmaia** [FusionAuth/fusionauth-issues#469]
### Problem
On our development environment we create and destroy multiple tenants for testing purpose. To create a new tenant we must give a `verificationEmailTemplateId` in order to activate the `verifyEmail` feature (even though we don't use FusionAuth to send emails). 

To fetch this email template ID we retrieve the email templates and then we filter them by `name` (`Email Verification`). But if the `FusionAuth` instance is initiated by a `kick-start` script (without performing the setup wizard) we found that there is no email templates available.

This works pretty well on our development environment because we are using a `sql` dump of a ready-to-use `1.11.0` instance where the setup wizard had already being executed.

We are now migrating from `1.11.0` to `1.14.0` and we wish to use the kick-start configuration `json` file instead of the `sql` dump. 

On my first attempt to use the kick-start script feature I've managed to work around the issue mentioned above by adding a request to manually add an email template named `Email Verification`. This solution works flawlessly and I was able to run our tests without a single error (aside from the new required `externalIdentifierConfiguration` `externalAuthenticationIdTimeToLiveInSeconds` option).

Because of this new `externalIdentifierConfiguration` option I wanted to check what the dashboard sets as the default value and therefore I had to go through the setup wizard which, because of the following unique constraint violation, I've got the following error:

<img width="584" alt="Screenshot 2020-02-07 at 17 08 16" src="https://user-images.githubusercontent.com/6815911/74049728-a6ded980-49cc-11ea-829b-9120823c0ddf.png">

This was the error call-stack: 

```
fusionauth_1      | Feb 07, 2020 5:08:09.124 PM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
fusionauth_1      | org.apache.ibatis.exceptions.PersistenceException:
fusionauth_1      | ### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "email_templates_uk_1"
fusionauth_1      |   Detail: Key (name)=(Email Verification) already exists.
fusionauth_1      | ### The error may involve io.fusionauth.api.domain.EmailTemplateMapper.create-Inline
fusionauth_1      | ### The error occurred while setting parameters
fusionauth_1      | ### SQL: INSERT INTO email_templates (id, default_from_name, default_html_template, default_subject, default_text_template, from_email, localized_from_names, localized_html_templates, localized_subjects, localized_text_templates, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
fusionauth_1      | ### Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "email_templates_uk_1"
fusionauth_1      |   Detail: Key (name)=(Email Verification) already exists.
fusionauth_1      | 	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
fusionauth_1      | 	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
fusionauth_1      | 	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
fusionauth_1      | 	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
fusionauth_1      | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
fusionauth_1      | 	at java.lang.reflect.Method.invoke(Method.java:498)
fusionauth_1      | 	at org.apache.ibatis.session.SqlSessionManager$SqlSessionInterceptor.invoke(SqlSessionManager.java:350)
fusionauth_1      | 	at com.sun.proxy.$Proxy46.insert(Unknown Source)
fusionauth_1      | 	at org.apache.ibatis.session.SqlSessionManager.insert(SqlSessionManager.java:236)
fusionauth_1      | 	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:58)
fusionauth_1      | 	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
fusionauth_1      | 	at com.sun.proxy.$Proxy58.create(Unknown Source)
fusionauth_1      | 	at io.fusionauth.api.service.email.DefaultEmailTemplateService.create(DefaultEmailTemplateService.java:66)
fusionauth_1      | 	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
fusionauth_1      | 	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
fusionauth_1      | 	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
fusionauth_1      | 	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
fusionauth_1      | 	at io.fusionauth.api.service.system.DefaultSetupService.setupEmailTemplate(DefaultSetupService.java:155)
fusionauth_1      | 	at io.fusionauth.api.service.system.DefaultSetupService.setup(DefaultSetupService.java:100)
fusionauth_1      | 	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
fusionauth_1      | 	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
fusionauth_1      | 	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
fusionauth_1      | 	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
fusionauth_1      | 	at io.fusionauth.app.action.SetupWizardAction.post(SetupWizardAction.java:63)
fusionauth_1      | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
fusionauth_1      | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
fusionauth_1      | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
fusionauth_1      | 	at java.lang.reflect.Method.invoke(Method.java:498)
fusionauth_1      | 	at org.primeframework.mvc.util.ReflectionUtils.invoke(ReflectionUtils.java:414)
fusionauth_1      | 	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.execute(DefaultActionInvocationWorkflow.java:79)
fusionauth_1      | 	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.perform(DefaultActionInvocationWorkflow.java:62)
fusionauth_1      | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1      | 	at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:47)
fusionauth_1      | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1      | 	at org.primeframework.mvc.security.DefaultSecurityWorkflow.perform(DefaultSecurityWorkflow.java:60)
fusionauth_1      | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1      | 	at org.primeframework.mvc.parameter.DefaultPostParameterWorkflow.perform(DefaultPostParameterWorkflow.java:50)
fusionauth_1      | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1      | 	at org.primeframework.mvc.content.DefaultContentWorkflow.perform(DefaultContentWorkflow.java:52)
fusionauth_1      | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1      | 	at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:57)
fusionauth_1      | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1      | 	at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:102)
fusionauth_1      | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1      | 	at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:58)
fusionauth_1      | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1      | 	at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:45)
fusionauth_1      | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1      | 	at io.fusionauth.app.primeframework.FrontEndTenantWorkflow.perform(FrontEndTenantWorkflow.java:69)
fusionauth_1      | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1      | 	at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:126)
fusionauth_1      | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1      | 	at org.primeframework.mvc.workflow.StaticResourceWorkflow.perform(StaticResourceWorkflow.java:97)
fusionauth_1      | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1      | 	at org.primeframework.mvc.parameter.RequestBodyWorkflow.perform(RequestBodyWorkflow.java:89)
fusionauth_1      | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1      | 	at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:57)
fusionauth_1      | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1      | 	at io.fusionauth.app.primeframework.CORSFilter.handleNonCORS(CORSFilter.java:291)
fusionauth_1      | 	at io.fusionauth.app.primeframework.CORSFilter.doFilter(CORSFilter.java:223)
fusionauth_1      | 	at io.fusionauth.app.primeframework.CORSRequestWorkflow.perform(CORSRequestWorkflow.java:48)
fusionauth_1      | 	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
fusionauth_1      | 	at io.fusionauth.app.primeframework.FusionAuthMVCWorkflow.perform(FusionAuthMVCWorkflow.java:88)
fusionauth_1      | 	at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44)
fusionauth_1      | 	at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50)
fusionauth_1      | 	at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:84)
fusionauth_1      | 	at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:59)
fusionauth_1      | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
fusionauth_1      | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
fusionauth_1      | 	at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27)
fusionauth_1      | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
fusionauth_1      | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
fusionauth_1      | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
fusionauth_1      | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
fusionauth_1      | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
fusionauth_1      | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
fusionauth_1      | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
fusionauth_1      | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
fusionauth_1      | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
fusionauth_1      | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
fusionauth_1      | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
fusionauth_1      | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
fusionauth_1      | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
fusionauth_1      | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
fusionauth_1      | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
fusionauth_1      | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
fusionauth_1      | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
fusionauth_1      | 	at java.lang.Thread.run(Thread.java:748)
fusionauth_1      | Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "email_templates_uk_1"
fusionauth_1      |   Detail: Key (name)=(Email Verification) already exists.
fusionauth_1      | 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
fusionauth_1      | 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
fusionauth_1      | 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
fusionauth_1      | 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
fusionauth_1      | 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
fusionauth_1      | 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
fusionauth_1      | 	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:138)
fusionauth_1      | 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
fusionauth_1      | 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
fusionauth_1      | 	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
fusionauth_1      | 	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
fusionauth_1      | 	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
fusionauth_1      | 	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
fusionauth_1      | 	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
fusionauth_1      | 	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
fusionauth_1      | 	... 86 common frames omitted
```
 
### Solution
Include a option on the kick-start json script to run the setup with certain values. 
Example:
```json
{
  ...
  "setup": {
    "user": {
      "firstName": "waldo",
      "lastName": "fred",
      "email": "foo@bar.com",
      "password": "foobiz"
    },
    "timezone": "Europe/Lisbon"
  }
  ...
}
```

### Alternatives/workarounds
I've managed to workaround this issue by adding the following request to the kick-start script as the last request:
```json
{
  "method": "POST",
  "url": "/setup-wizard?user.firstName=waldo&user.lastName=fred&user.email=foo%40bar.com&user.password=foobiz&passwordConfirm=foobiz&__cb_acceptLicense=false&acceptLicense=true&__cb_addToNewsletter=false&timezone=Europe%2FLisbon",
  "body": {}
}
```

This does throw the following error when runing the kick-start script: 

```
fusionauth_1      | Feb 07, 2020 5:21:03.784 PM ERROR io.fusionauth.api.service.system.kickstart.KickstartRunner - Failed to execute request to [POST][/setup-wizard?user.firstName=waldo&user.lastName=fred&user.email=foo%40bar.com&user.password=foobiz&passwordConfirm=foobiz&__cb_acceptLicense=false&acceptLicense=true&__cb_addToNewsletter=false&timezone=Europe%2FLisbon] Status [200]
fusionauth_1      | Request body:
fusionauth_1      | { }
fusionauth_1      | Feb 07, 2020 5:21:03.789 PM ERROR io.fusionauth.api.service.system.kickstart.KickstartRunner - Exception returned
fusionauth_1      | com.inversoft.rest.JSONException: Failed to parse the HTTP response as JSON. Actual HTTP response body:
fusionauth_1      | Note: Output has been truncated to the first 1024 of 7632 bytes.
fusionauth_1      |
fusionauth_1      |
fusionauth_1      | <!DOCTYPE html>
fusionauth_1      | <html lang="en">
fusionauth_1      | <head>
fusionauth_1      |   <title>Login | FusionAuth</title>
fusionauth_1      |   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
fusionauth_1      |   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
fusionauth_1      |   <meta name="application-name" content="FusionAuth">
fusionauth_1      |   <meta name="author" content="FusionAuth">
fusionauth_1      |   <meta name="description" content="User Management Redefined. A Single Sign-On solution for your entire enterprise.">
fusionauth_1      |   <meta name="robots" content="index, follow">
fusionauth_1      |
fusionauth_1      |   <link rel="apple-touch-icon-precomposed" sizes="57x57" href="/images/apple-touch-icon-57x57.png" />
fusionauth_1      |   <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/images/apple-touch-icon-114x114.png" />
fusionauth_1      |   <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/images/apple-touch-icon-72x72.png" />
fusionauth_1      |   <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/images/apple-touch-icon-144x144.png" />
fusionauth_1      |   <link rel="apple-touch-icon-precomposed" sizes="60x60" href="/images/apple-touch-icon-60x60.png" />
fusionauth_1      |   <li
fusionauth_1      | 	at com.inversoft.rest.JSONResponseHandler.apply(JSONResponseHandler.java:61)
fusionauth_1      | 	at com.inversoft.rest.RESTClient.go(RESTClient.java:272)
fusionauth_1      | 	at io.fusionauth.api.service.system.kickstart.KickstartRunner.run(KickstartRunner.java:109)
fusionauth_1      | 	at java.lang.Thread.run(Thread.java:748)
fusionauth_1      | Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
fusionauth_1      |  at [Source: (com.inversoft.rest.JSONResponseHandler$BetterBufferedInputStream); line: 2, column: 2]
fusionauth_1      | 	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
fusionauth_1      | 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
fusionauth_1      | 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
fusionauth_1      | 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2654)
fusionauth_1      | 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:856)
fusionauth_1      | 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:753)
fusionauth_1      | 	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4340)
fusionauth_1      | 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4189)
fusionauth_1      | 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3242)
fusionauth_1      | 	at com.inversoft.rest.JSONResponseHandler.apply(JSONResponseHandler.java:56)
fusionauth_1      | 	... 3 common frames omitted
```  

But `FusionAuth` works flawlessly with everything setuped properly without the need of a `sql` dump and for now its going to be the solution for our development enviorment, but its not ideal.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Interesting hack to make a `POST` :-) The exception from that is because we coded it to expect JSON in response, perhaps we need to limit requests to `/api/*`. 

I'm not sure I understand the core issue - Kickstart is designed to and does bypass setup wizard. If you do want email template created as part of your config you need to add those to the kickstart. 

See this example in the doc:
https://fusionauth.io/docs/v1/tech/installation-guide/kickstart#include-text-files

The reason we made this choice is that our stock email templates are very basic anyway, and the end user has to modify the URL in the templates before use so we decided you might as well just specify exactly how you want the template to look by adding it to your kickstart configuration. 



Re: the tenant part of it - I would recommend cloning the base tenant in your kickstart and then patching it with any changes you want. 

See Tenant `PATCH` example in this file:
https://github.com/FusionAuth/fusionauth-kickstart-examples/blob/master/fusionauth/kickstart-development.json

and a clone using `sourceTenantId` here :
https://github.com/FusionAuth/fusionauth-kickstart-examples/blob/master/fusionauth/kickstart-multiple-tenants.json

**Comment by johnmaia** [comment]
Correct. We can customize `FusionAuth` with the kick-start script to run our tests but (and I don't know if I'm doing something wrong) if I add an email template with the same name as one of the default templates (e.g. `Email Verification`) and then go through the wizard process it will throw an internal server error because of the conflicting template name.

Another way to avoid this behavior would be to load the load the default templates on the initial boot of the application, instead of only registering them when the wizard is completed.

We've contemplated the idea of the `sourceTenantId` and we may end up using it in the future but this issue is with our development environment where we need to boot a clean `FusionAuth` instance, prepare it with the necessary parameters in order to run the tests. Even if we create a base tenant, from which we clone it when creating new one's, we would still need to set the email themes to enable the recover/verify/etc features and if after that for some reason we had to visit the dashboard (e.g. debugging) the error related to the conflicting template name would pop-up again.

The best solution would be to be able to active the recover/verify/etc features without being required to set any email template. But since they are required, and we've been using the default templates for every new application, we'll keep using this "hack" in order to load the default email themes on our development environment without blocking possibility of accessing the dashboard.

**Comment by robotdan** [comment]
> and then go through the wizard process it will throw an internal server error because of the conflicting template name.

This shouldn't be happening, if you use kickstart and create at least one user you should not be prompted to go through setup wizard, you should just find yourself at the login prompt. If you are completing kickstart and still seeing the Setup Wizard - there is a bug or something else happening. 

If that is the case - send me your kickstart file and we'll see if we can recreate.

**Comment by johnmaia** [comment]
@robotdan your correct. My bad, I didn't expected that it would be possible to register the `FusionAuth` admin user with the kickstart script. I've rewritten our script and know it fully solves our issues.

I'm closing this issue now that I've seen that this feature is not necessary. 

Thanks for the help @robotdan.
