### ISSUE TITLE
Error thrown on bulk users remove via api

### ISSUE THREAD

**Issue by uncledent** [FusionAuth/fusionauth-issues#490]
### Description 
Users are removed, but error is thrown

```
ClientResponse {
  statusCode: 200,
  exception:
   { FetchError: invalid json response body at http://localhost:9011/api/user/bulk reason: Unexpected end of JSON input
       at /Users/denis/app4time_mono/backend/node_modules/node-fetch/lib/index.js:272:32
       at process._tickCallback (internal/process/next_tick.js:68:7)
     message:
      'invalid json response body at http://localhost:9011/api/user/bulk reason: Unexpected end of JSON input',
     type: 'invalid-json' } }
```

### Expected behavior
The error should not be thrown

### Screenshots
<img width="910" alt="Bildschirmfoto 2020-02-25 um 11 55 01" src="https://user-images.githubusercontent.com/6542981/75241054-ad8b9000-57c5-11ea-866c-98998d1f0c10.png">

### Platform
 - Fusionauth 1.10.0

**Comment by uncledent** [comment]
Checked - Fixed in 1.15.2
