### ISSUE TITLE
Issues with horizontal tab for Kickstart included text files

### ISSUE THREAD

**Issue by mgetka** [FusionAuth/fusionauth-issues#524]
### Description 

Horizontal tab character (ASCII `0x09`) in Kickstart included text files causes exceptions on application startup.

![](https://i.imgur.com/3bN0wfg.png)

### Steps to reproduce
1. Prepare Kickstart script including a text file containing horizontal tab character
2. Start FusionAuth
3. JSON encoding errors are thrown in application log

### Expected behavior
Kickstart script is handled correctly

### Platform
 - Device: Desktop
 - OS: 18.04.1-Ubuntu x64
 - Docker: 19.03.6, build 369ce74a3c
 - Image: fusionauth/fusionauth-app:1.15.5

#### Kickstart script:
```
{
    "apiKeys": [{
        "key": "465e177b-ea25-49ca-8b35-0b809c2eacc3"
    }],
    "requests": [{
            "method": "POST",
            "url": "/api/email/template/0502df1e-4010-4b43-b571-a423fce978b2",
            "body": {
                "emailTemplate": {
                    "defaultFromName": "FusionAuth Development",
                    "defaultSubject": "Reset your password",
                    "defaultHtmlTemplate": "@{template.txt}",
                    "defaultTextTemplate": "bbb",
                    "fromEmail": "dev@fusionauth.io",
                    "name": "Forgot Password"
                }
            }
        },
        {
            "method": "POST",
            "url": "/api/user/registration/00000000-0000-0000-0000-000000000001",
            "body": {
                "user": {
                    "email": "admin@example.com",
                    "password": "password"
                },
                "registration": {
                    "applicationId": "#{FUSIONAUTH_APPLICATION_ID}",
                    "roles": [
                        "admin"
                    ]
                }
            }
        }
    ]
}
```
#### `template.txt` contents:
_Just horizontal tab in double quotes._
```
"	"

```
#### Related error trace:
```
Mar 18, 2020 1:34:59.230 PM ERROR io.fusionauth.api.service.system.kickstart.DefaultKickstartService - Invalid kickstart file, unable to parse the JSON.
com.fasterxml.jackson.databind.JsonMappingException: Illegal unquoted character ((CTRL-CHAR, code 9)): has to be escaped using backslash to be included in string value
 at [Source: (String)"{
  "apiKeys" : [ {
    "description" : null,
    "key" : "465e177b-ea25-49ca-8b35-0b809c2eacc3",
    "permissions" : null,
    "tenantId" : null
  } ],
  "licenseId" : null,
  "requests" : [ {
    "body" : {
      "emailTemplate" : {
        "defaultFromName" : "FusionAuth Development",
        "defaultHtmlTemplate" : "\"	\"\n",
        "defaultSubject" : "Reset your password",
        "defaultTextTemplate" : "bbb",
        "fromEmail" : "dev@fusionauth.io",
        "name" : "Forgot Password"
 "[truncated 489 chars]; line: 13, column: 37] (through reference chain: io.fusionauth.api.domain.KickstartRequest["requests"]->java.util.ArrayList[0]->io.fusionauth.api.domain.KickstartRequest$APIRequest["body"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:397)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:356)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1714)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserializeWith(SettableBeanProperty.java:560)
	at com.fasterxml.jackson.databind.deser.impl.MergingSettableBeanProperty.deserializeAndSet(MergingSettableBeanProperty.java:80)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1719)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1261)
	at io.fusionauth.api.service.system.kickstart.DefaultKickstartService.kickstart(DefaultKickstartService.java:188)
	at io.fusionauth.api.service.system.KickStarter.<init>(KickStarter.java:15)
	at io.fusionauth.api.service.system.KickStarter$$FastClassByGuice$$7550f1f1.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at org.primeframework.mvc.guice.GuiceBootstrap.initialize(GuiceBootstrap.java:58)
	at org.primeframework.mvc.servlet.PrimeServletContextListener.contextInitialized(PrimeServletContextListener.java:61)
	at com.inversoft.maintenance.servlet.MaintenanceModePrimeServletContextListener.contextInitialized(MaintenanceModePrimeServletContextListener.java:59)
	at io.fusionauth.app.primeframework.FusionAuthAppPrimeServletContextListener.contextInitialized(FusionAuthAppPrimeServletContextListener.java:28)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4699)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5165)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal unquoted character ((CTRL-CHAR, code 9)): has to be escaped using backslash to be included in string value
 at [Source: (String)"{
  "apiKeys" : [ {
    "description" : null,
    "key" : "465e177b-ea25-49ca-8b35-0b809c2eacc3",
    "permissions" : null,
    "tenantId" : null
  } ],
  "licenseId" : null,
  "requests" : [ {
    "body" : {
      "emailTemplate" : {
        "defaultFromName" : "FusionAuth Development",
        "defaultHtmlTemplate" : "\"	\"\n",
        "defaultSubject" : "Reset your password",
        "defaultTextTemplate" : "bbb",
        "fromEmail" : "dev@fusionauth.io",
        "name" : "Forgot Password"
 "[truncated 489 chars]; line: 13, column: 37]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
	at com.fasterxml.jackson.core.base.ParserBase._throwUnquotedSpace(ParserBase.java:1046)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString2(ReaderBasedJsonParser.java:2067)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString(ReaderBasedJsonParser.java:2038)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:293)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:267)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	... 38 common frames omitted
```

**Comment by voidmain** [comment]
Quite possibly the funniest issue submission yet! Love the image. Haha.

Looks like we need to escape white space better when processing external files.

**Comment by robotdan** [comment]
Thanks for the issue and the excellent documentation!
