### ISSUE TITLE
 Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#635]
### Description
From what I can gather this is not an issue with Tomcat. However, because we cannot fix all clients, it may be recommended that we modify the default configuration to be more flexible. 

This suggestion post suggests the following modification to Tomcat ( https://stackoverflow.com/a/46053161/3892636 ) 

> The URI is encoded as UTF-8, but Tomcat is decoding them as ISO-8859-1. You need to edit the connector settings in the server.xml and add the URIEncoding="UTF-8" attribute.

However we are currently shipping this configuration.  Needs more investigation, unclear if this is causing any external symptoms or if it is just noise in the log.

```
13-May-2020 15:11:36.852 INFO [http-nio-9011-exec-21] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
        java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
                at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:502)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:502)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:832)
```

### Possible Solution

Tomcat documents the following configuration `relaxedQueryChars`.  ( https://tomcat.apache.org/tomcat-8.5-doc/config/http.html )

> The [https://tools.ietf.org/rfc/rfc7230.txt](HTTP/1.1 specification) requires that certain characters are `%nn` encoded when used in URI query strings. Unfortunately, many user agents including all the major browsers are not compliant with this specification and use these characters in unencoded form. To prevent Tomcat rejecting such requests, this attribute may be used to specify the additional characters to allow. If not specified, no additional characters will be allowed. The value may be any combination of the following characters: `" < > [ \ ] ^ ` { \| }` . Any other characters present in the value will be ignored.
--

It seems that to make Tomcat work with most browsers, we may need to shop this configuration. 

However, it is still unclear if this is FusionAuth's problem or a browsers problem. See this [SO thread](https://stackoverflow.com/a/50377112/3892636) where it is possibly advocated for not adding this configuration. 

As a side data point, Confluence is also bundling Tomcat, and they use this configuration. https://jira.atlassian.com/browse/CONFSERVER-57582

### Additional Context
https://bz.apache.org/bugzilla/show_bug.cgi?id=62273
https://cwiki.apache.org/confluence/display/TOMCAT/Encoding+and+URIs

### Related Issues
https://programmer.group/invalid-character-found-in-the-request-target-problem-resolution.html
https://stackoverflow.com/a/41150474/3892636
https://stackoverflow.com/a/46053161/3892636
https://bugzilla.mozilla.org/show_bug.cgi?id=1451347

**Comment by jzhuk** [comment]
There are two types of errors that start with "Error parsing HTTP request header" 
1)Invalid character found in the HTTP protocol 
2) Invalid character found in method name.
In that case Tomcat log the error and does not send any response back to the client.
The socked is not closed and one more Open File added to LFOS (log for open files).
Eventually number of open files is increased to the limit and Tomcat stops responding at all.
I've read of Tomcat configurations helping with HTTP request, but my case is using HTTPS via AWS Cloud Front.
I tried all recommended configurations in server.xml and catalina.properties.
I also tried several Tomcat versions, but not all.
AWS support sincerely tried to help me but unfortunately failed.
I highly appreciate anyone who can help here.
Thank you,
Jeff
 I establish ServletFilter class, but it does not help. 
The error happens before the filter, in tomcat layer. Tomcat has some provisioning for accepting different character coding, but not in encrypted way.

**Comment by robotdan** [comment]
Thanks @jzhuk can you post your exact exception? Or is it identical to the one I have in the description?

**Comment by jzhuk** [comment]
Hi Daniel!

Thank you so much for looking into that.

Invalid characters in the encrypted request make invalid URI and invalidate the protocol. 
Tomcat does not provide a response with the Error number, like 500, but just throws the Exception below. 


16-Jul-2020 06:31:52.793 INFO [http-nio-80-exec-167] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
	java.lang.IllegalArgumentException: Invalid character found in method name [0x050x01...]. HTTP method names must be tokens
		at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:432)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:502)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:834)

----
16-Jul-2020 18:06:51.220 INFO [http-nio-80-exec-9] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header                            Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.                                                                                java.lang.IllegalArgumentException: Invalid character found in the request target [/index.php?s=/Index/\x5Cthink\x5Capp/invokefunction&function=call_user_func_array&vars[0]=sha1&vars[1][]=xyzt]. The valid characters are defined in RFC 7230 and RFC 3986                                                                            at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:491)                                                                      at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:260)  

These exceptions are rare, strange client requests throw the exceptions that are not caught, handshake with the client is not happening, causing LSOF growing with the CLOSE_WAIT records:

http-nio-  8774 10605           root  149u     IPv6           15950578       0t0        TCP ip-172-31-42-229.us-west-2.compute.internal:http->64.252.86.223:23914 (CLOSE_WAIT)
http-nio-  8774 10605           root  150u     IPv6           15950579       0t0        TCP ip-172-31-42-229.us-west-2.compute.internal:http->64.252.86.223:25842 (CLOSE_WAIT)
http-nio-  8774 10605           root  151u     IPv6           15951160       0t0        TCP ip-172-31-42-229.us-west-2.compute.internal:http->64.252.86.223:30832 (CLOSE_WAIT)
http-nio-  8774 10605           root  152u     IPv6           15950580       0t0        TCP ip-172-31-42-229.us-west-2.compute.internal:http->64.252.86.35:12450 (CLOSE_WAIT)

See more in http://javaschool.com/lsof.txt

This is my conclusion, which is confirmed by AWS team.

Another possibility is that there is a response to these cases like you said, but it is so specific, that AWS does not provide it back to the client.

(AWS disregarded this possibility)

I am looking forward to your advice/opinion/solution.

Thank you!
Jeff

**Comment by jzhuk** [comment]
Hi Daniel!
I just posted a comment to:
https://github.com/FusionAuth/fusionauth-issues/issues/635

Jeff (Yefim) Zhuk | 720-299-4701 | http://ITUniversity.us 
http://ITofTheFuture.com | http://FixingEducation.us 
 

    On Monday, July 20, 2020, 10:56:49 AM MDT, Daniel DeGroff <notifications@github.com> wrote:  
 
 


Thanks @jzhuk can you post your exact exception? Or is it identical to the one I have in the description?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Invalid character found in the request target. The valid characters are ...

Tomcat configuration may cause exception for unexpected encoding in URL Description From what I can gather this ...
 |

 |

 |




Thank you so much for your help!

**Comment by jzhuk** [comment]
You can see my config here:
https://javaschool.com/server.xml
https://javaschool.com/catalina.properties

**Comment by ulantiger** [comment]
Add this **relaxedQueryChars="[,]"** , in your  Tomcat server.xml

It should look like:

    _<Connector port="8080" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443"
	       compression="on"
               URIEncoding="UTF-8"
               compressableMimeType="text/html,text/xml"
               **relaxedQueryChars="[,]"**
		 />_

**Comment by plunkettscott** [comment]
@robotdan, that bug I was telling you about in the latest email that's been crashing our server every night -- this issue's log is the last thing logged. it's logged right around the time I got an alert from our monitoring system that the FusionAuth server is down. For reference, including the last few logs leading up to the crash as well.

```
...
08-Sep-2020 21:35:29.115 INFO [http-nio-9011-exec-5] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
	java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
		at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:502)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:502)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:832)
09-Sep-2020 00:44:06.265 INFO [http-nio-9011-exec-10] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
	java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
		at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:502)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:502)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:832)
```

This is an EC2 instance running with an API Gateway in front of it in AWS. From what I can tell, this exception is not being handled and the JVM is crashing.

Is the proper solution to adjust the `server.xml` like mentioned in the previous comment? I see this is now an in-progress issue with a milestone set, so I'm not sure if the solution actually works.

**Comment by robotdan** [comment]
There is not yet an official fix for this issue. Because those are `INFO` messages it is still unclear to me if this is a root cause or it is noise in the log. 

If you want to try the `server.xml` update as mentioned by @ulantiger to see if that resolves the nightly issue you're observing - and then report back that would be helpful to know. 

Ideally we'd capture a few actual HTTP headers that cause this message to be logged so we can built some test cases.

**Comment by plunkettscott** [comment]
Understood. Let me get some additional logging and tracing enabled for this load balancer and see if I can come back with some better visibility into the cause of those log entries.

**Comment by plunkettscott** [comment]
New logs from FusionAuth. Doesn't look like this is directly related to my crashing, however, there's some other logs appearing in this bunch. Putting them here, but I believe most of this is irrelevant to this issue. Including them for reference anyway just in case.

```
2020-09-09 6:25:47.006 AM WARN  org.primeframework.mvc.action.DefaultActionMappingWorkflow - The action class [io.fusionauth.app.action.IndexAction] does not have a valid execute method for the HTTP method [POST]
2020-09-09 6:29:09.449 AM WARN  org.primeframework.mvc.action.DefaultActionMappingWorkflow - The action class [io.fusionauth.app.action.IndexAction] does not have a valid execute method for the HTTP method [OPTIONS]
2020-09-09 9:12:59.185 AM WARN  org.primeframework.mvc.action.DefaultActionMappingWorkflow - The action class [io.fusionauth.app.action.IndexAction] does not have a valid execute method for the HTTP method [POST]
09-Sep-2020 11:28:49.114 INFO [http-nio-9011-exec-21] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
	java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
		at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:502)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:502)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:832)
09-Sep-2020 11:36:52.248 INFO [http-nio-9011-exec-5] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
	java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
		at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:502)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:502)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:832)
2020-09-09 1:36:56.061 PM WARN  org.primeframework.mvc.action.DefaultActionMappingWorkflow - The action class [io.fusionauth.app.action.IndexAction] does not have a valid execute method for the HTTP method [POST]
2020-09-09 6:07:30.130 PM WARN  org.primeframework.mvc.action.DefaultActionMappingWorkflow - The action class [io.fusionauth.app.action.IndexAction] does not have a valid execute method for the HTTP method [POST]
2020-09-09 7:44:17.057 PM WARN  org.primeframework.mvc.action.DefaultActionMappingWorkflow - The action class [io.fusionauth.app.action.IndexAction] does not have a valid execute method for the HTTP method [POST]
09-Sep-2020 22:50:34.416 INFO [http-nio-9011-exec-19] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
	java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
		at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:502)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:502)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:832)
10-Sep-2020 01:58:47.811 INFO [http-nio-9011-exec-1] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
	java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
		at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:502)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:502)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:832)
2020-09-10 1:58:48.264 AM WARN  org.primeframework.mvc.action.DefaultActionMappingWorkflow - The action class [io.fusionauth.app.action.IndexAction] does not have a valid execute method for the HTTP method [POST]
```

**Comment by robotdan** [comment]
This should be fixed in version 1.19.5. I'll close this out, please comment on this issue if you can still recreate the issue. 

Here is a summary of the change to `server.xml`, added `relaxedPathChars` and `relaxedQueryChars`.

Defaulting to  `[]|` and `[]|{}^`\"<>` respectively, and these will be available through configuration.


```
# configuration options in fusionauth.properties
fusionauth-app.http.relaxed-path-chars=
fusionauth-app.http.relaxed-query-chars=
```

And also through environment variables `FUSIONAUTH_APP_HTTP_RELAXED_PATH_CHARS` and `FUSIONAUTH_APP_HTTP_RELAXED_QUERY_CHARS`. 

It should be noted that if you change these values, you'll need to use XML character references in unicode to ensure they are handled correct.

**Comment by ulantiger** [comment]
Yes, it fixed the problem. But Tomcat 9.0.33 pointed that < and > characters can't be used 
Therefore my final config looks like this:
    <Connector port="8080" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443"
	       compression="on"
               URIEncoding="UTF-8"
               compressableMimeType="text/html,text/xml"
               relaxedQueryChars='[,]|"{}^`'
	       relaxedPathChars ='[]|'
		 />

Thank you @robotdan

**Comment by robotdan** [comment]
@ulantiger you're welcome. Yes, you'll need to use unicode instead of the literal `<` or `>` characters. Here is the actual `relaxedQueryChars` value I have in `server.xml`:

`&#x5B;&#x5D;&#x7C;&#x7B;&#x7D;&#x5E;&#x5C;&#x60;&#x22;&#x3C;&#x3E;`

* `&#x5B;` -> `[`
* `&#x5D;` -> `]`
* `&#x7C;` -> `|`
* `&#x7B;` -> `{`
* `&#x7D;` -> `}`
* `&#x5E;` -> `^`
* `&#x5C;` -> `\` 
* `&#x60;` -> `` ` ``
* `&#x22;` -> `"`
* `&#x3C;` -> `<`
* `&#x3E;` -> `>`
