### ISSUE TITLE
Registration Fails under specific age

### ISSUE THREAD

**Issue by ehoxha4** [FusionAuth/fusionauth-issues#720]
### Description 
If COPPA is activated, at the moment that age is less than a specified value registration fails.

### Steps to reproduce
1. Go to Edit Application -> Registration and enable Self service registration.
2. Go to Edit Tenant -> Family and enable Family settings.
3. Go to login page and click Create an account.
4. Enter birthday less than 12 years old and click register.
5. Fill personal information and parent email and click register.
6. 500 Internal Server Error.
An internal error occurred. FusionAuth should have captured a stack trace in the log. If you have a licensed edition, contact support using the form under the "Get Support" menu item. Otherwise, check your logs to see what the error might be. 
7. Logs on docker

`Jul 01, 2020 11:32:56.148 AM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
java.lang.UnsupportedOperationException: You are attempting to map a form field that contains multiple parameters to a property on the action class that is of type LocalDate. This isn't allowed.
        at org.primeframework.mvc.parameter.convert.converters.LocalDateConverter.stringsToObject(LocalDateConverter.java:65)
        at org.primeframework.mvc.parameter.convert.AbstractGlobalConverter.convertFromStrings(AbstractGlobalConverter.java:89)
        at org.primeframework.mvc.parameter.el.Accessor.convert(Accessor.java:152)
        at org.primeframework.mvc.parameter.el.MemberAccessor.set(MemberAccessor.java:133)
        at org.primeframework.mvc.parameter.el.Accessor.set(Accessor.java:90)
        at org.primeframework.mvc.parameter.el.Expression.setCurrentValue(Expression.java:93)
        at org.primeframework.mvc.parameter.el.DefaultExpressionEvaluator.setValue(DefaultExpressionEvaluator.java:132)
        at org.primeframework.mvc.parameter.DefaultParameterHandler.setValues(DefaultParameterHandler.java:201)
        at org.primeframework.mvc.parameter.DefaultParameterHandler.handle(DefaultParameterHandler.java:119)
        at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:54)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
        at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:102)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
        at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:58)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
        at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:45)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
        at io.fusionauth.app.primeframework.FrontEndTenantWorkflow.perform(FrontEndTenantWorkflow.java:78)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
        at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:126)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
        at org.primeframework.mvc.workflow.StaticResourceWorkflow.perform(StaticResourceWorkflow.java:97)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
        at org.primeframework.mvc.parameter.RequestBodyWorkflow.perform(RequestBodyWorkflow.java:89)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
        at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:57)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
        at io.fusionauth.app.primeframework.CORSFilter.handleNonCORS(CORSFilter.java:291)
        at io.fusionauth.app.primeframework.CORSFilter.doFilter(CORSFilter.java:223)
        at io.fusionauth.app.primeframework.CORSRequestWorkflow.perform(CORSRequestWorkflow.java:48)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
        at io.fusionauth.app.primeframework.FusionAuthMVCWorkflow.perform(FusionAuthMVCWorkflow.java:88)
        at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44)
        at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50)
        at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:82)
        at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:59)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:832)
`

### Expected behavior
A new email will be send to parent to confirm account creation for his child.

### Screenshots

![Capture1](https://user-images.githubusercontent.com/50490642/86260335-6cfdb200-bbbd-11ea-889d-be830c3f24e0.PNG)
![Capture2](https://user-images.githubusercontent.com/50490642/86260340-6ff8a280-bbbd-11ea-960c-1549531191ba.PNG)
![Capture](https://user-images.githubusercontent.com/50490642/86259921-ec3eb600-bbbc-11ea-8be9-d8a7f3a5539e.PNG)
![Capturel](https://user-images.githubusercontent.com/50490642/86260347-71c26600-bbbd-11ea-90a5-4267fc689783.PNG)

### Platform
- Docker

**Comment by mooreds** [comment]
I believe this is a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/702 which has the workaround of not requiring the birthday on the registration page. 

Can you take a look and let me know if this is the same issue?

**Comment by ehoxha4** [comment]
Yes it works fine if you remove birthday.
Thank you!
Closing now.
