### ISSUE TITLE
unable to start fusionauth-search!

### ISSUE THREAD

**Issue by ashish1247** [FusionAuth/fusionauth-issues#795]
Given below is the output from "systemctl status fusionauth-search.service". I am currently working on Ubuntu 20.04 LTS.

fusionauth-search.service - LSB: Start FusionAuth
     Loaded: loaded (/etc/init.d/fusionauth-search; generated)
     Active: failed (Result: exit-code) since Thu 2020-08-06 23:20:47 PDT; 4s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 7852 ExecStart=/etc/init.d/fusionauth-search start (code=exited, status=1/FAILURE)

Aug 06 23:20:46 ubuntu systemd[1]: Starting LSB: Start FusionAuth...
Aug 06 23:20:47 ubuntu su[7878]: (to fusionauth) root on none
Aug 06 23:20:47 ubuntu su[7878]: pam_unix(su:session): session opened for user fusionauth by (uid=0)
Aug 06 23:20:47 ubuntu fusionauth-search[7852]: Starting FusionAuth Search Engine:
Aug 06 23:20:47 ubuntu su[7878]: pam_unix(su:session): session closed for user fusionauth
Aug 06 23:20:47 ubuntu systemd[1]: fusionauth-search.service: Control process exited, code=exited, statu>
Aug 06 23:20:47 ubuntu systemd[1]: fusionauth-search.service: Failed with result 'exit-code'.
Aug 06 23:20:47 ubuntu systemd[1]: Failed to start LSB: Start FusionAuth.

**Comment by robotdan** [comment]
This is not much to go on. You'll have to provide the log out from FusionAuth and Elasticsearch as well.

**Comment by ashish1247** [comment]
The given below log is from fusionauth-search.log:

[Aug 06, 2020 11:06:50.534 PM][ERROR][o.e.b.Bootstrap          ] [ubuntu] Exception
java.lang.RuntimeException: can not run elasticsearch as root
	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:105) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:172) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) [elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) [elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) [elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) [elasticsearch-cli-7.6.1.jar:7.6.1]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) [elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-7.6.1.jar:7.6.1]
[Aug 06, 2020 11:06:50.562 PM][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [ubuntu] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.RuntimeException: can not run elasticsearch as root
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:174) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) ~[elasticsearch-cli-7.6.1.jar:7.6.1]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.6.1.jar:7.6.1]
Caused by: java.lang.RuntimeException: can not run elasticsearch as root
	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:105) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:172) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.6.1.jar:7.6.1]
	... 6 more
[Aug 06, 2020 11:06:50.562 PM][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [ubuntu]  uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.RuntimeException: can not run elasticsearch as root
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:174) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) ~[elasticsearch-cli-7.6.1.jar:7.6.1]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.6.1.jar:7.6.1]
Caused by: java.lang.RuntimeException: can not run elasticsearch as root
	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:105) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:172) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.6.1.jar:7.6.1]
	... 6 more
uncaught exception in thread [main]
java.lang.RuntimeException: can not run elasticsearch as root
	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:105)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:172)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
For complete error details, refer to the log at /usr/local/fusionauth/logs/FusionAuth.log

**Comment by ashish1247** [comment]
And given below is log from fusionauth-app.log:

Tomcat started.
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
06-Aug-2020 23:06:43.123 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib]
06-Aug-2020 23:06:43.659 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-9011"]
06-Aug-2020 23:06:43.715 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
06-Aug-2020 23:06:43.746 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["https-jsse-nio-9013"]
06-Aug-2020 23:06:44.186 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
06-Aug-2020 23:06:44.190 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-127.0.0.1-9019"]
06-Aug-2020 23:06:44.193 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
06-Aug-2020 23:06:44.194 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 1387 ms
06-Aug-2020 23:06:44.203 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
06-Aug-2020 23:06:44.204 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.53
Aug 06, 2020 11:06:50 PM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Aug 06, 2020 11:06:51.207 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Loading FusionAuth configuration file [/usr/local/fusionauth/config/fusionauth.properties]
Aug 06, 2020 11:06:51.213 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Dynamically set property [fusionauth-app.url] set to [http://192.168.1.10:9011]
Aug 06, 2020 11:06:51.213 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Set Max HTTP header size to [10240].
Aug 06, 2020 11:06:51.923 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Loading FusionAuth configuration file [/usr/local/fusionauth/config/fusionauth.properties]
Aug 06, 2020 11:06:51.923 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Dynamically set property [fusionauth-app.url] set to [http://192.168.1.10:9011]
Aug 06, 2020 11:06:51.923 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Set Max HTTP header size to [10240].
Aug 06, 2020 11:06:51.957 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Loading FusionAuth configuration file [/usr/local/fusionauth/config/fusionauth.properties]
Aug 06, 2020 11:06:51.958 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Dynamically set property [fusionauth-app.url] set to [http://192.168.1.10:9011]
Aug 06, 2020 11:06:51.958 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Set Max HTTP header size to [10240].
Aug 06, 2020 11:06:52.030 PM INFO  io.fusionauth.app.maintenance.FusionAuthMaintenanceModeWorkflow - Determine database status : DOWN
Aug 06, 2020 11:06:52.031 PM INFO  org.primeframework.mvc.servlet.PrimeServletContextListener - Initializing Prime
Aug 06, 2020 11:06:52.032 PM INFO  io.fusionauth.app.maintenance.guice.FusionAuthMaintenanceModeModule - 

---------------------------------------------------------------------------------------------------------
--------------------------------------- Entering Maintenance Mode ---------------------------------------
---------------------------------------------------------------------------------------------------------

Aug 06, 2020 11:06:52.097 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Loading FusionAuth configuration file [/usr/local/fusionauth/config/fusionauth.properties]
Aug 06, 2020 11:06:52.097 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Dynamically set property [fusionauth-app.url] set to [http://192.168.1.10:9011]
Aug 06, 2020 11:06:52.097 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Set Max HTTP header size to [10240].
Aug 06, 2020 11:06:52.098 PM INFO  com.inversoft.maintenance.MaintenanceModePoller - Poller started to Wait for configuration to be completed.
06-Aug-2020 23:06:52.165 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-9011"]
06-Aug-2020 23:06:52.200 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["https-jsse-nio-9013"]
06-Aug-2020 23:06:52.211 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-127.0.0.1-9019"]
06-Aug-2020 23:06:52.219 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 8024 ms

**Comment by robotdan** [comment]
Your answer is right there in the log. :-) 

> [Aug 06, 2020 11:06:50.534 PM][ERROR][o.e.b.Bootstrap ] [ubuntu] Exception
java.lang.RuntimeException: can not run elasticsearch as root

**Comment by ashish1247** [comment]
Yeah got it. Thank you for quick reply! :)
