### ISSUE TITLE
Kickstart error part way through - SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by seanadkinson** [FusionAuth/fusionauth-issues#803]
### Description 
We had an error occur in the middle of a kickstart run in one of our environments.  It was a `SocketTimeoutException`.  The first request to create the API Key was successful, but not the second to create the admin user (actually the request was completed successfully, but kickstart didnt know that and errored out).

Possibly need a longer timeout, or at least a way to make it configurable for kickstart.

Since the API Key created successfully, additional restarts couldn't complete the rest of the kickstarts.  We had to delete the DB and restart.

### Affects versions
Docker on ECS, app version `1.18.3`

### Steps to reproduce

Kickstart file:
```
{
    "variables": {
        "apiKey": "#{ENV.FUSIONAUTH_API_KEY}",
        "defaultThemeId": "75a068fd-e94b-451a-9aeb-3ddb9a3b5987",
        "issuer": "#{ENV.FUSIONAUTH_ISSUER}",
        "streemTenantId": "#{ENV.FUSIONAUTH_STREEM_TENANT_ID}",
        "streemThemeId": "#{ENV.FUSIONAUTH_STREEM_THEME_ID}",
        "adminEmail": "#{ENV.FUSIONAUTH_ADMIN_EMAIL}",
        "adminPassword": "#{ENV.FUSIONAUTH_ADMIN_PASSWORD}",
        "emailFromAddress": "#{ENV.FUSIONAUTH_EMAIL_FROM_ADDRESS}",
        "emailFromName": "#{ENV.FUSIONAUTH_EMAIL_FROM_NAME}",
        "emailHost": "#{ENV.FUSIONAUTH_EMAIL_HOST}",
        "emailUsername": "#{ENV.FUSIONAUTH_EMAIL_USERNAME}",
        "emailPassword": "#{ENV.FUSIONAUTH_EMAIL_PASSWORD}",
        "googleAuthClientId": "#{ENV.GOOGLE_AUTH_CLIENT_ID}",
        "googleAuthClientSecret": "#{ENV.GOOGLE_AUTH_CLIENT_SECRET}"
    },
    "apiKeys": [
        {
            "key": "#{apiKey}"
        }
    ],
    "requests": [
        {
            "method": "POST",
            "url": "/api/user/registration",
            "body": {
                "user": {
                    "email": "#{adminEmail}",
                    "password": "#{adminPassword}"
                },
                "registration": {
                    "applicationId": "#{FUSIONAUTH_APPLICATION_ID}",
                    "roles": ["admin"]
                }
            }
        },
        {
            "method": "PATCH",
            "url": "/api/tenant/#{FUSIONAUTH_TENANT_ID}",
            "body": {
                "tenant": {
                    "issuer": "#{issuer}",
                    "emailConfiguration": {
                        "host": "#{emailHost}",
                        "port": 587,
                        "username": "#{emailUsername}",
                        "password": "#{emailPassword}",
                        "security": "TLS",
                        "defaultFromName": "#{emailFromName}",
                        "defaultFromEmail": "#{emailFromAddress}"
                    }
                }
            }
        },
        {
            "method": "POST",
            "url": "/api/tenant/#{streemTenantId}",
            "body": {
                "sourceTenantId": "#{FUSIONAUTH_TENANT_ID}",
                "tenant": {
                    "name": "streem"
                }
            }
        },
        {
            "method": "POST",
            "url": "/api/theme/#{streemThemeId}",
            "body": {
                "sourceThemeId": "#{defaultThemeId}",
                "theme": {
                    "name": "streem"
                }
            }
        },
        {
            "method": "POST",
            "url": "/api/identity-provider",
            "body": {
                "identityProvider": {
                    "buttonText": "Login with Google",
                    "client_id": "#{googleAuthClientId}",
                    "client_secret": "#{googleAuthClientSecret}",
                    "debug": true,
                    "enabled": true,
                    "scope": "openid profile email",
                    "type": "Google"
                }
            }
        }
    ]
}
```

Logs:
```
...
2020-08-10T13:33:34.154-07:00 | Aug 10, 2020 8:33:34.154 PM INFO  io.fusionauth.api.service.system.kickstart.KickstartRunner - Waiting for FusionAuth to complete startup in order to begin kickstart...
-- | --
  | 2020-08-10T13:33:34.260-07:00 | Aug 10, 2020 8:33:34.260 PM INFO com.inversoft.migration.Migrator - Run Cleanup [io.fusionauth.api.migration.guice.Migration_1_13_0]
  | 2020-08-10T13:33:34.843-07:00 | Aug 10, 2020 8:33:34.843 PM INFO com.inversoft.migration.Migrator - Run Once [io.fusionauth.api.migration.guice.Migration_1_15_3]
  | 2020-08-10T13:33:34.849-07:00 | Aug 10, 2020 8:33:34.848 PM INFO com.inversoft.migration.Migrator - Run Cleanup [io.fusionauth.api.migration.guice.Migration_1_15_3]
  | 2020-08-10T13:33:41.163-07:00 | Aug 10, 2020 8:33:41.162 PM ERROR io.fusionauth.api.service.system.kickstart.KickstartRunner - Failed to execute request to [POST][/api/user/registration] Status [-1]
  | 2020-08-10T13:33:41.163-07:00 | Request body:
  | 2020-08-10T13:33:41.163-07:00 | {
  | 2020-08-10T13:33:41.163-07:00 | "registration" : {
  | 2020-08-10T13:33:41.163-07:00 | "applicationId" : "3c219e58-ed0e-4b18-ad48-f4f92793ae32",
  | 2020-08-10T13:33:41.163-07:00 | "roles" : [ "admin" ]
  | 2020-08-10T13:33:41.163-07:00 | },
  | 2020-08-10T13:33:41.163-07:00 | "user" : {
  | 2020-08-10T13:33:41.163-07:00 | "email" : "...",
  | 2020-08-10T13:33:41.163-07:00 | "password" : "..."
  | 2020-08-10T13:33:41.163-07:00 | }
  | 2020-08-10T13:33:41.163-07:00 | }
  | 2020-08-10T13:33:41.243-07:00 | Aug 10, 2020 8:33:41.242 PM ERROR io.fusionauth.api.service.system.kickstart.KickstartRunner - Exception returned
  | 2020-08-10T13:33:41.243-07:00 | java.net.SocketTimeoutException: Read timed out
  | 2020-08-10T13:33:41.243-07:00 | at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
  | 2020-08-10T13:33:41.243-07:00 | at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
  | 2020-08-10T13:33:41.243-07:00 | at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
  | 2020-08-10T13:33:41.243-07:00 | at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
  | 2020-08-10T13:33:41.243-07:00 | at java.base/java.net.Socket$SocketInputStream.read(Socket.java:982)
  | 2020-08-10T13:33:41.243-07:00 | at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
  | 2020-08-10T13:33:41.243-07:00 | at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
  | 2020-08-10T13:33:41.243-07:00 | at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
  | 2020-08-10T13:33:41.243-07:00 | at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:754)
  | 2020-08-10T13:33:41.243-07:00 | at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
  | 2020-08-10T13:33:41.243-07:00 | at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1618)
  | 2020-08-10T13:33:41.243-07:00 | at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1523)
  | 2020-08-10T13:33:41.243-07:00 | at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
  | 2020-08-10T13:33:41.243-07:00 | at com.inversoft.rest.RESTClient.go(RESTClient.java:218)
  | 2020-08-10T13:33:41.243-07:00 | at io.fusionauth.api.service.system.kickstart.KickstartRunner.run(KickstartRunner.java:115)
  | 2020-08-10T13:33:41.243-07:00 | at java.base/java.lang.Thread.run(Thread.java:832)
...
```

### Expected behavior
Kickstart completes successfully if possible.

### Screenshots
N/A

### Platform
 - Device: Server on AWS ECS
 - OS: Docker
 - Browser + version: N/A
 - Database PostgresSQL 10, using DB search, not elasticsearch

### Additional context
This was running in ECS as a container configured with 1gb memory, 1/2 cpu.  I realized I didn't set `FUSIONAUTH_MEMORY`, so FA didn't know about the additional memory available.

**Comment by robotdan** [comment]
We default the read timeout to 5 seconds which is quite a long time. 

We could look into exposing these values in the kickstart configuration, but if you're seeing timeouts the system is likely very resource constrained or there is a high latency between the container and the database.

**Comment by seanadkinson** [comment]
@robotdan We continue to get this error occasionally (feels like maybe 50% of the time, anecdotally) when spinning up new environments.  It might have something to do with Fargate getting itself situated, or maybe something else, but we need the ability to specify a higher read timeout, or have a higher default for kickstart, as this really borks the environment.

**Comment by robotdan** [comment]
We'll make this configurable, if it still times out after that, we'll have to dig deeper to see it is taking so long to respond.

**Comment by robotdan** [comment]
@seanadkinson closing for now, this is now configurable, and will be documented in the kickstart guide. Please re-open if you still encounter this as perhaps there is another underlying issue. 

https://fusionauth.io/docs/v1/tech/installation-guide/kickstart/

Until that doc is up, here is example of adding this to kickstart:

This `settings` object is a top level object in your kickstart file:

```
  "settings": {
    "connectTimeout": 7000,
    "readTimeout": 7000
  },
```

This is in milliseconds, the default is `5000`.
