### ISSUE TITLE
FA 1.19.0 does not start if search.type=database

### ISSUE THREAD

**Issue by motzel** [FusionAuth/fusionauth-issues#846]
### Description 
I do not use ElasticSearch for searching, search.type is set to database. And yet FusionAuth is still trying to connect to ElasticSearch:

```
fa-fusionauth |
fa-fusionauth |   Unable to start the server. Here's why:
fa-fusionauth |
fa-fusionauth |
fa-fusionauth | [Error injecting constructor, java.lang.IllegalArgumentException: hosts must not be null nor empty]
fa-fusionauth |         -> [class java.lang.IllegalArgumentException] hosts must not be null nor empty
fa-fusionauth |
fa-fusionauth | ===================================================================================================
fa-fusionauth |
fa-fusionauth |
fa-fusionauth | 2020-09-04 8:07:15.421 AM ERROR org.primeframework.mvc.guice.GuiceBootstrap - Unable to start the server. Exception:
fa-fusionauth |
fa-fusionauth | com.google.inject.CreationException: Unable to create injector, see the following errors:
fa-fusionauth |
fa-fusionauth | 1) Error injecting constructor, java.lang.IllegalArgumentException: hosts must not be null nor empty
fa-fusionauth |   at io.fusionauth.api.service.search.ElasticSearchClientProvider.<init>(ElasticSearchClientProvider.java:30)
fa-fusionauth |   at io.fusionauth.api.service.guice.ServiceModule.configure(ServiceModule.java:163) (via modules: io.fusionauth.app.guice.FusionAuthModule -> com.google.inject.util.Modules$OverrideModule -> io.fusionauth.api.guice.APIModule -> io.fusionauth.api.service.guice.ServiceModule)
fa-fusionauth |   while locating io.fusionauth.api.service.search.ElasticSearchClientProvider
fa-fusionauth |
fa-fusionauth | 1 error
fa-fusionauth |         at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:554)
fa-fusionauth |         at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:188)
fa-fusionauth |         at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:111)
fa-fusionauth |         at com.google.inject.Guice.createInjector(Guice.java:87)
fa-fusionauth |         at com.google.inject.Guice.createInjector(Guice.java:69)
fa-fusionauth |         at com.google.inject.Guice.createInjector(Guice.java:59)
fa-fusionauth |         at org.primeframework.mvc.guice.GuiceBootstrap.initialize(GuiceBootstrap.java:58)
fa-fusionauth |         at com.inversoft.maintenance.MaintenanceModeService.done(MaintenanceModeService.java:67)
fa-fusionauth |         at com.inversoft.maintenance.MaintenanceModeThreadSafeHelper.areWeDoneYet(MaintenanceModeThreadSafeHelper.java:59)
fa-fusionauth |         at com.inversoft.maintenance.MaintenanceModePoller.lambda$new$1(MaintenanceModePoller.java:46)
fa-fusionauth |         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
fa-fusionauth |         at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
fa-fusionauth |         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
fa-fusionauth |         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
fa-fusionauth |         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
fa-fusionauth |         at java.base/java.lang.Thread.run(Thread.java:832)
fa-fusionauth | Caused by: java.lang.IllegalArgumentException: hosts must not be null nor empty
fa-fusionauth |         at org.elasticsearch.client.RestClient.builder(RestClient.java:173)
fa-fusionauth |         at com.inversoft.search.ElasticRestClientHelper.buildClient(ElasticRestClientHelper.java:73)
fa-fusionauth |         at io.fusionauth.api.service.search.ElasticSearchClientProvider.<init>(ElasticSearchClientProvider.java:32)
fa-fusionauth |         at io.fusionauth.api.service.search.ElasticSearchClientProvider$$FastClassByGuice$$d7116b9a.newInstance(<generated>)
fa-fusionauth |         at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
fa-fusionauth |         at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
fa-fusionauth |         at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
fa-fusionauth |         at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
fa-fusionauth |         at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
fa-fusionauth |         at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
fa-fusionauth |         at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
fa-fusionauth |         at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
fa-fusionauth |         at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
fa-fusionauth |         ... 14 common frames omitted
```

I added search.servers to the configuration file:
```
search.type=database
search.servers=http://localhost:9021
```
...and the server has started. However, there are still regular attempts to connect to ElasticSearch:

```
fa-fusionauth | Sep 04, 2020 8:12:11 AM org.elasticsearch.client.sniff.Sniffer run
fa-fusionauth | SEVERE: error while sniffing nodes
fa-fusionauth | java.net.ConnectException: Connection refused
fa-fusionauth |         at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:823)
fa-fusionauth |         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:248)
fa-fusionauth |         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235)
fa-fusionauth |         at org.elasticsearch.client.sniff.ElasticsearchNodesSniffer.sniff(ElasticsearchNodesSniffer.java:105)
fa-fusionauth |         at org.elasticsearch.client.sniff.Sniffer.sniff(Sniffer.java:209)
fa-fusionauth |         at org.elasticsearch.client.sniff.Sniffer$Task.run(Sniffer.java:139)
fa-fusionauth |         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
fa-fusionauth |         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
fa-fusionauth |         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
fa-fusionauth |         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
fa-fusionauth |         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
fa-fusionauth |         at java.base/java.lang.Thread.run(Thread.java:832)
fa-fusionauth | Caused by: java.net.ConnectException: Connection refused
fa-fusionauth |         at java.base/sun.nio.ch.Net.pollConnect(Native Method)
fa-fusionauth |         at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:589)
fa-fusionauth |         at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:839)
fa-fusionauth |         at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174)
fa-fusionauth |         at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148)
fa-fusionauth |         at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
fa-fusionauth |         at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221)
fa-fusionauth |         at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
fa-fusionauth |         ... 1 more
```

### Affects versions
1.19.0

### Steps to reproduce

No specific steps. Just run the official docker image with the default configuration.

### Expected behavior
FusionAuth will not try to connect to ElasticSearch.

### Platform
- Docker image: fusionauth/fusionauth-app:1.19.0
- Database: PostgreSQL (also docker image - postgres:9.6)

**Comment by robotdan** [comment]
Thanks for reporting @motzel , this is likely an issue with the configuration updates from 1.19.0. We'll take a look.

**Comment by robotdan** [comment]
Same root issue as #847
