### ISSUE TITLE
issue with random 500s on login for users

### ISSUE THREAD

**Issue by zbruhnke** [FusionAuth/fusionauth-issues#868]
## (Put bug title here)
issue with random 500s on login for users
### Description 
We're seeing what seems like intermittent errors (possibly related to Elasticsearch?) where users can successfully login but then their 2FA code seems to be denied even though its actually correct.

This mostly appears to be happening with 2FA via text message but we have seen some instances of app based 2FA as well (authy specifically)

### Affects versions
List the version you are running, and any other versions you have attempted a recreated. 
1.13.1

### Platform
(Please complete the following information)
- This seems to be across all platforms

### Additional context

```
java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
	at org.apache.http.util.Asserts.check(Asserts.java:46)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:343)
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:325)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:218)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:191)
	at com.inversoft.search.AbstractElasticSearchSearchEngine.request(AbstractElasticSearchSearchEngine.java:158)
	at com.inversoft.search.AbstractElasticSearchSearchEngine.request(AbstractElasticSearchSearchEngine.java:182)
	at io.fusionauth.api.service.search.ElasticsearchSearchEngine.index(ElasticsearchSearchEngine.java:144)
	at io.fusionauth.api.service.user.DefaultUserService.verifyEmail(DefaultUserService.java:1586)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
	at io.fusionauth.app.action.api.user.VerifyEmailAction.post(VerifyEmailAction.java:68)
	at sun.reflect.GeneratedMethodAccessor100.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.primeframework.mvc.util.ReflectionUtils.invoke(ReflectionUtils.java:414)
	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.execute(DefaultActionInvocationWorkflow.java:79)
	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.perform(DefaultActionInvocationWorkflow.java:62)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:47)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.security.DefaultSecurityWorkflow.perform(DefaultSecurityWorkflow.java:65)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.parameter.DefaultPostParameterWorkflow.perform(DefaultPostParameterWorkflow.java:50)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.content.DefaultContentWorkflow.perform(DefaultContentWorkflow.java:52)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:57)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:102)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:58)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:45)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at io.fusionauth.app.primeframework.FrontEndTenantWorkflow.perform(FrontEndTenantWorkflow.java:69)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:126)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.workflow.StaticResourceWorkflow.perform(StaticResourceWorkflow.java:97)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.parameter.RequestBodyWorkflow.perform(RequestBodyWorkflow.java:89)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:57)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at io.fusionauth.app.primeframework.CORSFilter.handleNonCORS(CORSFilter.java:291)
	at io.fusionauth.app.primeframework.CORSFilter.doFilter(CORSFilter.java:252)
	at io.fusionauth.app.primeframework.CORSRequestWorkflow.perform(CORSRequestWorkflow.java:48)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:43)
	at io.fusionauth.app.primeframework.FusionAuthMVCWorkflow.perform(FusionAuthMVCWorkflow.java:88)
	at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44)
	at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50)
	at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:84)
	at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by robotdan** [comment]
Perhaps this issue? 

https://github.com/elastic/elasticsearch/issues/39946 which seems to be solved via https://github.com/elastic/elasticsearch/issues/49124. 

If this is the correct fix, it is said to be fixed in Apache HTTP Core 4.4.13, and we are using version 4.4.12 via Elasticsearch REST client. 

We'll do some additional research and see if this looks to be the issue. 

If you want to try this on your own - you could replace the `4.4.12` version of this jar with `4.4.13` in the classpath. Depending upon how you are deploying, this may mean you need to repackage the docker image / bundle. 

Here are the current versions:
```
/usr/local/fusionauth/fusionauth-app/web/WEB-INF/lib/httpclient-4.5.10.jar
/usr/local/fusionauth/fusionauth-app/web/WEB-INF/lib/httpcore-4.4.12.jar
/usr/local/fusionauth/fusionauth-app/web/WEB-INF/lib/httpcore-nio-4.4.12.jar
```


More details : https://github.com/elastic/elasticsearch/issues/49124#issuecomment-692104856

**Comment by robotdan** [comment]
Trying to see if we can figure out exactly where the fix was delivered, the release notes for Apache HTTP Core don't look to mention anything. See thread here: https://github.com/elastic/elasticsearch/issues/49124#issuecomment-693492779

**Comment by robotdan** [comment]
This looks to the Jira issue that resolves the root issue. https://issues.apache.org/jira/browse/HTTPASYNC-160

It says that the fix is in version `4.1.4` of the Async HTTP client which is not yet available.
https://downloads.apache.org/httpcomponents/httpasyncclient/RELEASE_NOTES-4.1.x.txt

We'll have to watch for `4.1.4` to be released and see if it contains `HTTPASYNC-160`.  Hopefully the Elasticsearch client will also pick up this version once released.

**Comment by zbruhnke** [comment]
@robotdan are you guys not seeing this on your hosted deployments? I'm kind of surprised we're the only ones reporting this issue

**Comment by robotdan** [comment]
Nope, I have not seen this and you're the first to bring it up. 

The last update on this thread: https://github.com/elastic/elasticsearch/issues/49124#issuecomment-693552262 indicates this is actually a working as design issue - as far as the Apache HTTP core library is concerned (if I'm reading that right). 

And in the Elasticsearch client version >= 5 they have perhaps fixed it partially. 

Additional thread here that was suggested from the above GitHub issue: http://mail-archives.apache.org/mod_mbox/hc-dev/202006.mbox/%3c9ef305d3a9587370ded5611b1dc55c25c29e3fc4.camel@apache.org%3e

**Comment by zbruhnke** [comment]
Thanks for this ... that's a pretty damning conclusion, from your perspective it sounds like there is currently no "right" answer for us to try on our setup other than to potentially see these intermittent issues right now?

**Comment by robotdan** [comment]
Not sure yet. From this comment elastic/elasticsearch#49124 (comment) - it looks like we may be able to add our own exception handler on behalf of the Elasticsearch client to handle these exceptions. 

I need to dig into it a bit further, but if that is the case, that means we could ship a patch with some custom code to handle these expected exceptions (from the HTTP core library's perspective) and not cause a failure in Elasticsearch.

**Comment by zbruhnke** [comment]
OK Great, please keep me in the loop, looks like as sessions grow we're seeing this more often albeit still on an intermittent basis

**Comment by robotdan** [comment]
I have prototyped an exception handler, since I cannot recreate, I'm sort of flying blind. But in theory this should take care of it, I'll run with it a bit but should be able to get it out in a patch release.

**Comment by zbruhnke** [comment]
Thanks @robotdan !

**Comment by robotdan** [comment]
Delivered an exception handler in 1.19.7. Once you get a chance to start running with that version let us know if you see these errors anymore.
