### ISSUE TITLE
Initial catalina port -1 causes exception 

### ISSUE THREAD

**Issue by rmr** [FusionAuth/fusionauth-issues#902]
### Description 
2020-10-01 9:59:41.607 AM INFO  io.fusionauth.api.service.system.NodeService - Node [29daa892-0288-4d93-ae4c-fdb0c237b14b] promoted to master at [2020-10-01T09:59:41.607056Z], the previous master Node [54332afd-1235-4c03-8917-26a827b5e799] has been shutdown or removed
01-Oct-2020 09:59:43.931 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-9011"]
01-Oct-2020 09:59:43.976 SEVERE [main] org.apache.catalina.core.StandardService.startInternal Failed to start connector [Connector[AJP/1.3-auto-2]]
	org.apache.catalina.LifecycleException: The connector cannot start since the specified port value of [-1] is invalid
		at org.apache.catalina.connector.Connector.startInternal(Connector.java:1093)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:440)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:766)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:688)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:564)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
01-Oct-2020 09:59:43.977 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 20431 ms

### Affects versions
1.19.8 

### Steps to reproduce
Kubernetes startup

### Platform
Kubernetes

File fusionauth.properties

fusionauth-app.memory=512M
search.type=database
fusionauth-app.http.port=9011

**Comment by robotdan** [comment]
Do you also have have `fusionauth-app.http-port` specified in your `fusionauth.properties` file, or do you have the environment variable `FUSIONAUTH_APP_HTTP_PORT` or `FUSIONAUTH_HTTP_PORT` defined anywhere?

**Comment by rmr** [comment]
I only use the fusionauth.properties file. I removed the environmental variables.

**Comment by robotdan** [comment]
Your k8s config is not using any environment variables? Can you post your k8s config? Need more information. Thanks.

**Comment by Pckool** [comment]
I am also having the same issue and I am setting the `FUSIONAUTH_APP_HTTP_PORT` env variable

**Comment by mooreds** [comment]
@Pckool 

Can you please provide us with information needed to reproduce? At a minimum:

* fusionauth version
* k8s config
* environment variables
* which version of k8s you are running

Thanks!

**Comment by robotdan** [comment]
Closing. Let us know if you still can recreate this issue, and please provide all environment variables, fusionauth config files, etc. so we can review. Thanks!
