### ISSUE TITLE
Admin screen barfs on users registered to an application in a different tenant than the user

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#914]
### Description 

Admin screen shows errors when a user is registered to an application in a different tenant.

### Affects versions

1.19.8

### Steps to reproduce
1. Create two tenants (tenantA, tenantB).
1. Create an application (appA) in tenantA.
1. Import a user into tenantB (using import apis, unsure about the user creation api, haven't tested that) and at the same time register them for appA.
1. View the user in the administrative user interface.
1. See error

```
FreeMarker template error (DEBUG mode; use RETHROW in production!): The following has evaluated to null or missing: ==> applications(registration.applicationId) [in template "WEB-INF/templates/admin/user/_macros.ftl" at line 407, column 32] ---- Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)?? ---- ---- FTL stack trace ("~" means nesting-related): - Failed at: #assign application = applications(re... [in template "WEB-INF/templates/admin/user/_macros.ftl" in macro "registrationsTable" at line 407, column 9] - Reached through: @userMacros.registrationsTable [in template "WEB-INF/templates/admin/user/manage.ftl" at line 105, column 11] ~ Reached through: #nested [in template "WEB-INF/templates/_utils/panel.ftl" in macro "full" at line 15, column 9] ~ Reached through: @panel.full panelClass="panel ${panel... [in template "WEB-INF/templates/admin/user/manage.ftl" at line 88, column 7] ~ Reached through: #nested [in template "WEB-INF/templates/_layouts/admin.ftl" in macro "main" at line 344, column 5] ~ Reached through: @layout.main [in template "WEB-INF/templates/admin/user/manage.ftl" at line 74, column 5] ~ Reached through: #nested [in template "WEB-INF/templates/_layouts/admin.ftl" in macro "body" at line 324, column 5] ~ Reached through: @layout.body [in template "WEB-INF/templates/admin/user/manage.ftl" at line 30, column 3] ~ Reached through: #nested [in template "WEB-INF/templates/_layouts/admin.ftl" in macro "html" at line 14, column 3] ~ Reached through: @layout.html [in template "WEB-INF/templates/admin/user/manage.ftl" at line 21, column 1] ---- Java stack trace (for programmers): ---- freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...] at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134) at freemarker.core.Assignment.accept(Assignment.java:139) at freemarker.core.Environment.visit(Environment.java:370) at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291) at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271) at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244) at freemarker.core.Environment.visitIteratorBlock(Environment.java:644) at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108) at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94) at freemarker.core.Environment.visit(Environment.java:334) at freemarker.core.Environment.visit(Environment.java:376) at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:876) at freemarker.core.Environment.invokeMacro(Environment.java:812) at 
...
```

### Expected behavior

Either application registration fails if the user and app are in different tenants (preferable, may have perf impacts for import) or at the least there are no registrations shown for user if they are registered for an application that is not in the tenant the user is in.

### Additional context

These users were put into an application via the import api.

Reported by a client: https://fusionauth.slack.com/archives/GNURTTC8N/p1601936398268900

**Comment by robotdan** [comment]
Oops, I also opened a bug. Fixing under https://github.com/FusionAuth/fusionauth-issues/issues/915 .
