### ISSUE TITLE
Patch user with null preferredLanguage returns 500 error

### ISSUE THREAD

**Issue by nicko** [FusionAuth/fusionauth-issues#956]
### Description 
Attempting to patch user.preferredLanguages to `null` to remove all languages as per the note in the docs in the User section: https://fusionauth.io/docs/v1/tech/apis/users/#update-a-user

When sending `null` via postman I recieve a 500 error. Checking the logs I can see an exception:

```
java.lang.NullPointerException: null
    at io.fusionauth.domain.User.normalize(User.java:313)
    at io.fusionauth.app.action.api.UserAction.validatePutAndPatch(UserAction.java:234)
   ....
```

### Affects versions
fusionauth/fusionauth-app:1.18.7

### Steps to reproduce
1. Create a new user in FusionAuth
```
curl --location --request POST '{{hostname}}/api/user/registration/897c5957-7f15-413a-94d1-6300dc03d714' \
--header 'Authorization: ...' \
--header 'X-FusionAuth-TenantId: ...' \
--header 'Content-Type: application/json' \
--header 'Cookie: JSESSIONID=...' \
--data-raw '{
    "generateAuthenticationToken": true,
    "user": {
        "username": "...",
        "sendSetPasswordEmail": "false",
        "skipVerification": true,
        "password": "..."
    },
    "registration": {
        "applicationId": "..."
    }
}'
```

2. Update that user with a null `preferreredLanguages` property.

```
curl --location --request PATCH '{{hostname}}/api/user/897c5957-7f15-413a-94d1-6300dc03d714' \
--header 'Authorization: ...' \
--header 'X-FusionAuth-TenantId: ...' \
--header 'Content-Type: application/json' \
--header 'Cookie: JSESSIONID=...' \
--data-raw '{
    "user": {
        "preferredLanguages": null
    }
}'
```

3. Observe 500 error and response body:
```
{
    "generalErrors": [
        {
            "code": "[Exception]",
            "message": "FusionAuth encountered an unexpected error. Please contact support for assistance."
        }
    ]
}
```

### Expected behavior
According to the docs, sending a `null` for this property should clear the array. This is due to limitations in the PATCH method which will only ever _merge_ arrays of values. 

**My Purpose**
The reason I'm sending this value is to _replace_ the user's preferred language so I'm actually sending a `null` followed by a new language. If there was an explicit way to replace the preferred language(s) then that would be even better.

### Platform
(Please complete the following information)
 - Calling using Postman
 - Database Postgres, not sure what version

From admin Home > System > About
```
Version: | 1.18.7
Latest version: | 1.20.0
Nodes: | 3
```

**Comment by mooreds** [comment]
@nicko this appears to be a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/706 . Is that correct? If so, I'll close and we can track the issue there.

If not, please let us know that too.

**Comment by nicko** [comment]
@mooreds it is! Sorry about that, I did check before I create it but must have missed that one. Any idea when a fix will be merged?

**Comment by mooreds** [comment]
No worries, I file dupes sometimes too.

We can't commit to any timelines for fixing specific bugs, unfortunately. Sorry! I will note that this is affecting you on the original bug.
