### ISSUE TITLE
Authenticating as an unknown user causes internal BCrypt error

### ISSUE THREAD

**Issue by wasdennnoch** [FusionAuth/fusionauth-issues#966]
### Description 
When trying to log in with a random loginId which does not exist, and the tenant is set to use BCrypt as the password hashing method, you are greeted with the error message "FusionAuth encountered an unexpected error". This does not happen when the loginId is valid, only with invalid users.
To confirm this wasn't an issue caused by a failed FusionAuth upgrade on my end I had a look through the code mentioned in the stack trace, and I suspect the error cause is `DefaultAuthenticationService#slowItDown()` trying to encrypt the value `"enumerate"` with the string `"this"` (4 bytes) as the salt whenever authentication fails, but the `BCryptPasswordEncryptor` expects the salt to always be 16 bytes.

### Affects versions
1.19.8, problematic code seems to also exist in 1.20.1

### Steps to reproduce
1. Enter random login credentials
2. Try to log in

### Expected behavior
A message along the lines of "invalid credentials" should be displayed.

### Platform
 - OS: Ubuntu Server 18.04.5
 - Browser: Chrome 86
 - Database: PostgresSQL 12.1, Elasticsearch 6.8.6

### Additional context
```
2020-10-21 10:05:06.668 AM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown,
java.lang.IllegalArgumentException: Bad salt length,
	at io.fusionauth.api.security.BCryptPasswordEncryptor$BCrypt.crypt(BCryptPasswordEncryptor.java:540),
	at io.fusionauth.api.security.BCryptPasswordEncryptor$BCrypt.hashPassword(BCryptPasswordEncryptor.java:404),
	at io.fusionauth.api.security.BCryptPasswordEncryptor.encrypt(BCryptPasswordEncryptor.java:41),
	at io.fusionauth.api.service.authentication.DefaultAuthenticationService.slowItDown(DefaultAuthenticationService.java:397),
	at io.fusionauth.api.service.authentication.DefaultAuthenticationService.validateUserForAuthentication(DefaultAuthenticationService.java:411),
	at io.fusionauth.api.service.authentication.DefaultAuthenticationService._authenticate(DefaultAuthenticationService.java:112),
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96),
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96),
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96),
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96),
	at io.fusionauth.api.service.authentication.DefaultAuthenticationService.authenticate(DefaultAuthenticationService.java:165),
	at io.fusionauth.app.action.api.LoginAction.lambda$post$1(LoginAction.java:126),
	at io.fusionauth.app.action.api.BaseLoginAction.callLogin(BaseLoginAction.java:165),
	at io.fusionauth.app.action.api.LoginAction.post(LoginAction.java:126),
	at jdk.internal.reflect.GeneratedMethodAccessor1428.invoke(Unknown Source),
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at java.base/java.lang.reflect.Method.invoke(Method.java:564),
	at org.primeframework.mvc.util.ReflectionUtils.invoke(ReflectionUtils.java:414),
	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.execute(DefaultActionInvocationWorkflow.java:79),
	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.perform(DefaultActionInvocationWorkflow.java:62),
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51),
	at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:47),
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51),
	at org.primeframework.mvc.security.DefaultSecurityWorkflow.perform(DefaultSecurityWorkflow.java:81),
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51),
	at org.primeframework.mvc.parameter.DefaultPostParameterWorkflow.perform(DefaultPostParameterWorkflow.java:50),
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51),
	at org.primeframework.mvc.content.DefaultContentWorkflow.perform(DefaultContentWorkflow.java:52),
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51),
	at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:57),
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51),
	at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:102),
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51),
	at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:58),
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51),
	at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:44),
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51),
	at io.fusionauth.app.primeframework.FrontEndTenantWorkflow.perform(FrontEndTenantWorkflow.java:71),
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51),
	at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:126),
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51),
	at org.primeframework.mvc.workflow.StaticResourceWorkflow.perform(StaticResourceWorkflow.java:97),
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51),
	at org.primeframework.mvc.parameter.RequestBodyWorkflow.perform(RequestBodyWorkflow.java:89),
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51),
	at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:64),
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51),
	at io.fusionauth.app.primeframework.CORSFilter.handleNonCORS(CORSFilter.java:291),
	at io.fusionauth.app.primeframework.CORSFilter.doFilter(CORSFilter.java:252),
	at io.fusionauth.app.primeframework.CORSRequestWorkflow.perform(CORSRequestWorkflow.java:48),
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51),
	at io.fusionauth.app.primeframework.FusionAuthMVCWorkflow.perform(FusionAuthMVCWorkflow.java:88),
	at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44),
	at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50),
	at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:78),
	at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:59),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199),
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96),
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543),
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139),
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81),
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87),
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343),
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615),
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65),
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818),
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626),
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49),
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130),
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630),
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61),
	at java.base/java.lang.Thread.run(Thread.java:832),
```

**Comment by robotdan** [comment]
Thanks for reporting @wasdennnoch we'll get this fixed ASAP.
