### ISSUE TITLE
Unable to set CORS with kickstart

### ISSUE THREAD

**Issue by pigletto** [FusionAuth/fusionauth-issues#986]
### Description 
I'd like to set CORS headers with kickstart but when executed it raises an exception. I used the following kickstart code:

```
{
      "method": "PATCH",
      "url": "/api/systemConfiguration",
      "body": {
        "systemConfiguration": {
          "corsConfiguration": {
            "allowedMethods": [
              "GET",
              "POST",
              "PUT",
              "OPTIONS"
            ],
            "allowedOrigins": [
              "https://example.com"
            ]
          }
        }
      }
    },
```

The kickstart fails with the following error:

```
fusionauth_1            | 2020-11-13 7:31:35.108 AM ERROR io.fusionauth.api.service.system.kickstart.KickstartRunner - Failed to execute request to [PATCH][/api/systemConfiguration] Status [404]
fusionauth_1            | Request body:
fusionauth_1            | {
fusionauth_1            |   "systemConfiguration" : {
fusionauth_1            |     "corsConfiguration" : {
fusionauth_1            |       "allowedMethods" : [ "GET", "POST", "PUT", "OPTIONS" ],
fusionauth_1            |       "allowedOrigins" : [ "https://example.com" ]
fusionauth_1            |     }
fusionauth_1            |   }
fusionauth_1            | }
fusionauth_1            | 2020-11-13 7:31:35.112 AM ERROR io.fusionauth.api.service.system.kickstart.KickstartRunner - Exception returned
fusionauth_1            | com.inversoft.rest.JSONException: Failed to parse the HTTP response as JSON. Actual HTTP response body:
fusionauth_1            | 
fusionauth_1            | <!DOCTYPE html>
fusionauth_1            | <html lang="en">
fusionauth_1            | <head>
fusionauth_1            |   <title>404
fusionauth_1            |       at com.inversoft.rest.JSONResponseHandler.apply(JSONResponseHandler.java:61)
fusionauth_1            |       at com.inversoft.rest.RESTClient.go(RESTClient.java:234)
fusionauth_1            |       at io.fusionauth.api.service.system.kickstart.KickstartRunner.run(KickstartRunner.java:115)
fusionauth_1            |       at java.base/java.lang.Thread.run(Thread.java:832)
fusionauth_1            | Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
fusionauth_1            |  at [Source: (com.inversoft.rest.JSONResponseHandler$BetterBufferedInputStream); line: 2, column: 2]
fusionauth_1            |       at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
fusionauth_1            |       at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
fusionauth_1            |       at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
fusionauth_1            |       at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2655)
fusionauth_1            |       at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:857)
fusionauth_1            |       at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:754)
fusionauth_1            |       at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4356)
fusionauth_1            |       at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4205)
fusionauth_1            |       at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3251)
fusionauth_1            |       at com.inversoft.rest.JSONResponseHandler.apply(JSONResponseHandler.java:56)
fusionauth_1            |       ... 3 common frames omitted
```

### Affects versions
FusionAuth 1.20.1

### Steps to reproduce
1. Create kickstart file with the fragment that sets the CORS (like the one above)
2. Start FusionAuth with the kickstart
3. See error

### Expected behavior
I'd expect kickstart to proceed without errors

### Platform
 - Device: docker (Fusionauth based image)
 - Database PostgreSQL & Elasticsearch

### Additional context
API call like this one works properly after the FA is initialized:
$ curl -v -X PATCH -H 'Authorization: XKqpOnYxxxxxxxxxxwTPiGZl4-AWnSJ5du3tZf1N58' -H 'Content-Type: application/json' -d '{"systemConfiguration": {"corsConfiguration": {"allowedMethods": ["GET", "POST","PUT","OPTIONS"],"allowedOrigins": ["https://example.com"]}}}' "https://auth.examp.le/api/system-configuration"

**Comment by mooreds** [comment]
I think you pointed to the wrong endpoint in kickstart.

```
"url": "/api/systemConfiguration",
```

should be

```
"url": "/api/system-configuration",
```

Can you please try that and let me know if it works?

**Comment by pigletto** [comment]
Ahh... you're right. I've messed up the URL. Thanks for the hint!
